from __future__ import annotations

try:
    from phase_generation_lib import generate_batch
except ImportError:
    from tools.phase_generation_lib import generate_batch


PHASES = [
    {
        "id": 55,
        "topic": "Conic sections",
        "subtopic": "Parabolas, circles, ellipses, and hyperbolas in standard form",
        "prerequisites": "coordinate plane, distance formula, completing the square, quadratic graphs",
        "metadata_prereq": "coordinate_plane, distance_formula, completing_square, quadratic_graphs",
        "metadata_misconceptions": "confuses_conic_forms, drops_square_completion_constant, swaps_a_and_b, ignores_center_translation",
        "review": [
            "Use the distance formula to measure from a point to a center.",
            "Complete the square by adding the same square-making constant inside the equation.",
            "Recognize horizontal and vertical translations from expressions like x - h and y - k.",
            "Connect squared terms to graph shapes on the coordinate plane.",
            "Check whether a point satisfies an equation by substitution.",
        ],
        "concepts": [
            "A circle has equal squared denominators and stores all points a fixed distance from its center.",
            "A parabola has one squared variable and is controlled by the directed distance p from vertex to focus.",
            "An ellipse has two added squared terms with positive denominators and a longer major axis.",
            "A hyperbola has two squared terms that subtract and has asymptotes through its center.",
            "Completing the square reveals the translated center or vertex before graph features are read.",
        ],
        "misconceptions": [
            "Treating every equation with squared variables as a circle.",
            "Forgetting to add square-completion constants to the opposite side of the equation.",
            "Reading the center signs directly instead of reversing the signs in x - h and y - k.",
            "Using a^2 - b^2 for hyperbola foci instead of a^2 + b^2.",
            "Calling the larger denominator a horizontal axis without checking which variable owns it.",
        ],
        "exercises": [
            {
                "focus": "Classifying a circle from standard form",
                "question": "Classify the conic x^2 + y^2 = 25 and name its center and radius.",
                "answer": "Circle with center (0, 0) and radius 5.",
                "explanation": "Both squared terms are added with the same coefficient, so the graph is a circle. Since x^2 + y^2 = 5^2, the center is (0, 0) and the radius is 5.",
                "type": "Classification",
                "skill": "Recognize conic type from standard form",
                "visual": True,
                "distractors": "calls it an ellipse because two variables are squared; gives radius 25; gives center (5, 5); says the radius is sqrt(25)/2",
            },
            {
                "focus": "Reading circle features",
                "question": "Find the center and radius of (x - 3)^2 + (y + 2)^2 = 49.",
                "answer": "Center (3, -2), radius 7.",
                "explanation": "A circle in standard form is (x - h)^2 + (y - k)^2 = r^2. Here h = 3, k = -2, and r^2 = 49, so r = 7.",
                "type": "Feature identification",
                "skill": "Read translated circle form",
                "visual": True,
                "distractors": "uses center (-3, 2); gives radius 49; gives radius 7 but center (3, 2); treats it as a parabola",
            },
            {
                "focus": "Writing a circle equation",
                "question": "Write the equation of the circle with center (-1, 4) and radius 6.",
                "answer": "(x + 1)^2 + (y - 4)^2 = 36.",
                "explanation": "Use (x - h)^2 + (y - k)^2 = r^2. With h = -1, k = 4, and r = 6, the equation is (x + 1)^2 + (y - 4)^2 = 36.",
                "type": "Construction",
                "skill": "Build a circle equation from features",
                "visual": True,
                "distractors": "writes (x - 1)^2 + (y + 4)^2 = 36; uses 6 instead of 36; swaps h and k; omits the squares",
            },
            {
                "focus": "Completing the square for a circle",
                "question": "Rewrite x^2 + y^2 - 6x + 4y - 12 = 0 in standard form and identify the circle.",
                "answer": "(x - 3)^2 + (y + 2)^2 = 25; center (3, -2), radius 5.",
                "explanation": "Group terms: x^2 - 6x and y^2 + 4y. Add 9 and 4 to complete squares, giving (x - 3)^2 + (y + 2)^2 = 25. The center is (3, -2), and the radius is 5.",
                "type": "Equation rewriting",
                "skill": "Complete the square to reveal circle features",
                "equation_battle": True,
                "visual": True,
                "distractors": "forgets one added constant; gives radius 25; reads center (-3, 2); leaves the equation in general form",
            },
            {
                "focus": "Finding parabola focus and directrix",
                "question": "For y = (1/8)(x - 2)^2 - 3, find the vertex, focus, and directrix.",
                "answer": "Vertex (2, -3), focus (2, -1), directrix y = -5.",
                "explanation": "Rewrite as (x - 2)^2 = 8(y + 3). Since 4p = 8, p = 2. The vertex is (2, -3), so the focus is 2 units above it at (2, -1), and the directrix is y = -5.",
                "type": "Feature identification",
                "skill": "Use p in vertical parabola form",
                "visual": True,
                "distractors": "sets p = 8; moves the focus horizontally; gives directrix y = -1; reads the vertex as (-2, 3)",
            },
            {
                "focus": "Writing a parabola from vertex and focus",
                "question": "Write the equation of the parabola with vertex (1, -2) and focus (1, 1).",
                "answer": "(x - 1)^2 = 12(y + 2).",
                "explanation": "The focus is 3 units above the vertex, so p = 3 and the parabola opens upward. The form is (x - h)^2 = 4p(y - k), giving (x - 1)^2 = 12(y + 2).",
                "type": "Construction",
                "skill": "Build a parabola equation from focus data",
                "visual": True,
                "distractors": "uses 3 instead of 12; opens the parabola left or right; writes y - 2 instead of y + 2; swaps x and y",
            },
            {
                "focus": "Reading ellipse vertices",
                "question": "Find the center, vertices, and covertices of (x - 1)^2/25 + (y + 2)^2/9 = 1.",
                "answer": "Center (1, -2); vertices (-4, -2) and (6, -2); covertices (1, -5) and (1, 1).",
                "explanation": "The larger denominator is 25 under the x-term, so the major axis is horizontal with a = 5. The center is (1, -2). Move 5 left and right for vertices and 3 up and down for covertices.",
                "type": "Feature identification",
                "skill": "Read horizontal ellipse features",
                "visual": True,
                "distractors": "uses a = 25; makes the major axis vertical; reads center (-1, 2); gives covertices with distance 9",
            },
            {
                "focus": "Reading hyperbola features",
                "question": "Find the center, vertices, and asymptotes of (y + 1)^2/16 - (x - 2)^2/9 = 1.",
                "answer": "Center (2, -1); vertices (2, 3) and (2, -5); asymptotes y + 1 = (4/3)(x - 2) and y + 1 = -(4/3)(x - 2).",
                "explanation": "The positive term is the y-term, so the hyperbola opens up and down. The center is (2, -1), a = 4, and b = 3. Move 4 units vertically for the vertices and use slopes 4/3 and -4/3 for the asymptotes.",
                "type": "Feature identification",
                "skill": "Read vertical hyperbola features",
                "visual": True,
                "distractors": "uses slopes 3/4 and -3/4; opens left and right; reads center (-2, 1); moves vertices horizontally",
            },
            {
                "focus": "Completing the square for an ellipse",
                "question": "Classify and rewrite 9x^2 + 4y^2 - 18x + 16y - 11 = 0 in standard form.",
                "answer": "(x - 1)^2/4 + (y + 2)^2/9 = 1; ellipse centered at (1, -2).",
                "explanation": "Complete the square: 9(x^2 - 2x) + 4(y^2 + 4y) = 11. This becomes 9(x - 1)^2 + 4(y + 2)^2 = 36, so standard form is (x - 1)^2/4 + (y + 2)^2/9 = 1.",
                "type": "Equation rewriting",
                "skill": "Complete the square to classify an ellipse",
                "equation_battle": True,
                "visual": True,
                "distractors": "divides by 36 before completing squares; calls it a circle; forgets to multiply square constants by 9 and 4; reads center (-1, 2)",
            },
            {
                "focus": "Finding ellipse eccentricity",
                "question": "Find the eccentricity of x^2/100 + y^2/64 = 1.",
                "answer": "3/5.",
                "explanation": "For this ellipse, a = 10 and b = 8. Since c^2 = a^2 - b^2 = 100 - 64 = 36, c = 6. The eccentricity is e = c/a = 6/10 = 3/5.",
                "type": "Feature calculation",
                "skill": "Compute ellipse eccentricity",
                "visual": True,
                "distractors": "uses c^2 = a^2 + b^2; gives 4/5; uses b/a; treats 100 as a",
            },
            {
                "focus": "Finding hyperbola foci",
                "question": "Find the foci of x^2/9 - y^2/16 = 1.",
                "answer": "(-5, 0) and (5, 0).",
                "explanation": "For a hyperbola, c^2 = a^2 + b^2. Here a^2 = 9 and b^2 = 16, so c^2 = 25 and c = 5. The transverse axis is horizontal, so the foci are (-5, 0) and (5, 0).",
                "type": "Feature calculation",
                "skill": "Compute hyperbola foci",
                "visual": True,
                "distractors": "uses c = sqrt(7); places foci on the y-axis; gives vertices instead of foci; swaps a and b without checking orientation",
            },
            {
                "focus": "Reading a horizontal parabola",
                "question": "For (y + 4)^2 = -12(x - 1), find the vertex, focus, and directrix.",
                "answer": "Vertex (1, -4), focus (-2, -4), directrix x = 4.",
                "explanation": "The form is (y - k)^2 = 4p(x - h). Here 4p = -12, so p = -3. Starting at vertex (1, -4), move 3 units left to the focus (-2, -4), and put the directrix 3 units right at x = 4.",
                "type": "Feature identification",
                "skill": "Use p in horizontal parabola form",
                "visual": True,
                "distractors": "moves the focus up or down; uses p = -12; gives directrix x = -2; reads vertex (-1, 4)",
            },
            {
                "focus": "Checking a point on a circle",
                "question": "Does the point (6, 1) lie on the circle (x - 2)^2 + (y + 2)^2 = 25?",
                "answer": "Yes, because it satisfies the equation.",
                "explanation": "Substitute (6, 1): (6 - 2)^2 + (1 + 2)^2 = 4^2 + 3^2 = 16 + 9 = 25. The point lies on the circle.",
                "type": "Verification",
                "skill": "Substitute a point into a conic equation",
                "visual": True,
                "distractors": "checks distance from the origin; forgets the center shift; computes 4^2 + 3^2 as 49; says every nearby point is on the circle",
            },
            {
                "focus": "Writing an ellipse from vertices",
                "question": "Write the equation of the ellipse centered at (0, 0) with vertices (0, -7) and (0, 7), and covertices (-2, 0) and (2, 0).",
                "answer": "x^2/4 + y^2/49 = 1.",
                "explanation": "The vertices are vertical and 7 units from the center, so a^2 = 49 under y^2. The covertices are 2 units from the center, so b^2 = 4 under x^2.",
                "type": "Construction",
                "skill": "Build an ellipse equation from graph features",
                "visual": True,
                "distractors": "places 49 under x^2; uses 7 and 2 instead of their squares; writes a hyperbola; shifts the center away from the origin",
            },
            {
                "focus": "Writing a hyperbola from vertices and asymptotes",
                "question": "Write the equation of the hyperbola with center (-1, 3), vertices (-1, 1) and (-1, 5), and asymptotes y - 3 = 2(x + 1) and y - 3 = -2(x + 1).",
                "answer": "(y - 3)^2/4 - (x + 1)^2 = 1.",
                "explanation": "The vertices are vertical and 2 units from the center, so a = 2. For a vertical hyperbola, asymptote slopes are a/b and -a/b. Since a/b = 2, b = 1. The equation is (y - 3)^2/4 - (x + 1)^2/1 = 1.",
                "type": "Construction",
                "skill": "Build a vertical hyperbola equation",
                "visual": True,
                "boss": True,
                "distractors": "uses a horizontal hyperbola; makes b = 2; misses the center shift; writes an ellipse because the vertices are symmetric",
            },
            {
                "focus": "Completing the square for a hyperbola",
                "question": "Rewrite 4x^2 - 9y^2 - 16x - 18y - 29 = 0 in standard form and give the asymptotes.",
                "answer": "(x - 2)^2/9 - (y + 1)^2/4 = 1; asymptotes y + 1 = (2/3)(x - 2) and y + 1 = -(2/3)(x - 2).",
                "explanation": "Complete the square: 4(x^2 - 4x) - 9(y^2 + 2y) = 29. This becomes 4(x - 2)^2 - 9(y + 1)^2 = 36, so standard form is (x - 2)^2/9 - (y + 1)^2/4 = 1. The hyperbola is horizontal with a = 3 and b = 2, so the asymptote slopes are 2/3 and -2/3.",
                "type": "Equation rewriting",
                "skill": "Complete the square to reveal hyperbola features",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "forgets to distribute -9 when completing the square; gives slopes 3/2 and -3/2; calls the graph an ellipse; reads center (-2, 1)",
            },
            {
                "focus": "Finding a missing ellipse parameter",
                "question": "The point (2, 3) lies on x^2/16 + y^2/k = 1. Find k.",
                "answer": "k = 12.",
                "explanation": "Substitute the point: 2^2/16 + 3^2/k = 1, so 1/4 + 9/k = 1. Then 9/k = 3/4, which gives k = 12.",
                "type": "Parameter solving",
                "skill": "Use a point to determine a conic parameter",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "sets k = 9; subtracts 1/4 incorrectly; uses x = 3 and y = 2; forgets that k is a denominator",
            },
            {
                "focus": "Intersecting a line and a circle",
                "question": "Find the intersection points of x^2 + y^2 = 25 and y = 3.",
                "answer": "(-4, 3) and (4, 3).",
                "explanation": "Substitute y = 3 into the circle: x^2 + 9 = 25, so x^2 = 16 and x = -4 or x = 4. The intersection points are (-4, 3) and (4, 3).",
                "type": "System solving",
                "skill": "Solve a line-circle intersection",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "returns only one point; uses y = -3; says x = 16; forgets to write ordered pairs",
            },
            {
                "focus": "Modeling a parabolic arch",
                "question": "A parabolic arch has vertex (0, 12) and passes through (-6, 0) and (6, 0). If its equation is y = ax^2 + 12, what is the height when x = 3?",
                "answer": "9 units.",
                "explanation": "Use point (6, 0): 0 = 36a + 12, so a = -1/3. Then at x = 3, y = (-1/3)(9) + 12 = 9.",
                "type": "Modeling",
                "skill": "Fit and evaluate a parabolic model",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "uses a = 1/3; substitutes x = 6 for the final height; gives 12 because it is the vertex height; forgets the negative opening",
            },
            {
                "focus": "Full ellipse analysis from general form",
                "question": "Rewrite 16x^2 + 25y^2 - 64x + 150y - 111 = 0 in standard form, then give the center, vertices, covertices, and foci.",
                "answer": "(x - 2)^2/25 + (y + 3)^2/16 = 1; center (2, -3); vertices (-3, -3) and (7, -3); covertices (2, -7) and (2, 1); foci (-1, -3) and (5, -3).",
                "explanation": "Complete the square to get 16(x - 2)^2 + 25(y + 3)^2 = 400, so standard form is (x - 2)^2/25 + (y + 3)^2/16 = 1. The major axis is horizontal with a = 5 and b = 4. Since c^2 = 25 - 16 = 9, c = 3, so the foci are 3 units left and right of the center.",
                "type": "Boss synthesis",
                "skill": "Analyze an ellipse from general form",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "misses the center shift; uses c^2 = 25 + 16; makes the major axis vertical; divides by 400 before completing squares",
            },
        ],
        "next_topic": "Vectors",
    },
    {
        "id": 56,
        "topic": "Vectors",
        "subtopic": "Vector components, magnitude, dot products, projections, and applications",
        "prerequisites": "coordinate plane, right triangle trigonometry, distance formula, basic algebra",
        "metadata_prereq": "coordinate_plane, right_triangle_trig, distance_formula, linear_equations",
        "metadata_misconceptions": "confuses_points_and_vectors, ignores_direction, treats_dot_product_as_vector, uses_degrees_without_context",
        "review": [
            "Subtract coordinates in the order terminal minus initial to form a displacement vector.",
            "Use the Pythagorean theorem to find lengths from horizontal and vertical components.",
            "Use sine and cosine to convert between magnitude-direction form and components.",
            "Remember that scalar multiplication changes length and may reverse direction.",
            "Interpret units carefully when vectors model velocity, force, or displacement.",
        ],
        "concepts": [
            "A vector represents magnitude and direction, not a fixed location.",
            "Component form lets vectors be added, subtracted, and scaled coordinate by coordinate.",
            "Magnitude measures vector length and comes from the distance formula.",
            "The dot product measures alignment and can detect perpendicular vectors.",
            "Projection gives the part of one vector that points in the direction of another.",
        ],
        "misconceptions": [
            "Subtracting coordinates in the wrong order when building a vector.",
            "Adding magnitudes instead of adding components.",
            "Treating a dot product as another vector instead of a scalar.",
            "Forgetting to divide by magnitude when creating a unit vector.",
            "Using the wrong angle reference when converting direction to components.",
        ],
        "exercises": [
            {
                "focus": "Building a vector from two points",
                "question": "Find the vector from A(2, -3) to B(7, 5).",
                "answer": "<5, 8>.",
                "explanation": "Subtract initial coordinates from terminal coordinates: <7 - 2, 5 - (-3)> = <5, 8>.",
                "type": "Component calculation",
                "skill": "Create a displacement vector",
                "visual": True,
                "distractors": "computes <2 - 7, -3 - 5>; gives the endpoint as the vector; subtracts only x-coordinates; reverses the signs",
            },
            {
                "focus": "Finding magnitude",
                "question": "Find the magnitude of <6, -8>.",
                "answer": "10.",
                "explanation": "The magnitude is sqrt(6^2 + (-8)^2) = sqrt(36 + 64) = sqrt(100) = 10.",
                "type": "Magnitude",
                "skill": "Use the vector length formula",
                "visual": True,
                "distractors": "adds 6 and -8; gives sqrt(28); forgets to square the negative component; gives 100",
            },
            {
                "focus": "Creating a unit vector",
                "question": "Find a unit vector in the direction of <3, 4>.",
                "answer": "<3/5, 4/5>.",
                "explanation": "The magnitude of <3, 4> is 5. Divide each component by 5 to get the unit vector <3/5, 4/5>.",
                "type": "Normalization",
                "skill": "Scale a vector to length 1",
                "visual": True,
                "distractors": "multiplies by 5; gives <4/5, 3/5>; divides by 25; gives magnitude 1 without a vector",
            },
            {
                "focus": "Adding vectors",
                "question": "Compute <2, -1> + <-5, 4>.",
                "answer": "<-3, 3>.",
                "explanation": "Add corresponding components: <2 + (-5), -1 + 4> = <-3, 3>.",
                "type": "Vector operation",
                "skill": "Add vectors by components",
                "visual": True,
                "distractors": "adds all four numbers into one scalar; subtracts components; gives <7, 5>; changes signs before adding",
            },
            {
                "focus": "Scalar multiplication",
                "question": "Compute -3<4, -2>.",
                "answer": "<-12, 6>.",
                "explanation": "Multiply each component by -3: <-12, 6>. The negative scalar reverses direction and triples the length.",
                "type": "Vector operation",
                "skill": "Multiply a vector by a scalar",
                "visual": True,
                "distractors": "multiplies only the first component; gives <12, -6>; adds -3 to each component; treats -3 as a magnitude only",
            },
            {
                "focus": "Combining displacement vectors",
                "question": "A player moves by <3, 2>, then <-1, 5>, then <4, -3>. What is the total displacement and its magnitude?",
                "answer": "Total displacement <6, 4>; magnitude 2sqrt(13).",
                "explanation": "Add components: <3 - 1 + 4, 2 + 5 - 3> = <6, 4>. Its magnitude is sqrt(6^2 + 4^2) = sqrt(52) = 2sqrt(13).",
                "type": "Modeling",
                "skill": "Add multiple displacement vectors",
                "visual": True,
                "distractors": "adds magnitudes of each move; ignores the negative components; gives <8, 10>; simplifies sqrt(52) as 26",
            },
            {
                "focus": "Computing a dot product",
                "question": "Compute <2, 5> dot <-3, 4>.",
                "answer": "14.",
                "explanation": "Multiply corresponding components and add: 2(-3) + 5(4) = -6 + 20 = 14.",
                "type": "Dot product",
                "skill": "Calculate a scalar dot product",
                "visual": False,
                "distractors": "returns <-6, 20>; adds components first; multiplies 2 by 4 and 5 by -3; gives -26",
            },
            {
                "focus": "Testing perpendicular vectors",
                "question": "Are <4, -2> and <1, 2> perpendicular?",
                "answer": "Yes, their dot product is 0.",
                "explanation": "The dot product is 4(1) + (-2)(2) = 4 - 4 = 0. A zero dot product means the nonzero vectors are perpendicular.",
                "type": "Dot product reasoning",
                "skill": "Use the dot product to detect perpendicularity",
                "visual": True,
                "distractors": "compares magnitudes only; says no because components are not opposites; multiplies components without adding; ignores the negative sign",
            },
            {
                "focus": "Finding the angle between vectors",
                "question": "Find the angle between <1, 0> and <1, sqrt(3)>.",
                "answer": "60 degrees.",
                "explanation": "The dot product is 1, and the magnitudes are 1 and 2. Thus cos(theta) = 1/(1)(2) = 1/2, so theta = 60 degrees.",
                "type": "Angle calculation",
                "skill": "Use dot product angle formula",
                "visual": True,
                "distractors": "uses sine instead of cosine; gives 30 degrees; forgets the magnitude 2; reports the dot product as the angle",
            },
            {
                "focus": "Projecting onto a horizontal vector",
                "question": "Find the projection of <6, 2> onto <3, 0>.",
                "answer": "<6, 0>.",
                "explanation": "Projection onto b is ((a dot b)/(b dot b))b. Here a dot b = 18 and b dot b = 9, so the multiplier is 2. The projection is 2<3, 0> = <6, 0>.",
                "type": "Projection",
                "skill": "Compute a vector projection",
                "visual": True,
                "distractors": "drops the vector direction and gives 6; projects onto the y-axis; divides by |b| instead of b dot b; gives <3, 0>",
            },
            {
                "focus": "Computing work with vectors",
                "question": "A force <10, 4> newtons moves an object by displacement <3, 2> meters. Find the work done.",
                "answer": "38 joules.",
                "explanation": "Work is force dot displacement: 10(3) + 4(2) = 30 + 8 = 38 joules.",
                "type": "Modeling",
                "skill": "Use a dot product in a work context",
                "visual": True,
                "distractors": "multiplies magnitudes without angle; returns a vector; adds all components; forgets units",
            },
            {
                "focus": "Converting direction to components",
                "question": "Write a vector of magnitude 8 at an angle of 30 degrees from the positive x-axis in component form.",
                "answer": "<4sqrt(3), 4>.",
                "explanation": "Use <r cos theta, r sin theta>. With r = 8 and theta = 30 degrees, the vector is <8(sqrt(3)/2), 8(1/2)> = <4sqrt(3), 4>.",
                "type": "Trigonometric conversion",
                "skill": "Convert polar-style vector data to components",
                "visual": True,
                "distractors": "swaps sine and cosine; uses 30 as a component; gives <4, 4sqrt(3)>; forgets to multiply by 8",
            },
            {
                "focus": "Finding direction angle",
                "question": "Find the magnitude and direction angle of <-3, 3> measured from the positive x-axis.",
                "answer": "Magnitude 3sqrt(2), direction 135 degrees.",
                "explanation": "The magnitude is sqrt((-3)^2 + 3^2) = sqrt(18) = 3sqrt(2). The vector is in quadrant II with reference angle 45 degrees, so the direction is 135 degrees.",
                "type": "Trigonometric conversion",
                "skill": "Convert components to magnitude and direction",
                "visual": True,
                "distractors": "gives 45 degrees; gives 315 degrees; misses the quadrant; gives magnitude sqrt(6)",
            },
            {
                "focus": "Solving a vector equation",
                "question": "Find x and y if <x, 4> + <3, y> = <8, -2>.",
                "answer": "x = 5 and y = -6.",
                "explanation": "Match components: x + 3 = 8, so x = 5. Also 4 + y = -2, so y = -6.",
                "type": "Equation solving",
                "skill": "Solve component equations",
                "equation_battle": True,
                "distractors": "sets x = 8 and y = -2; subtracts in the wrong direction; solves only one component; treats the equation as a dot product",
            },
            {
                "focus": "Combining scalar multiples",
                "question": "Compute 2<1, 3> - <4, -2>.",
                "answer": "<-2, 8>.",
                "explanation": "First multiply: 2<1, 3> = <2, 6>. Then subtract: <2, 6> - <4, -2> = <-2, 8>.",
                "type": "Vector operation",
                "skill": "Use scalar multiplication and subtraction together",
                "visual": True,
                "boss": True,
                "distractors": "subtracts before multiplying; treats -<4, -2> as <-4, -2>; gives <6, 4>; makes an arithmetic sign error",
            },
            {
                "focus": "Finding 3D magnitude",
                "question": "Find the magnitude of <2, -3, 6>.",
                "answer": "7.",
                "explanation": "Use the 3D magnitude formula: sqrt(2^2 + (-3)^2 + 6^2) = sqrt(4 + 9 + 36) = sqrt(49) = 7.",
                "type": "Magnitude",
                "skill": "Use vector length in three dimensions",
                "visual": False,
                "boss": True,
                "distractors": "uses only two components; gives 49; adds components; forgets to square -3",
            },
            {
                "focus": "Computing a 3D dot product",
                "question": "Compute <1, 2, -2> dot <3, 0, 4>.",
                "answer": "-5.",
                "explanation": "Multiply and add corresponding components: 1(3) + 2(0) + (-2)(4) = 3 + 0 - 8 = -5.",
                "type": "Dot product",
                "skill": "Calculate dot products in three dimensions",
                "visual": False,
                "boss": True,
                "distractors": "drops the zero component but also drops the last term; returns <3, 0, -8>; gives 11; uses absolute values",
            },
            {
                "focus": "Finding a parameter for perpendicularity",
                "question": "Find k so that <2, k> is perpendicular to <-3, 4>.",
                "answer": "k = 3/2.",
                "explanation": "Perpendicular vectors have dot product 0. So 2(-3) + k(4) = 0, which gives -6 + 4k = 0 and k = 3/2.",
                "type": "Parameter solving",
                "skill": "Use dot product conditions",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "sets components equal; uses 2(-3) - 4k = 0; gives k = -3/2; solves for k from equal magnitudes",
            },
            {
                "focus": "Modeling velocity with current",
                "question": "A boat's still-water velocity is <8, 0> miles per hour and the current is <0, 3> miles per hour. Find the resultant velocity and speed.",
                "answer": "Resultant velocity <8, 3>; speed sqrt(73) miles per hour.",
                "explanation": "Add the velocity vectors to get <8, 3>. The speed is the magnitude: sqrt(8^2 + 3^2) = sqrt(73) miles per hour.",
                "type": "Modeling",
                "skill": "Combine velocity vectors and interpret magnitude",
                "visual": True,
                "boss": True,
                "distractors": "adds speeds to get 11; subtracts the current; gives direction only; forgets that speed is magnitude",
            },
            {
                "focus": "Using vectors for triangle area and angle",
                "question": "For A(1, 2), B(5, 5), and C(2, 9), find the area of triangle ABC and the angle at A.",
                "answer": "Area 25/2 square units; angle at A is 45 degrees.",
                "explanation": "Use vectors AB = <4, 3> and AC = <1, 7>. The area is (1/2)|4(7) - 3(1)| = 25/2. The dot product is 25, with magnitudes 5 and 5sqrt(2), so cos(theta) = 1/sqrt(2), giving theta = 45 degrees.",
                "type": "Boss synthesis",
                "skill": "Use determinants and dot products together",
                "visual": True,
                "boss": True,
                "distractors": "uses full parallelogram area; computes BA instead of AB and changes only one vector; gives 90 degrees from a zero-dot assumption; drops the one-half factor",
            },
        ],
        "next_topic": "Complex numbers",
    },
    {
        "id": 57,
        "topic": "Complex numbers",
        "subtopic": "Operations, conjugates, quadratic roots, modulus, and polar form",
        "prerequisites": "integer arithmetic, radicals, quadratic formula, trigonometric exact values",
        "metadata_prereq": "integer_arithmetic, radicals, quadratic_formula, exact_trig_values",
        "metadata_misconceptions": "forgets_i_squared_is_negative_one, mishandles_conjugates, drops_complex_restrictions, mixes_polar_angle_and_radius",
        "review": [
            "Use i^2 = -1 whenever powers or products of i appear.",
            "Combine real parts with real parts and imaginary parts with imaginary parts.",
            "Use the quadratic formula when real factoring no longer works.",
            "Use the Pythagorean theorem to find modulus in the complex plane.",
            "Use exact trig values to convert between rectangular and polar forms.",
        ],
        "concepts": [
            "A complex number a + bi has real part a and imaginary part b.",
            "The conjugate a - bi helps divide complex numbers and creates real products.",
            "Complex roots naturally appear when a quadratic has a negative discriminant.",
            "The modulus of a + bi is its distance from the origin in the complex plane.",
            "Polar form uses radius and angle, so multiplication scales radii and adds angles.",
        ],
        "misconceptions": [
            "Treating i^2 as positive 1 instead of negative 1.",
            "Combining real and imaginary terms as if they were like terms.",
            "Dividing complex numbers without multiplying by the conjugate.",
            "Forgetting that polar angles need the correct quadrant.",
            "Keeping both plus and minus roots when a context requires a positive real input.",
        ],
        "exercises": [
            {
                "focus": "Simplifying powers of i",
                "question": "Simplify i^37.",
                "answer": "i.",
                "explanation": "Powers of i cycle every 4: i, -1, -i, 1. Since 37 leaves remainder 1 when divided by 4, i^37 = i.",
                "type": "Simplification",
                "skill": "Use the cycle of powers of i",
                "distractors": "gives 1 from rounding to 36; gives -i; treats i as a variable power; says i^37 is real",
            },
            {
                "focus": "Adding complex numbers",
                "question": "Compute (3 + 2i) + (5 - 7i).",
                "answer": "8 - 5i.",
                "explanation": "Add real parts and imaginary parts separately: 3 + 5 = 8 and 2i - 7i = -5i.",
                "type": "Complex operation",
                "skill": "Add complex numbers",
                "distractors": "adds all coefficients into 3i; gives 8 + 9i; subtracts imaginary parts in the wrong order; multiplies instead of adding",
            },
            {
                "focus": "Subtracting complex numbers",
                "question": "Compute (4 - 3i) - (1 + 6i).",
                "answer": "3 - 9i.",
                "explanation": "Distribute the subtraction: 4 - 3i - 1 - 6i = 3 - 9i.",
                "type": "Complex operation",
                "skill": "Subtract complex numbers carefully",
                "distractors": "forgets to distribute the negative; gives 3 + 3i; subtracts real parts only; changes -3i to +3i",
            },
            {
                "focus": "Multiplying complex numbers",
                "question": "Compute (2 + 3i)(4 - i).",
                "answer": "11 + 10i.",
                "explanation": "Multiply: 8 - 2i + 12i - 3i^2. Since i^2 = -1, -3i^2 = 3, so the result is 11 + 10i.",
                "type": "Complex operation",
                "skill": "Multiply binomial complex numbers",
                "equation_battle": True,
                "distractors": "treats i^2 as 1; gives 5 + 10i; forgets the outer terms; combines 8 and -3i^2 incorrectly",
            },
            {
                "focus": "Using conjugate products",
                "question": "Compute (5 + 2i)(5 - 2i).",
                "answer": "29.",
                "explanation": "Conjugates multiply to a real number: 5^2 + 2^2 = 25 + 4 = 29.",
                "type": "Complex operation",
                "skill": "Multiply conjugates",
                "distractors": "gives 21 from 25 - 4; leaves imaginary terms; gives 25 - 4i; treats the product as another conjugate pair",
            },
            {
                "focus": "Dividing complex numbers",
                "question": "Write (7 + 5i)/(2 - i) in a + bi form.",
                "answer": "9/5 + (17/5)i.",
                "explanation": "Multiply numerator and denominator by 2 + i. The numerator becomes 9 + 17i, and the denominator becomes 5, so the quotient is 9/5 + (17/5)i.",
                "type": "Complex operation",
                "skill": "Use conjugates to divide complex numbers",
                "equation_battle": True,
                "distractors": "uses 2 - i again instead of the conjugate; divides real and imaginary parts separately; leaves i in the denominator; gets denominator 3",
            },
            {
                "focus": "Solving a pure imaginary quadratic",
                "question": "Solve x^2 + 16 = 0.",
                "answer": "x = 4i or x = -4i.",
                "explanation": "The equation gives x^2 = -16. Since sqrt(-16) = 4i, the solutions are 4i and -4i.",
                "type": "Equation solving",
                "skill": "Find imaginary square roots",
                "equation_battle": True,
                "distractors": "gives only 4i; gives x = 4 and x = -4; says there is no complex solution; writes x = 16i",
            },
            {
                "focus": "Using the quadratic formula with complex roots",
                "question": "Solve x^2 - 6x + 13 = 0.",
                "answer": "x = 3 + 2i or x = 3 - 2i.",
                "explanation": "The discriminant is (-6)^2 - 4(1)(13) = -16. The quadratic formula gives (6 plus-or-minus 4i)/2, which is 3 plus-or-minus 2i.",
                "type": "Equation solving",
                "skill": "Use the quadratic formula for complex roots",
                "equation_battle": True,
                "distractors": "drops the imaginary unit; gives 6 plus-or-minus 4i; says no roots; uses discriminant 16",
            },
            {
                "focus": "Finding modulus",
                "question": "Find the modulus of -3 + 4i.",
                "answer": "5.",
                "explanation": "The modulus is sqrt((-3)^2 + 4^2) = sqrt(9 + 16) = 5.",
                "type": "Complex plane",
                "skill": "Compute distance from the origin",
                "visual": True,
                "distractors": "adds -3 and 4; gives sqrt(7); gives -5; treats modulus as the imaginary part",
            },
            {
                "focus": "Finding a conjugate and product",
                "question": "For z = 1 - 6i, find the conjugate of z and z times its conjugate.",
                "answer": "Conjugate 1 + 6i; product 37.",
                "explanation": "The conjugate changes the sign of the imaginary part. The product is 1^2 + 6^2 = 37.",
                "type": "Complex operation",
                "skill": "Use conjugates to create real products",
                "distractors": "changes the real sign; gives product 35; leaves product complex; changes both signs",
            },
            {
                "focus": "Interpreting the complex plane",
                "question": "In which quadrant is the complex number 2 - 5i located?",
                "answer": "Quadrant IV.",
                "explanation": "The real part 2 is positive, so the point is to the right. The imaginary part -5 is negative, so the point is below the real axis. That is Quadrant IV.",
                "type": "Graph interpretation",
                "skill": "Locate a complex number on the plane",
                "visual": True,
                "distractors": "uses Quadrant II from the negative imaginary part; swaps real and imaginary axes; says Quadrant I because 2 is positive; calls it an axis point",
            },
            {
                "focus": "Writing rectangular form in polar form",
                "question": "Write 1 + sqrt(3)i in polar form using degrees.",
                "answer": "2(cos 60 deg + i sin 60 deg).",
                "explanation": "The modulus is sqrt(1^2 + (sqrt(3))^2) = 2. The point is in Quadrant I and tan(theta) = sqrt(3), so theta = 60 degrees.",
                "type": "Polar conversion",
                "skill": "Convert rectangular complex form to polar form",
                "visual": True,
                "distractors": "uses radius 4; gives 30 degrees; places the angle in Quadrant II; swaps sine and cosine",
            },
            {
                "focus": "Converting polar form to rectangular form",
                "question": "Convert 4(cos 210 deg + i sin 210 deg) to a + bi form.",
                "answer": "-2sqrt(3) - 2i.",
                "explanation": "cos 210 deg = -sqrt(3)/2 and sin 210 deg = -1/2. Multiplying both by 4 gives -2sqrt(3) - 2i.",
                "type": "Polar conversion",
                "skill": "Use exact trig values in polar conversion",
                "visual": True,
                "distractors": "uses positive signs from a 30-degree reference angle; forgets to multiply by 4; gives -2 - 2sqrt(3)i; uses 210 as a component",
            },
            {
                "focus": "Multiplying in polar form",
                "question": "Multiply 3(cos 40 deg + i sin 40 deg) by 2(cos 80 deg + i sin 80 deg).",
                "answer": "6(cos 120 deg + i sin 120 deg).",
                "explanation": "When multiplying in polar form, multiply the moduli and add the angles. The result is 3 times 2 = 6 with angle 40 + 80 = 120 degrees.",
                "type": "Polar operation",
                "skill": "Multiply complex numbers in polar form",
                "distractors": "adds radii; multiplies angles; subtracts angles; converts only one factor",
            },
            {
                "focus": "Dividing in polar form",
                "question": "Divide 10(cos 150 deg + i sin 150 deg) by 2(cos 30 deg + i sin 30 deg).",
                "answer": "5(cos 120 deg + i sin 120 deg).",
                "explanation": "When dividing in polar form, divide the moduli and subtract the angles. The result has modulus 10/2 = 5 and angle 150 - 30 = 120 degrees.",
                "type": "Polar operation",
                "skill": "Divide complex numbers in polar form",
                "distractors": "multiplies the moduli; adds the angles; subtracts in the wrong order; divides angles",
                "boss": True,
            },
            {
                "focus": "Using De Moivre's theorem",
                "question": "Compute (sqrt(3) + i)^4 in a + bi form.",
                "answer": "-8 + 8sqrt(3)i.",
                "explanation": "sqrt(3) + i has modulus 2 and angle 30 degrees. Raising to the fourth power gives 2^4 with angle 120 degrees, so the result is 16(cos 120 deg + i sin 120 deg) = -8 + 8sqrt(3)i.",
                "type": "Polar power",
                "skill": "Apply De Moivre's theorem",
                "equation_battle": True,
                "boss": True,
                "distractors": "raises only the angle; uses 30 degrees after raising; gives 16 as the whole answer; treats sqrt(3) + i as radius sqrt(3)",
            },
            {
                "focus": "Finding square roots of a negative number",
                "question": "Solve z^2 = -9.",
                "answer": "z = 3i or z = -3i.",
                "explanation": "The square roots of -9 are the numbers whose square is -9. Since (3i)^2 = -9 and (-3i)^2 = -9, both are solutions.",
                "type": "Equation solving",
                "skill": "Find complex square roots",
                "equation_battle": True,
                "boss": True,
                "distractors": "gives z = 9i; gives only one root; gives real roots 3 and -3; says no complex roots",
            },
            {
                "focus": "Matching real and imaginary parts",
                "question": "Find a and b if (a + 2i) + (3 + bi) = 7 - 5i.",
                "answer": "a = 4 and b = -7.",
                "explanation": "Combine parts: (a + 3) + (2 + b)i = 7 - 5i. Match real parts to get a + 3 = 7, so a = 4. Match imaginary parts to get 2 + b = -5, so b = -7.",
                "type": "Parameter solving",
                "skill": "Equate real and imaginary components",
                "equation_battle": True,
                "boss": True,
                "distractors": "sets a = 7 and b = -5; mixes real and imaginary equations; gives b = 7; ignores the existing 2i",
            },
            {
                "focus": "Finding a reciprocal",
                "question": "Write 1/(3 - 4i) in a + bi form.",
                "answer": "3/25 + (4/25)i.",
                "explanation": "Multiply by the conjugate 3 + 4i. The numerator becomes 3 + 4i and the denominator is 3^2 + 4^2 = 25, giving 3/25 + (4/25)i.",
                "type": "Complex operation",
                "skill": "Use conjugates to rationalize a complex denominator",
                "equation_battle": True,
                "boss": True,
                "distractors": "uses 3 - 4i as the conjugate; gives denominator 7; changes the sign of the real part; leaves i in the denominator",
            },
            {
                "focus": "Solving a factored complex quadratic",
                "question": "Solve z^2 - 5z + 7 + i = 0.",
                "answer": "z = 2 + i or z = 3 - i.",
                "explanation": "The expression factors as (z - (2 + i))(z - (3 - i)) because the roots add to 5 and multiply to 7 + i. Therefore the solutions are 2 + i and 3 - i.",
                "type": "Boss synthesis",
                "skill": "Solve a quadratic with complex roots by structure",
                "equation_battle": True,
                "boss": True,
                "distractors": "treats i as a variable coefficient; drops the imaginary part of the constant; gives 2 - i and 3 + i; assumes all roots must be conjugates",
            },
        ],
        "next_topic": "Mixed review",
    },
    {
        "id": 58,
        "topic": "Mixed review",
        "subtopic": "Integrated review across algebra, functions, trigonometry, sequences, conics, vectors, and complex numbers",
        "prerequisites": "linear equations, functions, quadratics, rational expressions, exponentials, logarithms, trigonometry, sequences, conics, vectors, complex numbers",
        "metadata_prereq": "linear_equations, functions, quadratics, rational_expressions, exponentials, logarithms, trigonometry, sequences, conics, vectors, complex_numbers",
        "metadata_misconceptions": "chooses_procedure_by_surface_feature, ignores_domain, drops_units, mixes_exact_and_decimal_forms",
        "review": [
            "Name the topic family before choosing a method.",
            "Check restrictions before and after solving equations.",
            "Use exact values when the question is built from exact trig or radical data.",
            "Translate between symbolic, graphical, numerical, and verbal representations.",
            "Write final answers in the form requested by the problem.",
        ],
        "concepts": [
            "Mixed review rewards method selection before computation.",
            "A correct answer includes restrictions, units, or intervals when the context needs them.",
            "Earlier algebra skills support later function, trigonometric, and modeling tasks.",
            "Graph features often come from rewriting an equation into a more revealing form.",
            "Boss readiness means explaining why a method applies, not only getting a number.",
        ],
        "misconceptions": [
            "Solving every problem with the most recent topic instead of the visible structure.",
            "Forgetting domain restrictions after algebraic simplification.",
            "Using decimal approximations when exact values are cleaner and requested.",
            "Stopping after a setup without answering the question asked.",
            "Treating a representation change as a different problem instead of the same relationship.",
        ],
        "exercises": [
            {
                "focus": "Solving a linear equation",
                "question": "Solve 3(2x - 1) = 15.",
                "answer": "x = 3.",
                "explanation": "Distribute to get 6x - 3 = 15. Add 3 to both sides: 6x = 18. Divide by 6 to get x = 3.",
                "type": "Review",
                "skill": "Solve a multi-step linear equation",
                "equation_battle": True,
                "distractors": "forgets to distribute; divides by 3 too early; gives x = 2; stops at 6x = 18",
            },
            {
                "focus": "Solving an absolute value inequality",
                "question": "Solve |x - 4| < 7.",
                "answer": "-3 < x < 11.",
                "explanation": "The inequality |x - 4| < 7 means -7 < x - 4 < 7. Add 4 to all three parts to get -3 < x < 11.",
                "type": "Review",
                "skill": "Translate absolute value distance into a compound inequality",
                "visual": True,
                "distractors": "uses x < -3 or x > 11; forgets to add 4 to one side; gives x = 11 only; reverses signs without reason",
            },
            {
                "focus": "Solving a system",
                "question": "Solve the system y = 2x + 1 and x + y = 10.",
                "answer": "(3, 7).",
                "explanation": "Substitute y = 2x + 1 into x + y = 10 to get x + 2x + 1 = 10. Then 3x = 9, so x = 3 and y = 7.",
                "type": "Review",
                "skill": "Use substitution to solve a linear system",
                "equation_battle": True,
                "visual": True,
                "distractors": "adds equations without aligning variables; gives x = 7 and y = 3; forgets to substitute back; solves only for x",
            },
            {
                "focus": "Evaluating a composition",
                "question": "If f(x) = x^2 + 1 and g(x) = 3x - 2, find f(g(2)).",
                "answer": "17.",
                "explanation": "First find g(2) = 3(2) - 2 = 4. Then f(4) = 4^2 + 1 = 17.",
                "type": "Review",
                "skill": "Evaluate a function composition in order",
                "distractors": "computes g(f(2)); adds the formulas; uses g(2) = 8; forgets to square 4",
            },
            {
                "focus": "Finding domain from a formula",
                "question": "Find the domain of h(x) = sqrt(x - 5)/(x - 2).",
                "answer": "[5, infinity).",
                "explanation": "The square root requires x - 5 >= 0, so x >= 5. The denominator cannot be 0, but x = 2 is already outside x >= 5. The domain is [5, infinity).",
                "type": "Review",
                "skill": "Combine radical and denominator restrictions",
                "visual": True,
                "distractors": "removes x = 2 as an extra hole inside the interval; uses x > 5; ignores the square root; gives all real numbers",
            },
            {
                "focus": "Finding an inverse function",
                "question": "Find the inverse of f(x) = 2x - 7.",
                "answer": "f^-1(x) = (x + 7)/2.",
                "explanation": "Let y = 2x - 7. Swap x and y to get x = 2y - 7. Solve for y: x + 7 = 2y, so y = (x + 7)/2.",
                "type": "Review",
                "skill": "Reverse a linear function",
                "equation_battle": True,
                "distractors": "writes (x - 7)/2; forgets to swap x and y; gives 2x + 7; solves for x and stops",
            },
            {
                "focus": "Factoring a quadratic",
                "question": "Factor x^2 - 9x + 20.",
                "answer": "(x - 4)(x - 5).",
                "explanation": "Find two numbers that multiply to 20 and add to -9. The numbers are -4 and -5, so the factorization is (x - 4)(x - 5).",
                "type": "Review",
                "skill": "Factor a monic quadratic",
                "distractors": "uses positive 4 and 5; gives (x - 2)(x - 10); finds numbers that add to 20; stops at the roots only",
            },
            {
                "focus": "Solving a quadratic with complex roots",
                "question": "Solve x^2 + 2x + 5 = 0.",
                "answer": "x = -1 + 2i or x = -1 - 2i.",
                "explanation": "The discriminant is 2^2 - 4(1)(5) = -16. The quadratic formula gives (-2 plus-or-minus 4i)/2, so x = -1 plus-or-minus 2i.",
                "type": "Review",
                "skill": "Use the quadratic formula with a negative discriminant",
                "equation_battle": True,
                "distractors": "drops i; says no roots; divides only -2 by 2; gives -2 plus-or-minus 4i",
            },
            {
                "focus": "Reading polynomial end behavior",
                "question": "Describe the end behavior of p(x) = -2x^5 + 3x^2.",
                "answer": "As x goes to infinity, p(x) goes to -infinity; as x goes to -infinity, p(x) goes to infinity.",
                "explanation": "The leading term -2x^5 controls end behavior. An odd degree with negative leading coefficient rises left and falls right.",
                "type": "Review",
                "skill": "Use leading term behavior",
                "visual": True,
                "distractors": "uses the 3x^2 term; says both ends rise; says both ends fall; ignores the negative leading coefficient",
            },
            {
                "focus": "Using the remainder theorem",
                "question": "Find the remainder when f(x) = x^3 - 4x + 1 is divided by x - 2.",
                "answer": "1.",
                "explanation": "By the remainder theorem, the remainder is f(2). Compute f(2) = 8 - 8 + 1 = 1.",
                "type": "Review",
                "skill": "Evaluate a polynomial for a division remainder",
                "distractors": "uses f(-2); performs long division but drops the constant; gives x = 2; says the remainder is 0 because x - 2 is a factor",
            },
            {
                "focus": "Finding rational asymptotes",
                "question": "Find the vertical asymptote and slant asymptote of y = (2x^2 + 1)/(x - 3).",
                "answer": "Vertical asymptote x = 3; slant asymptote y = 2x + 6.",
                "explanation": "The denominator is zero at x = 3, and the numerator is not zero there, so x = 3 is a vertical asymptote. Dividing 2x^2 + 1 by x - 3 gives quotient 2x + 6 with remainder 19, so the slant asymptote is y = 2x + 6.",
                "type": "Review",
                "skill": "Read vertical and slant asymptotes",
                "visual": True,
                "distractors": "uses x = -3; gives horizontal asymptote y = 2; ignores the remainder but also changes the quotient; factors a nonexistent common factor",
            },
            {
                "focus": "Evaluating exponential growth",
                "question": "An investment of 500 dollars grows by 6 percent per year for 3 years. Find its value to the nearest cent.",
                "answer": "$595.51.",
                "explanation": "Use 500(1.06)^3 = 595.508. Rounded to the nearest cent, the value is $595.51.",
                "type": "Review",
                "skill": "Use an exponential growth model",
                "distractors": "uses 0.06 as the whole base; uses simple interest only; rounds to 595.50; compounds for 2 years",
            },
            {
                "focus": "Evaluating a logarithm",
                "question": "Evaluate log_3(81).",
                "answer": "4.",
                "explanation": "The question asks for the exponent on 3 that gives 81. Since 3^4 = 81, log_3(81) = 4.",
                "type": "Review",
                "skill": "Use the definition of logarithm",
                "distractors": "gives 27; uses base 10; writes 3^81; says 1/4",
            },
            {
                "focus": "Solving a logarithmic equation",
                "question": "Solve log_2(x - 1) = 5.",
                "answer": "x = 33.",
                "explanation": "Rewrite in exponential form: x - 1 = 2^5 = 32. Therefore x = 33, which keeps x - 1 positive.",
                "type": "Review",
                "skill": "Convert logarithmic form to exponential form",
                "equation_battle": True,
                "distractors": "sets x - 1 = 10; gives x = 32; ignores the argument restriction; uses 5^2",
            },
            {
                "focus": "Using an exact trig value",
                "question": "Find sin(5pi/6).",
                "answer": "1/2.",
                "explanation": "5pi/6 is in Quadrant II with reference angle pi/6. Sine is positive in Quadrant II, and sin(pi/6) = 1/2.",
                "type": "Review",
                "skill": "Use reference angles on the unit circle",
                "visual": True,
                "distractors": "gives -1/2; uses cosine; gives sqrt(3)/2; places the angle in Quadrant III",
            },
            {
                "focus": "Solving a trigonometric equation",
                "question": "Solve 2cos x = 1 on 0 <= x < 2pi.",
                "answer": "x = pi/3 or x = 5pi/3.",
                "explanation": "Divide by 2 to get cos x = 1/2. Cosine is positive in Quadrants I and IV, so the solutions on the interval are pi/3 and 5pi/3.",
                "type": "Review",
                "skill": "Solve a basic trig equation on an interval",
                "visual": True,
                "equation_battle": True,
                "boss": True,
                "distractors": "returns only pi/3; uses sine solutions; includes 2pi/3; ignores the interval",
            },
            {
                "focus": "Using the law of cosines",
                "question": "Two sides of a triangle are 5 and 7 with included angle 60 degrees. Find the opposite side.",
                "answer": "sqrt(39).",
                "explanation": "By the law of cosines, c^2 = 5^2 + 7^2 - 2(5)(7)cos 60 deg = 25 + 49 - 35 = 39. Thus c = sqrt(39).",
                "type": "Review",
                "skill": "Apply the law of cosines",
                "visual": True,
                "boss": True,
                "distractors": "uses the law of sines; forgets the 2ab factor; uses cos 60 deg = 1; gives 39 as the side length",
            },
            {
                "focus": "Finding an arithmetic series sum",
                "question": "Find the sum of the first 10 terms of the arithmetic sequence with first term 4 and common difference 3.",
                "answer": "175.",
                "explanation": "Use S_n = n/2(2a_1 + (n - 1)d). Then S_10 = 10/2(2(4) + 9(3)) = 5(8 + 27) = 175.",
                "type": "Review",
                "skill": "Use the arithmetic series formula",
                "equation_battle": True,
                "boss": True,
                "distractors": "finds only the tenth term; uses geometric series formula; uses n - 1 as 10; gives 35",
            },
            {
                "focus": "Connecting vectors and complex numbers",
                "question": "Add vectors <2, -5> and <4, 1>, then treat the result <a, b> as the complex number a + bi. What is its modulus?",
                "answer": "2sqrt(13).",
                "explanation": "The vector sum is <6, -4>, so the complex number is 6 - 4i. Its modulus is sqrt(6^2 + (-4)^2) = sqrt(52) = 2sqrt(13).",
                "type": "Mixed representation",
                "skill": "Transfer component reasoning to complex modulus",
                "visual": True,
                "boss": True,
                "distractors": "uses <6, 4>; adds magnitudes; gives sqrt(10); treats the modulus as 6 - 4i",
            },
            {
                "focus": "Completing the square and solving a quadratic",
                "question": "For f(x) = x^2 - 4x + 1, write vertex form and solve f(x) = 0.",
                "answer": "f(x) = (x - 2)^2 - 3; zeros x = 2 + sqrt(3) and x = 2 - sqrt(3).",
                "explanation": "Complete the square: x^2 - 4x + 1 = (x - 2)^2 - 4 + 1 = (x - 2)^2 - 3. Setting this equal to 0 gives (x - 2)^2 = 3, so x = 2 plus-or-minus sqrt(3).",
                "type": "Boss synthesis",
                "skill": "Use vertex form to solve a quadratic exactly",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "writes (x + 2)^2 - 3; gives zeros plus-or-minus sqrt(3); stops at vertex form; uses decimal approximations without exact answers",
            },
        ],
        "next_topic": "Final boss challenges",
    },
    {
        "id": 59,
        "topic": "Final boss challenges",
        "subtopic": "Capstone synthesis across the full Precalculus Odyssey pathway",
        "prerequisites": "all previous Precalculus Odyssey phases",
        "metadata_prereq": "linear_equations, functions, quadratics, polynomials, rationals, exponentials, logarithms, trigonometry, sequences, series, conics, vectors, complex_numbers",
        "metadata_misconceptions": "starts_without_planning, ignores_restrictions, mixes_representations_carelessly, stops_before_interpretation",
        "review": [
            "Read the full prompt and identify the topic families involved before solving.",
            "List restrictions and units before finalizing an answer.",
            "Choose exact, decimal, graphical, or contextual form based on the question.",
            "Check solutions in the original relationship when squaring, logging, or simplifying rational expressions.",
            "Explain the final result in one sentence so the answer has meaning.",
        ],
        "concepts": [
            "A final boss problem combines skills but still breaks into legal smaller moves.",
            "Representation changes are tools: equations, graphs, vectors, and complex numbers can describe the same structure.",
            "Restrictions protect the solution from extraneous answers and impossible inputs.",
            "Modeling problems require a numeric result and an interpretation in context.",
            "Mastery means selecting methods flexibly and checking the result against the original prompt.",
        ],
        "misconceptions": [
            "Trying to apply one memorized procedure to every part of a multi-stage task.",
            "Forgetting that a simplified rational expression still carries original restrictions.",
            "Keeping extraneous roots after squaring an equation.",
            "Using a graph feature without connecting it to the equation that created it.",
            "Reporting intermediate values as final answers without context.",
        ],
        "exercises": [
            {
                "focus": "Linear modeling boss",
                "question": "A game pass costs 12 dollars plus 4 dollars per quest. If the total cost is 36 dollars, how many quests were purchased?",
                "answer": "6 quests.",
                "explanation": "Set up 12 + 4q = 36. Subtract 12 to get 4q = 24, then divide by 4 to get q = 6.",
                "type": "Boss modeling",
                "skill": "Build and solve a linear model",
                "equation_battle": True,
                "boss": True,
                "distractors": "divides 36 by 4 before subtracting 12; gives dollars instead of quests; uses 12q + 4; stops at 4q = 24",
            },
            {
                "focus": "System modeling boss",
                "question": "A shop sold 7 items total. Apples cost 2 dollars each, berries cost 3 dollars each, and the total was 19 dollars. How many apples and berries were sold?",
                "answer": "2 apples and 5 berries.",
                "explanation": "Let a be apples and b be berries. The system is a + b = 7 and 2a + 3b = 19. From a = 7 - b, substitute to get 2(7 - b) + 3b = 19, so b = 5 and a = 2.",
                "type": "Boss modeling",
                "skill": "Create and solve a two-variable system",
                "equation_battle": True,
                "boss": True,
                "distractors": "swaps the item counts; uses one equation only; gives non-integer counts; forgets the total item equation",
            },
            {
                "focus": "Domain boss",
                "question": "Find the domain of h(x) = sqrt(12 - 3x)/(x + 1).",
                "answer": "(-infinity, -1) union (-1, 4].",
                "explanation": "The square root requires 12 - 3x >= 0, so x <= 4. The denominator requires x != -1. Combining these gives (-infinity, -1) union (-1, 4].",
                "type": "Boss restrictions",
                "skill": "Combine radical and rational domain restrictions",
                "visual": True,
                "boss": True,
                "distractors": "uses x >= 4; forgets to remove -1; removes 4 even though the square root may be zero; gives all real numbers except -1",
            },
            {
                "focus": "Composition equation boss",
                "question": "Let f(x) = 3x - 5 and g(x) = x^2 + 1. Solve f(g(x)) = 22.",
                "answer": "x = 2sqrt(2) or x = -2sqrt(2).",
                "explanation": "First compose: f(g(x)) = 3(x^2 + 1) - 5 = 3x^2 - 2. Set 3x^2 - 2 = 22, so 3x^2 = 24 and x^2 = 8. Thus x = 2sqrt(2) or x = -2sqrt(2).",
                "type": "Boss synthesis",
                "skill": "Compose functions and solve the resulting equation",
                "equation_battle": True,
                "boss": True,
                "distractors": "uses g(f(x)); drops the square; keeps only the positive root; solves 3x - 5 = 22",
            },
            {
                "focus": "Projectile quadratic boss",
                "question": "A projectile has height h(t) = -16t^2 + 64t + 80. Find its maximum height and the positive time when it hits the ground.",
                "answer": "Maximum height 144 at t = 2 seconds; it hits the ground at t = 5 seconds.",
                "explanation": "The vertex time is t = -b/(2a) = -64/(2(-16)) = 2. Then h(2) = 144. For the ground, solve -16t^2 + 64t + 80 = 0, or t^2 - 4t - 5 = 0, giving t = 5 or t = -1. The positive time is 5 seconds.",
                "type": "Boss modeling",
                "skill": "Use a quadratic model for maximum and intercept",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "uses the negative time; finds only the maximum; uses t = 4 as vertex time; forgets units",
            },
            {
                "focus": "Polynomial factor boss",
                "question": "Factor f(x) = x^3 - 2x^2 - 5x + 6 completely if x = 1 is a zero, then list all zeros.",
                "answer": "f(x) = (x - 1)(x - 3)(x + 2); zeros -2, 1, and 3.",
                "explanation": "Divide by x - 1 to get x^2 - x - 6. Factor the quotient as (x - 3)(x + 2). The zeros are 1, 3, and -2.",
                "type": "Boss synthesis",
                "skill": "Use factor theorem and quadratic factoring",
                "equation_battle": True,
                "boss": True,
                "distractors": "uses x + 1 as the factor; lists factors as zeros; misses the negative zero; stops after synthetic division",
            },
            {
                "focus": "Rational expression boss",
                "question": "Simplify (x^2 - 9)/(x^2 - x - 6), then give the restrictions, hole, and vertical asymptote.",
                "answer": "Simplified form (x + 3)/(x + 2); restrictions x != 3 and x != -2; hole (3, 6/5); vertical asymptote x = -2.",
                "explanation": "Factor to get (x - 3)(x + 3)/((x - 3)(x + 2)). Cancel x - 3, but keep original restrictions x != 3 and x != -2. The canceled factor creates a hole at x = 3 with y = (3 + 3)/(3 + 2) = 6/5, and x = -2 remains a vertical asymptote.",
                "type": "Boss synthesis",
                "skill": "Simplify rational expressions while preserving graph features",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "forgets x = 3 as a restriction; calls the hole a vertical asymptote; cancels x terms instead of factors; gives hole y = 0",
            },
            {
                "focus": "Exponential-logarithmic boss",
                "question": "How long does it take 200 dollars growing at 8 percent per year to reach 400 dollars? Give the answer to the nearest hundredth of a year.",
                "answer": "9.01 years.",
                "explanation": "Solve 200(1.08)^t = 400. Divide by 200 to get (1.08)^t = 2. Taking logs gives t = ln(2)/ln(1.08), which is about 9.01 years.",
                "type": "Boss modeling",
                "skill": "Solve an exponential equation with logarithms",
                "equation_battle": True,
                "boss": True,
                "distractors": "uses 8 years from the percent; uses simple interest; divides logs in the wrong order; rounds to 9.00 too early",
            },
            {
                "focus": "Trig graph boss",
                "question": "For y = 3sin(2(x - pi/4)) + 1, give the amplitude, period, phase shift, and midline.",
                "answer": "Amplitude 3; period pi; phase shift right pi/4; midline y = 1.",
                "explanation": "Amplitude is |3| = 3. The period is 2pi/2 = pi. The expression x - pi/4 means a shift right pi/4. The +1 gives midline y = 1.",
                "type": "Boss graphing",
                "skill": "Read transformed sine graph parameters",
                "visual": True,
                "boss": True,
                "distractors": "uses period 2pi; shifts left pi/4; uses midline y = -1; treats 2 as amplitude",
            },
            {
                "focus": "Trig equation boss",
                "question": "Solve sin^2 x + sin x = 0 on 0 <= x < 2pi.",
                "answer": "x = 0, pi, or 3pi/2.",
                "explanation": "Factor: sin x(sin x + 1) = 0. So sin x = 0 gives x = 0 and pi on the interval, and sin x = -1 gives x = 3pi/2.",
                "type": "Boss equation",
                "skill": "Factor and solve a trigonometric equation",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "drops sin x = -1; includes 2pi even though the interval excludes it; solves cosine instead; divides by sin x and loses solutions",
            },
            {
                "focus": "Law of sines boss",
                "question": "In a triangle, A = 30 degrees, B = 45 degrees, and side a = 8. Find side b.",
                "answer": "8sqrt(2).",
                "explanation": "Use the law of sines: b/sin 45 deg = 8/sin 30 deg. Thus b = 8(sin 45 deg)/(sin 30 deg) = 8(sqrt(2)/2)/(1/2) = 8sqrt(2).",
                "type": "Boss geometry",
                "skill": "Apply the law of sines with exact values",
                "visual": True,
                "boss": True,
                "distractors": "uses cosine law; swaps the sine ratio; gives 4sqrt(2); uses degrees as side lengths",
            },
            {
                "focus": "Geometric series boss",
                "question": "Find the sum of the first 8 terms of the geometric sequence with a_1 = 3 and r = 2.",
                "answer": "765.",
                "explanation": "Use S_n = a_1(r^n - 1)/(r - 1) for r not equal to 1. Then S_8 = 3(2^8 - 1)/(2 - 1) = 3(255) = 765.",
                "type": "Boss sequence",
                "skill": "Use a finite geometric series formula",
                "equation_battle": True,
                "boss": True,
                "distractors": "finds only the eighth term; uses arithmetic series formula; starts with n = 7; gives 768",
            },
            {
                "focus": "Ellipse foci boss",
                "question": "For (x + 1)^2/16 + (y - 2)^2/9 = 1, find the center and foci.",
                "answer": "Center (-1, 2); foci (-1 - sqrt(7), 2) and (-1 + sqrt(7), 2).",
                "explanation": "The center is (-1, 2). Since the larger denominator is under the x-term, a^2 = 16 and b^2 = 9. Then c^2 = 16 - 9 = 7, so the foci are sqrt(7) units left and right of the center.",
                "type": "Boss conic",
                "skill": "Read ellipse foci from standard form",
                "visual": True,
                "boss": True,
                "distractors": "uses c^2 = 25; places foci vertically; reads center (1, -2); gives vertices instead of foci",
            },
            {
                "focus": "Vector navigation boss",
                "question": "An airplane flies with velocity <120, 0> miles per hour while wind adds <0, -30> miles per hour. After 2 hours, what is the displacement and total distance from the start?",
                "answer": "Displacement <240, -60>; distance 60sqrt(17) miles.",
                "explanation": "The resultant velocity is <120, -30>. Over 2 hours, displacement is 2<120, -30> = <240, -60>. Its magnitude is sqrt(240^2 + (-60)^2) = sqrt(61200) = 60sqrt(17).",
                "type": "Boss vector modeling",
                "skill": "Combine velocity vectors and scale by time",
                "visual": True,
                "boss": True,
                "distractors": "forgets to multiply by 2 hours; adds speeds only; gives distance 300; ignores the wind component",
            },
            {
                "focus": "Complex polar boss",
                "question": "Compute [2(cos 30 deg + i sin 30 deg)]^3.",
                "answer": "8i.",
                "explanation": "By De Moivre's theorem, cube the modulus and triple the angle: 2^3(cos 90 deg + i sin 90 deg) = 8(0 + i) = 8i.",
                "type": "Boss complex numbers",
                "skill": "Use polar powers of complex numbers",
                "equation_battle": True,
                "boss": True,
                "distractors": "triples the modulus; keeps angle 30 degrees; gives 8 as a real number; squares instead of cubes",
            },
            {
                "focus": "Rational equation boss",
                "question": "Solve 1/(x - 2) + 1/(x + 2) = 1.",
                "answer": "x = 1 + sqrt(5) or x = 1 - sqrt(5).",
                "explanation": "The restrictions are x != 2 and x != -2. Multiply by (x - 2)(x + 2) to get (x + 2) + (x - 2) = x^2 - 4. Thus 2x = x^2 - 4, so x^2 - 2x - 4 = 0. The quadratic formula gives x = 1 plus-or-minus sqrt(5), and neither value violates the restrictions.",
                "type": "Boss equation",
                "skill": "Solve a rational equation with restrictions",
                "equation_battle": True,
                "boss": True,
                "distractors": "cancels denominators separately; forgets restrictions; gives x = 2; drops the negative root",
            },
            {
                "focus": "Logarithm property boss",
                "question": "Solve 2log_3(x) = log_3(81).",
                "answer": "x = 9.",
                "explanation": "Since log_3(81) = 4, the equation is 2log_3(x) = 4. Then log_3(x) = 2, so x = 9. The logarithm requires x > 0, which is satisfied.",
                "type": "Boss logarithms",
                "skill": "Solve a logarithmic equation with domain checking",
                "equation_battle": True,
                "boss": True,
                "distractors": "keeps x = -9; divides 81 by 2; treats log_3(x) as 3x; ignores the domain",
            },
            {
                "focus": "Quadratic optimization boss",
                "question": "A rectangle has perimeter 40. If one side is x, its area is A(x) = x(20 - x). What dimensions give the maximum area, and what is that area?",
                "answer": "10 by 10; maximum area 100 square units.",
                "explanation": "Expand A(x) = -x^2 + 20x. The vertex occurs at x = -b/(2a) = -20/(2(-1)) = 10. The other side is 20 - 10 = 10, and the area is 100.",
                "type": "Boss modeling",
                "skill": "Use a quadratic vertex for optimization",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "uses side 20 and 0; maximizes perimeter instead of area; gives area 40; forgets the other dimension",
            },
            {
                "focus": "Radical equation boss",
                "question": "Solve sqrt(x + 5) = x - 1.",
                "answer": "x = 4.",
                "explanation": "The right side requires x - 1 >= 0, so x >= 1. Square both sides: x + 5 = (x - 1)^2 = x^2 - 2x + 1. This gives x^2 - 3x - 4 = 0, so x = 4 or x = -1. Only x = 4 satisfies the original equation.",
                "type": "Boss equation",
                "skill": "Solve and check a radical equation",
                "equation_battle": True,
                "boss": True,
                "distractors": "keeps x = -1; forgets to square x - 1 as a binomial; ignores x >= 1; stops at the quadratic",
            },
            {
                "focus": "Representation synthesis boss",
                "question": "A robot starts at (0, 0), moves by <3, 4> and then by <-1, 2>. Treat its final point (a, b) as the complex number a + bi. Find the distance from the origin and compute (a + bi)(1 - i).",
                "answer": "Distance 2sqrt(10); product 8 + 4i.",
                "explanation": "The total displacement is <2, 6>, so the final complex number is 2 + 6i. The distance from the origin is sqrt(2^2 + 6^2) = sqrt(40) = 2sqrt(10). The product is (2 + 6i)(1 - i) = 2 - 2i + 6i - 6i^2 = 8 + 4i.",
                "type": "Final boss synthesis",
                "skill": "Connect vectors, distance, and complex multiplication",
                "equation_battle": True,
                "visual": True,
                "boss": True,
                "distractors": "uses final point (4, 2); treats distance as 8; forgets i^2 = -1; multiplies only real parts",
            },
        ],
        "next_topic": "Course completion",
    },
]


if __name__ == "__main__":
    generate_batch(PHASES)
