from __future__ import annotations

try:
    from .phase_generation_lib import generate_batch
except ImportError:
    from phase_generation_lib import generate_batch


def ex(
    focus: str,
    question: str,
    answer: str,
    explanation: str,
    **extra: object,
) -> dict:
    item = {
        "focus": focus,
        "question": question,
        "answer": answer,
        "explanation": explanation,
    }
    item.update(extra)
    return item


PHASES = [
    {
        "id": 35,
        "topic": "Rational asymptotes",
        "subtopic": "Vertical, horizontal, and slant asymptotes of rational functions",
        "prerequisites": "Rational expression simplification, rational restrictions and holes, factoring, and polynomial degree comparisons",
        "metadata_prereq": "rational_simplification, restrictions_and_holes, factoring, polynomial_degree",
        "metadata_misconceptions": "hole_as_vertical_asymptote, denominator_only_rule, degree_rule_reversal, ignoring_cancellation",
        "review": [
            "Factor numerators and denominators before deciding what cancels.",
            "Values that make the original denominator zero are restrictions.",
            "A canceled factor creates a hole; an uncanceled denominator factor can create a vertical asymptote.",
            "Compare polynomial degrees to predict end behavior of rational functions.",
            "Use polynomial division when the numerator degree is exactly one more than the denominator degree.",
        ],
        "concepts": [
            "Vertical asymptotes come from uncanceled denominator zeros.",
            "Horizontal asymptotes depend on the degree comparison after the rational expression is simplified.",
            "If numerator and denominator have the same degree, the horizontal asymptote is the ratio of leading coefficients.",
            "If the numerator degree is smaller, the horizontal asymptote is y = 0.",
            "If the numerator degree is exactly one more, a slant asymptote comes from polynomial division.",
            "Holes and asymptotes both come from restrictions, but they describe different graph behavior.",
        ],
        "misconceptions": [
            "Treating every excluded x-value as a vertical asymptote.",
            "Finding horizontal asymptotes from constant terms instead of leading terms.",
            "Forgetting to simplify before classifying holes and vertical asymptotes.",
            "Claiming a horizontal asymptote whenever the numerator has larger degree.",
            "Using the quotient from division but forgetting to drop the remainder for a slant asymptote.",
        ],
        "exercises": [
            ex(
                "vertical asymptote from an uncanceled factor",
                "Find the vertical asymptote of f(x) = 5/(x - 3).",
                "x = 3",
                "The denominator is zero when x - 3 = 0, so x = 3. No factor cancels, so the graph has a vertical asymptote at x = 3.",
                visual=True,
            ),
            ex(
                "hole versus vertical asymptote",
                "For f(x) = (x - 2)/((x - 2)(x + 5)), identify the hole and the vertical asymptote.",
                "Hole at x = 2; vertical asymptote x = -5",
                "The factor x - 2 cancels, so x = 2 is a hole. The remaining denominator x + 5 is zero at x = -5, giving a vertical asymptote.",
                visual=True,
            ),
            ex(
                "horizontal asymptote y equals zero",
                "Find the horizontal asymptote of f(x) = (4x + 1)/(2x^2 - 7).",
                "y = 0",
                "The numerator has degree 1 and the denominator has degree 2. Since the numerator degree is smaller, f(x) approaches 0 as x grows large.",
            ),
            ex(
                "horizontal asymptote from leading coefficients",
                "Find the horizontal asymptote of f(x) = (6x^2 - 5)/(3x^2 + x + 9).",
                "y = 2",
                "The degrees are equal, so use the ratio of leading coefficients: 6/3 = 2. The horizontal asymptote is y = 2.",
            ),
            ex(
                "no horizontal asymptote when numerator degree is larger",
                "Does f(x) = (x^3 + 2)/(x^2 + 1) have a horizontal asymptote?",
                "No horizontal asymptote",
                "The numerator degree is 3 and the denominator degree is 2. Since the numerator degree is larger, the function has no horizontal asymptote.",
            ),
            ex(
                "slant asymptote by division",
                "Find the slant asymptote of f(x) = (x^2 + 3x + 1)/(x + 1).",
                "y = x + 2",
                "Divide x^2 + 3x + 1 by x + 1. The quotient is x + 2 with remainder -1, so the slant asymptote is y = x + 2.",
                equation_battle=True,
            ),
            ex(
                "vertical asymptotes after factoring",
                "Find the vertical asymptotes of f(x) = (x + 1)/(x^2 - 9).",
                "x = 3 and x = -3",
                "Factor the denominator: x^2 - 9 = (x - 3)(x + 3). Neither factor cancels, so x = 3 and x = -3 are vertical asymptotes.",
            ),
            ex(
                "simplify before asymptotes",
                "For f(x) = (x^2 - 4)/(x^2 - 5x + 6), find the vertical asymptote and hole.",
                "Vertical asymptote x = 3; hole at x = 2",
                "Factor to get (x - 2)(x + 2)/((x - 2)(x - 3)). The x - 2 factor cancels, so x = 2 is a hole and x = 3 is the vertical asymptote.",
                visual=True,
            ),
            ex(
                "horizontal asymptote after cancellation",
                "Find the horizontal asymptote of f(x) = (2x^2 + 2x)/(x^2 - 1).",
                "y = 2",
                "Factor first: 2x(x + 1)/((x - 1)(x + 1)) simplifies to 2x/(x - 1). The simplified degrees are equal, and 2/1 = 2.",
            ),
            ex(
                "hole coordinate",
                "Find the hole of f(x) = (x^2 - 1)/(x - 1).",
                "Hole at (1, 2)",
                "Factor x^2 - 1 as (x - 1)(x + 1). After canceling x - 1, the graph follows y = x + 1 except at x = 1, where y would be 2.",
                visual=True,
            ),
            ex(
                "two vertical asymptotes and one horizontal asymptote",
                "Find the vertical and horizontal asymptotes of f(x) = (3x^2 + 1)/(x^2 - 4).",
                "Vertical asymptotes x = 2 and x = -2; horizontal asymptote y = 3",
                "The denominator factors as (x - 2)(x + 2), so x = 2 and x = -2 are vertical asymptotes. Equal degrees give y = 3/1 = 3.",
            ),
            ex(
                "slant asymptote with negative leading term",
                "Find the slant asymptote of f(x) = (2x^2 - x + 4)/(x - 2).",
                "y = 2x + 3",
                "Polynomial division gives quotient 2x + 3 and remainder 10. The remainder becomes small far from the origin, so the slant asymptote is y = 2x + 3.",
                equation_battle=True,
            ),
            ex(
                "asymptote from transformed reciprocal",
                "Find the vertical and horizontal asymptotes of f(x) = 4/(x + 2) - 5.",
                "Vertical asymptote x = -2; horizontal asymptote y = -5",
                "The denominator x + 2 is zero at x = -2. The reciprocal part approaches 0 for large x, leaving the horizontal asymptote y = -5.",
                visual=True,
            ),
            ex(
                "domain restriction that becomes a hole",
                "For f(x) = (x^2 + 5x + 6)/(x + 2), find the removable restriction and the simplified graph.",
                "Removable restriction x = -2; simplified graph y = x + 3",
                "The numerator factors as (x + 2)(x + 3). Cancel x + 2 to get y = x + 3, but x = -2 remains excluded as a hole.",
            ),
            ex(
                "classifying all asymptote types",
                "Classify the end behavior and vertical asymptote of f(x) = (x^2 + 1)/(x - 4).",
                "Vertical asymptote x = 4; slant asymptote y = x + 4",
                "The denominator is zero at x = 4. Since the numerator degree is one more than the denominator degree, divide to get quotient x + 4 with remainder 17.",
                boss=True,
            ),
            ex(
                "build a rational function from asymptotes",
                "Give one rational function with vertical asymptote x = 1 and horizontal asymptote y = 3.",
                "One answer is f(x) = 3 + 2/(x - 1)",
                "The term 2/(x - 1) creates a vertical asymptote at x = 1 and approaches 0 for large x, so the horizontal asymptote is y = 3.",
                reverse_variant="Give the asymptotes and ask the player to build a rational function that has them.",
            ),
            ex(
                "error analysis with canceled factors",
                "A player says f(x) = (x - 4)/(x^2 - 16) has vertical asymptotes x = 4 and x = -4. What is the correction?",
                "x = 4 is a hole; x = -4 is the only vertical asymptote",
                "Factor the denominator as (x - 4)(x + 4). The x - 4 factor cancels, so it creates a hole rather than a vertical asymptote.",
                boss=True,
            ),
            ex(
                "asymptote from table behavior",
                "A rational function has values 101, 201, and 1001 near x = 2 from the right, while values far left and far right approach 4. Name the likely asymptotes.",
                "Vertical asymptote x = 2; horizontal asymptote y = 4",
                "The values grow without bound near x = 2, which indicates a vertical asymptote there. The far-end values approach 4, giving horizontal asymptote y = 4.",
                visual=True,
                boss=True,
            ),
            ex(
                "slant asymptote with missing terms",
                "Find the slant asymptote of f(x) = (x^2 - 9)/(x - 1).",
                "y = x + 1",
                "Divide x^2 - 9 by x - 1. The quotient is x + 1 with remainder -8, so the slant asymptote is y = x + 1.",
                boss=True,
            ),
            ex(
                "mixed rational asymptote summary",
                "For f(x) = (2x^2 - 8)/(x^2 - x - 6), identify holes, vertical asymptotes, and horizontal asymptote.",
                "Hole at x = -2; vertical asymptote x = 3; horizontal asymptote y = 2",
                "Factor as 2(x - 2)(x + 2)/((x - 3)(x + 2)). The x + 2 factor cancels, so x = -2 is a hole; x = 3 remains a vertical asymptote. Equal degrees give y = 2.",
                boss=True,
            ),
        ],
        "next_topic": "Exponential growth",
    },
    {
        "id": 36,
        "topic": "Exponential growth",
        "subtopic": "Growth factors, percent increase, doubling, and exponential models",
        "prerequisites": "Function notation, exponent rules, percent change, and graph interpretation",
        "metadata_prereq": "function_notation, exponent_rules, percent_change, graph_interpretation",
        "metadata_misconceptions": "adding_instead_of_multiplying, percent_factor_confusion, exponent_base_confusion, linear_growth_assumption",
        "review": [
            "A percent increase of r becomes a multiplier of 1 + r.",
            "Repeated multiplication creates exponential change.",
            "Function notation such as f(3) means evaluate when the input is 3.",
            "Powers count repeated factors, not repeated addition.",
            "Tables with a constant ratio suggest exponential behavior.",
        ],
        "concepts": [
            "An exponential growth model has the form A = a b^t with a > 0 and b > 1.",
            "The initial value is the output when t = 0.",
            "The growth factor b is the multiplier for each equal time step.",
            "The percent growth rate is b - 1, written as a percent.",
            "Doubling models use a growth factor of 2 for each doubling interval.",
            "Continuous growth uses A = P e^(rt), where r is the continuous growth rate.",
        ],
        "misconceptions": [
            "Adding the percent rate each period instead of multiplying by the growth factor.",
            "Using 12 for a 12 percent increase instead of 1.12.",
            "Mistaking the initial value for the growth factor.",
            "Assuming every increasing table is exponential.",
            "Rounding too early in a multi-step model.",
        ],
        "exercises": [
            ex(
                "evaluate a simple growth model",
                "If f(t) = 3(2^t), find f(4).",
                "48",
                "Substitute t = 4: f(4) = 3(2^4) = 3(16) = 48.",
            ),
            ex(
                "identify initial value and growth factor",
                "For A(t) = 80(1.25^t), name the initial value and growth factor.",
                "Initial value 80; growth factor 1.25",
                "When t = 0, 1.25^0 = 1, so the starting amount is 80. The base 1.25 is the multiplier each period.",
            ),
            ex(
                "convert percent increase to multiplier",
                "What growth factor represents a 7 percent increase each year?",
                "1.07",
                "A 7 percent increase means keep 100 percent and add 7 percent, so the multiplier is 1 + 0.07 = 1.07.",
            ),
            ex(
                "write a growth equation from a context",
                "A town has 5000 people and grows by 4 percent per year. Write a model for the population after t years.",
                "P(t) = 5000(1.04^t)",
                "The initial value is 5000. A 4 percent increase gives growth factor 1.04, so the model is P(t) = 5000(1.04^t).",
                modeling_variant="Change the town to a club, colony, or account and keep the growth factor interpretation.",
            ),
            ex(
                "evaluate percent growth",
                "A video has 200 views and grows by 50 percent per day. How many views are expected after 3 days?",
                "675 views",
                "Use 200(1.5^3). Since 1.5^3 = 3.375, the expected count is 200(3.375) = 675 views.",
            ),
            ex(
                "find a growth factor from a table",
                "A table shows 6, 18, 54, 162 for equal time steps. What is the growth factor?",
                "3",
                "Each term is multiplied by 3: 18/6 = 3, 54/18 = 3, and 162/54 = 3.",
                visual=True,
            ),
            ex(
                "build a model from two consecutive values",
                "An exponential sequence has A(0) = 12 and A(1) = 18. Write A(t).",
                "A(t) = 12(1.5^t)",
                "The initial value is 12. The one-step multiplier is 18/12 = 1.5, so A(t) = 12(1.5^t).",
            ),
            ex(
                "doubling model",
                "A bacteria culture starts with 40 cells and doubles every hour. Write a model for t hours.",
                "B(t) = 40(2^t)",
                "Doubling means multiply by 2 each hour, and 40 is the starting amount.",
            ),
            ex(
                "solve a doubling equation by inspection",
                "If B(t) = 40(2^t), when will the culture reach 320 cells?",
                "t = 3 hours",
                "Set 40(2^t) = 320. Divide by 40 to get 2^t = 8, so t = 3.",
                equation_battle=True,
            ),
            ex(
                "distinguish exponential from linear growth",
                "Which table is exponential: A has outputs 5, 10, 15, 20; B has outputs 5, 10, 20, 40?",
                "Table B",
                "Table A adds 5 each step, so it is linear. Table B multiplies by 2 each step, so it is exponential.",
                visual=True,
            ),
            ex(
                "find percent growth from growth factor",
                "A model has growth factor 1.18. What is the percent growth rate?",
                "18 percent",
                "Subtract 1 from the growth factor: 1.18 - 1 = 0.18, which is 18 percent.",
            ),
            ex(
                "evaluate growth with fractional initial value",
                "A plant is 2.5 cm tall and grows by 20 percent each week. What height is predicted after 2 weeks?",
                "3.6 cm",
                "Use 2.5(1.2^2). Since 1.2^2 = 1.44, the height is 2.5(1.44) = 3.6 cm.",
            ),
            ex(
                "growth from graph intercept",
                "An exponential growth graph crosses the y-axis at 9 and triples each step. Write the model.",
                "y = 9(3^x)",
                "The y-intercept gives the initial value 9. Tripling each step means growth factor 3.",
                visual=True,
            ),
            ex(
                "compare two growth models",
                "Which is larger at t = 3: A(t) = 100(1.1^t) or B(t) = 80(1.2^t)?",
                "B(3) is larger",
                "A(3) = 100(1.331) = 133.1. B(3) = 80(1.728) = 138.24, so B(3) is larger.",
                boss=True,
            ),
            ex(
                "correct a growth comparison",
                "A player says A(t) = 100(1.1^t) is larger than B(t) = 80(1.2^t) at t = 3 because 100 > 80. What is the correct comparison?",
                "B(3) is larger",
                "Initial value alone is not enough. A(3) = 133.1 and B(3) = 138.24, so B is larger at t = 3.",
                boss=True,
            ),
            ex(
                "solve for starting value",
                "An exponential model with growth factor 1.5 has value 54 at t = 2. What is the initial value?",
                "24",
                "Let A(t) = a(1.5^t). Then 54 = a(1.5^2) = 2.25a, so a = 54/2.25 = 24.",
                equation_battle=True,
            ),
            ex(
                "continuous growth evaluation",
                "A quantity follows A(t) = 300e^(0.02t). What is A(10) to the nearest whole number?",
                "366",
                "A(10) = 300e^0.2. Since e^0.2 is about 1.2214, A(10) is about 366.42, which rounds to 366.",
                boss=True,
            ),
            ex(
                "correct continuous growth rounding",
                "A quantity follows A(t) = 500e^(0.04t). What is A(3) to the nearest whole number?",
                "564",
                "Substitute t = 3 to get 500e^0.12. This is about 563.75, so the nearest whole number is 564.",
                boss=True,
            ),
            ex(
                "reverse engineer a growth factor",
                "A value grows from 20 to 45 in two equal steps. What is the growth factor per step?",
                "1.5",
                "Let the factor be b. Then 20b^2 = 45, so b^2 = 2.25 and b = 1.5 because a growth factor is positive.",
                equation_battle=True,
                reverse_variant="Give start and end values over a fixed number of steps and ask for the growth factor.",
            ),
            ex(
                "multi-step growth model interpretation",
                "A game item worth 30 coins increases by 10 percent per level. How much is it worth after 5 levels, to the nearest coin?",
                "48 coins",
                "Use 30(1.10^5). Since 1.10^5 is about 1.61051, the value is about 48.315 coins, which rounds to 48.",
                boss=True,
            ),
        ],
        "next_topic": "Exponential decay",
    },
    {
        "id": 37,
        "topic": "Exponential decay",
        "subtopic": "Decay factors, percent decrease, half-life, and decreasing exponential models",
        "prerequisites": "Exponential growth, exponent rules, percent change, and function notation",
        "metadata_prereq": "exponential_growth, exponent_rules, percent_change, function_notation",
        "metadata_misconceptions": "subtracting_rate_from_output, decay_factor_confusion, half_life_linear_error, negative_base_error",
        "review": [
            "A percent decrease of r becomes a multiplier of 1 - r.",
            "An exponential model uses repeated multiplication over equal intervals.",
            "A base between 0 and 1 creates decay when the initial value is positive.",
            "Half-life means multiplying by 1/2 for each half-life interval.",
            "Function notation tells which input value to substitute.",
        ],
        "concepts": [
            "An exponential decay model has the form A = a b^t with a > 0 and 0 < b < 1.",
            "The decay factor b is the amount kept each period.",
            "The percent decay rate is 1 - b, written as a percent.",
            "Half-life models can be written A = A0(1/2)^(t/h), where h is the half-life.",
            "Exponential decay approaches zero for positive initial values but does not reach zero in the basic model.",
            "Continuous decay uses A = P e^(-rt), where r is positive.",
        ],
        "misconceptions": [
            "Using 0.15 instead of 0.85 for a 15 percent decrease.",
            "Subtracting the same amount each period instead of multiplying by the same factor.",
            "Making the base negative because the situation is decreasing.",
            "Confusing half-life with subtracting half of the original amount each interval.",
            "Rounding the decay factor before solving when an exact fraction is available.",
        ],
        "exercises": [
            ex(
                "identify decay factor",
                "For A(t) = 120(0.8^t), what is the decay factor?",
                "0.8",
                "The base of the exponential expression is the per-period multiplier, so the decay factor is 0.8.",
            ),
            ex(
                "convert percent decrease to multiplier",
                "What decay factor represents a 12 percent decrease each month?",
                "0.88",
                "A 12 percent decrease means 88 percent remains, so the multiplier is 1 - 0.12 = 0.88.",
            ),
            ex(
                "evaluate a decay model",
                "If f(t) = 50(0.5^t), find f(3).",
                "6.25",
                "Substitute t = 3: f(3) = 50(0.5^3) = 50(0.125) = 6.25.",
            ),
            ex(
                "write a percent decay model",
                "A car is worth 18000 dollars and loses 10 percent of its value each year. Write V(t).",
                "V(t) = 18000(0.90^t)",
                "The initial value is 18000. Losing 10 percent means keeping 90 percent, so the decay factor is 0.90.",
                modeling_variant="Use depreciation, cooling, medicine, or fading light as the context.",
            ),
            ex(
                "evaluate depreciation",
                "A bike worth 600 dollars loses 20 percent of its value each year. What is it worth after 2 years?",
                "384 dollars",
                "Use 600(0.8^2). Since 0.8^2 = 0.64, the value is 600(0.64) = 384 dollars.",
            ),
            ex(
                "find percent decay from factor",
                "A model has decay factor 0.73. What percent decrease does this represent?",
                "27 percent",
                "The decrease is 1 - 0.73 = 0.27, which is 27 percent.",
            ),
            ex(
                "table with constant ratio below one",
                "A table shows 160, 80, 40, 20 for equal time steps. What exponential model starts at t = 0?",
                "A(t) = 160(0.5^t)",
                "The starting value is 160 and each step multiplies by 1/2, so A(t) = 160(0.5^t).",
                visual=True,
            ),
            ex(
                "half-life model",
                "A sample starts with 96 grams and has half-life 5 hours. Write a model for t hours.",
                "A(t) = 96(1/2)^(t/5)",
                "Every 5 hours the sample is multiplied by 1/2, so the exponent counts t/5 half-life intervals.",
            ),
            ex(
                "half-life evaluation",
                "Using A(t) = 96(1/2)^(t/5), how much remains after 15 hours?",
                "12 grams",
                "Since 15/5 = 3 half-lives, A(15) = 96(1/2)^3 = 96/8 = 12 grams.",
            ),
            ex(
                "solve simple decay by inspection",
                "If A(t) = 200(0.5^t), when is A(t) = 25?",
                "t = 3",
                "Set 200(0.5^t) = 25. Divide by 200 to get 0.5^t = 1/8, which happens when t = 3.",
                equation_battle=True,
            ),
            ex(
                "distinguish linear decrease from exponential decay",
                "Which table is exponential decay: A has outputs 100, 90, 80, 70; B has outputs 100, 80, 64, 51.2?",
                "Table B",
                "Table A subtracts 10 each step. Table B multiplies by 0.8 each step, so it is exponential decay.",
                visual=True,
            ),
            ex(
                "initial value from later value",
                "A model has decay factor 0.5 and A(4) = 10. What is A(0)?",
                "160",
                "A(4) = a(0.5^4) = a/16. If a/16 = 10, then a = 160.",
                equation_battle=True,
            ),
            ex(
                "continuous decay evaluation",
                "A medicine amount is M(t) = 80e^(-0.25t). How much remains after 4 hours, to the nearest tenth?",
                "29.4",
                "M(4) = 80e^-1. Since e^-1 is about 0.3679, the amount is about 29.4.",
            ),
            ex(
                "compare two decay models",
                "Which is larger at t = 2: A(t) = 100(0.7^t) or B(t) = 80(0.8^t)?",
                "B(2) is larger",
                "A(2) = 100(0.49) = 49. B(2) = 80(0.64) = 51.2, so B is larger.",
                boss=True,
            ),
            ex(
                "decay graph interpretation",
                "A decay graph has y-intercept 300 and each step keeps 60 percent. Write the equation.",
                "y = 300(0.6^x)",
                "The y-intercept gives the initial value 300, and keeping 60 percent gives decay factor 0.6.",
                visual=True,
            ),
            ex(
                "reverse engineer a decay factor",
                "A value drops from 500 to 320 in two equal steps. What is the decay factor per step?",
                "0.8",
                "Let the factor be b. Then 500b^2 = 320, so b^2 = 0.64 and b = 0.8 because a decay factor is positive.",
                equation_battle=True,
            ),
            ex(
                "error analysis percent decrease",
                "A player models a 30 percent decrease from 90 as 90(0.30^t). What should the model be?",
                "A(t) = 90(0.70^t)",
                "A 30 percent decrease means 70 percent remains each step. The base should be 0.70, not 0.30.",
                boss=True,
            ),
            ex(
                "decay toward zero interpretation",
                "For A(t) = 12(0.25^t), what value does A(t) approach as t becomes very large?",
                "0",
                "Each step keeps one fourth of the previous amount. The values get closer and closer to 0.",
                visual=True,
            ),
            ex(
                "multi-step half-life with nonzero start",
                "A 72 gram sample has half-life 3 days. How much remains after 12 days?",
                "4.5 grams",
                "Twelve days is 12/3 = 4 half-lives. The amount is 72(1/2)^4 = 72/16 = 4.5 grams.",
                boss=True,
            ),
            ex(
                "mixed decay model interpretation",
                "A phone battery has 90 percent charge and loses 18 percent of its charge each hour. Estimate the charge after 3 hours to the nearest percent.",
                "50 percent",
                "Use 90(0.82^3). Since 0.82^3 is about 0.551, the charge is about 49.6 percent, which rounds to 50 percent.",
                boss=True,
            ),
        ],
        "next_topic": "Compound interest",
    },
    {
        "id": 38,
        "topic": "Compound interest",
        "subtopic": "Periodic and continuous compounding with interest formulas",
        "prerequisites": "Exponential growth, percent rates, exponent rules, and calculator evaluation",
        "metadata_prereq": "exponential_growth, percent_rates, exponent_rules, calculator_evaluation",
        "metadata_misconceptions": "rate_not_decimal, compounding_frequency_error, simple_interest_confusion, exponent_period_confusion",
        "review": [
            "Convert percent rates to decimals before using a formula.",
            "Periodic compounding uses A = P(1 + r/n)^(nt).",
            "Continuous compounding uses A = Pe^(rt).",
            "The principal P is the starting amount.",
            "The exponent nt counts the total number of compounding periods.",
        ],
        "concepts": [
            "More frequent compounding changes both the periodic rate and the number of periods.",
            "The annual rate r is divided by n before it is applied each period.",
            "The exponent nt multiplies years by periods per year.",
            "Interest earned is final amount minus principal.",
            "Continuous compounding is the limiting case A = Pe^(rt).",
            "Solving for principal means dividing the future amount by the growth factor.",
        ],
        "misconceptions": [
            "Using r = 5 instead of r = 0.05 for 5 percent.",
            "Putting n only in the exponent and not in the periodic rate.",
            "Using simple interest when the problem says compounded.",
            "Forgetting that monthly compounding has 12 periods per year.",
            "Rounding inside the exponent before evaluating the final amount.",
        ],
        "exercises": [
            ex(
                "annual compounding setup",
                "Invest 1000 dollars at 6 percent compounded annually for 3 years. What is the amount?",
                "$1191.02",
                "Use A = 1000(1.06)^3. Since 1.06^3 = 1.191016, the amount is $1191.02.",
            ),
            ex(
                "identify formula parts",
                "In A = 2500(1 + 0.04/4)^(4t), what are P, r, and n?",
                "P = 2500, r = 0.04, n = 4",
                "The form is P(1 + r/n)^(nt). Here the principal is 2500, the annual rate is 0.04, and quarterly compounding means n = 4.",
            ),
            ex(
                "quarterly compounding",
                "Find the amount from 2000 dollars at 8 percent compounded quarterly for 1 year.",
                "$2164.86",
                "Use A = 2000(1 + 0.08/4)^4 = 2000(1.02)^4. This equals about $2164.86.",
            ),
            ex(
                "monthly compounding exponent",
                "For 500 dollars at 12 percent compounded monthly for 2 years, what expression gives the amount?",
                "500(1.01)^24",
                "The monthly rate is 0.12/12 = 0.01 and the number of months is 12(2) = 24.",
            ),
            ex(
                "monthly compounding amount",
                "Evaluate 500 dollars at 12 percent compounded monthly for 2 years.",
                "$634.87",
                "Use 500(1.01)^24. The factor is about 1.269735, so the amount is about $634.87.",
            ),
            ex(
                "interest earned",
                "If 1500 dollars grows to 1686.23 dollars, how much interest was earned?",
                "$186.23",
                "Interest earned is final amount minus principal: 1686.23 - 1500 = 186.23.",
            ),
            ex(
                "semiannual compounding",
                "Invest 800 dollars at 5 percent compounded semiannually for 4 years. Find the amount.",
                "$974.72",
                "Semiannual means n = 2. Use 800(1 + 0.05/2)^8 = 800(1.025)^8, which is about $974.72.",
            ),
            ex(
                "daily compounding setup",
                "Write, but do not evaluate, the amount for 1200 dollars at 3 percent compounded daily for 5 years using 365 days per year.",
                "A = 1200(1 + 0.03/365)^1825",
                "The daily rate is 0.03/365, and the number of compounding periods is 365(5) = 1825.",
                modeling_variant="Change the account type and ask for the compounding expression only.",
            ),
            ex(
                "continuous compounding setup",
                "Write the continuous compounding model for 700 dollars at 4.5 percent for t years.",
                "A(t) = 700e^(0.045t)",
                "Continuous compounding uses A = Pe^(rt). Convert 4.5 percent to 0.045.",
            ),
            ex(
                "continuous compounding evaluation",
                "Find the amount for 1000 dollars at 5 percent compounded continuously for 2 years.",
                "$1105.17",
                "Use A = 1000e^(0.05)(2) = 1000e^0.1. This is about $1105.17.",
            ),
            ex(
                "solve for principal",
                "How much principal is needed to have 1210 dollars after 2 years at 10 percent compounded annually?",
                "$1000",
                "Use 1210 = P(1.10)^2. Since 1.10^2 = 1.21, P = 1210/1.21 = 1000.",
                equation_battle=True,
            ),
            ex(
                "compare compounding frequencies",
                "Which is larger after 1 year at 6 percent on 1000 dollars: annual compounding or monthly compounding?",
                "Monthly compounding",
                "Annual gives 1000(1.06) = 1060. Monthly gives 1000(1.005)^12, about 1061.68, which is larger.",
            ),
            ex(
                "find total periods",
                "An investment is compounded weekly for 3 years. How many compounding periods are used?",
                "156 periods",
                "Weekly compounding uses 52 periods per year. Over 3 years, 52(3) = 156 periods.",
            ),
            ex(
                "rate conversion",
                "What decimal rate should be used for 7.25 percent interest?",
                "0.0725",
                "Move the percent two places left: 7.25 percent = 0.0725.",
            ),
            ex(
                "choose correct compound expression",
                "Which expression models 900 dollars at 6 percent compounded quarterly for 3 years: 900(1.06)^3 or 900(1.015)^12?",
                "900(1.015)^12",
                "Quarterly compounding divides the annual rate by 4, giving 0.015 per quarter, and uses 4(3) = 12 quarters.",
                visual=True,
            ),
            ex(
                "future value target by inspection",
                "At 100 percent annual interest compounded annually, how long does 300 dollars take to become 2400 dollars?",
                "3 years",
                "A 100 percent annual rate gives factor 2. Solve 300(2^t) = 2400, so 2^t = 8 and t = 3.",
                equation_battle=True,
            ),
            ex(
                "rounding to cents",
                "Find the amount for 250 dollars at 4 percent compounded annually for 6 years, rounded to cents.",
                "$316.33",
                "Use 250(1.04)^6. The growth factor is about 1.265319, so the amount is about $316.33.",
                boss=True,
            ),
            ex(
                "error analysis compounding frequency",
                "A player writes 1000(1.08)^8 for 8 percent compounded quarterly for 2 years. What is the correct expression?",
                "1000(1.02)^8",
                "There are 8 quarters, but the rate per quarter is 0.08/4 = 0.02. The base should be 1.02.",
                boss=True,
            ),
            ex(
                "continuous versus annual comparison",
                "For 1000 dollars at 10 percent for 1 year, which is larger: annual compounding or continuous compounding?",
                "Continuous compounding",
                "Annual gives 1000(1.10) = 1100. Continuous gives 1000e^0.1, about 1105.17, so it is larger.",
                boss=True,
            ),
            ex(
                "compound interest modeling sentence",
                "A savings account has 4000 dollars at 3.6 percent compounded monthly. Write the model and find the amount after 5 years.",
                "A(t) = 4000(1.003)^(12t); A(5) is about $4787.58",
                "The monthly rate is 0.036/12 = 0.003. After 5 years there are 60 months, so A(5) = 4000(1.003)^60, about $4787.58.",
                boss=True,
            ),
        ],
        "next_topic": "Logarithm definitions",
    },
    {
        "id": 39,
        "topic": "Logarithm definitions",
        "subtopic": "Logarithms as exponents and conversions between logarithmic and exponential form",
        "prerequisites": "Exponent rules, exponential equations, inverse functions, and function notation",
        "metadata_prereq": "exponent_rules, exponential_equations, inverse_functions, function_notation",
        "metadata_misconceptions": "base_argument_swap, log_as_multiplication, domain_ignored, common_natural_log_confusion",
        "review": [
            "An exponent tells how many times a base is used as a factor.",
            "Exponential and logarithmic forms describe the same relationship.",
            "The base of a logarithm must be positive and not equal to 1.",
            "The argument of a logarithm must be positive.",
            "Common log means base 10, and natural log means base e.",
        ],
        "concepts": [
            "log_b(a) = c means b^c = a.",
            "A logarithm answers the question: what exponent goes on the base?",
            "Logarithmic functions are inverses of exponential functions with the same base.",
            "Logarithms of powers of the base evaluate cleanly.",
            "The domain restriction comes from the argument being positive.",
            "Exact log values often come from rewriting numbers as powers.",
        ],
        "misconceptions": [
            "Swapping the base and the argument when converting forms.",
            "Treating log_b(a) as b times a.",
            "Allowing zero or negative arguments in real logarithms.",
            "Forgetting that log(x) means log base 10 in many precalculus contexts.",
            "Assuming every logarithm has a whole-number value.",
        ],
        "exercises": [
            ex(
                "convert logarithmic to exponential form",
                "Rewrite log_2(8) = 3 in exponential form.",
                "2^3 = 8",
                "The base of the log is 2, the output is 3, and the argument is 8, so 2^3 = 8.",
            ),
            ex(
                "convert exponential to logarithmic form",
                "Rewrite 5^2 = 25 in logarithmic form.",
                "log_5(25) = 2",
                "The base stays 5, the result 25 becomes the log argument, and the exponent 2 becomes the log value.",
            ),
            ex(
                "evaluate a basic logarithm",
                "Evaluate log_3(81).",
                "4",
                "Since 3^4 = 81, log_3(81) = 4.",
            ),
            ex(
                "evaluate a negative logarithm value",
                "Evaluate log_5(1/25).",
                "-2",
                "Since 5^-2 = 1/25, the logarithm equals -2.",
            ),
            ex(
                "evaluate common log",
                "Evaluate log(1000).",
                "3",
                "Common log uses base 10. Since 10^3 = 1000, log(1000) = 3.",
            ),
            ex(
                "evaluate natural log of a power",
                "Evaluate ln(e^7).",
                "7",
                "Natural log has base e, so ln(e^7) asks for the exponent on e that gives e^7.",
            ),
            ex(
                "solve from log definition",
                "If log_4(x) = 3, find x.",
                "64",
                "Convert to exponential form: 4^3 = x, so x = 64.",
                equation_battle=True,
            ),
            ex(
                "solve for log output",
                "If log_2(1/8) = x, find x.",
                "-3",
                "The equation means 2^x = 1/8. Since 1/8 = 2^-3, x = -3.",
            ),
            ex(
                "find domain of a logarithm",
                "Find the domain of f(x) = log_3(x - 5).",
                "x > 5",
                "The log argument must be positive: x - 5 > 0, so x > 5.",
            ),
            ex(
                "domain with linear argument",
                "Find the domain of g(x) = ln(2x + 6).",
                "x > -3",
                "Require 2x + 6 > 0. Then 2x > -6, so x > -3.",
                equation_battle=True,
            ),
            ex(
                "identify base and argument",
                "In log_7(49) = 2, name the base, argument, and value.",
                "Base 7; argument 49; value 2",
                "The small number under log is the base, the input 49 is the argument, and the output is 2.",
            ),
            ex(
                "evaluate log with fractional base",
                "Evaluate log_(1/2)(8).",
                "-3",
                "The equation log_(1/2)(8) = x means (1/2)^x = 8. Since (1/2)^-3 = 8, the value is -3.",
            ),
            ex(
                "rewrite exponential decay as logarithm",
                "Rewrite (1/3)^4 = 1/81 in logarithmic form.",
                "log_(1/3)(1/81) = 4",
                "The base is 1/3, the result is 1/81, and the exponent is 4.",
            ),
            ex(
                "log equals zero",
                "Evaluate log_9(1).",
                "0",
                "Any allowed base to the zero power equals 1, so log_9(1) = 0.",
            ),
            ex(
                "log equals one",
                "Evaluate log_11(11).",
                "1",
                "Since 11^1 = 11, log_11(11) = 1.",
            ),
            ex(
                "error analysis base swap",
                "A player rewrites log_4(64) = 3 as 64^3 = 4. What is the correct exponential form?",
                "4^3 = 64",
                "The base of the logarithm stays the base of the exponential expression. The log value is the exponent.",
                boss=True,
            ),
            ex(
                "check whether a log is real",
                "Is log_2(-8) a real number?",
                "No real value",
                "A real logarithm requires a positive argument. Since -8 is negative, log_2(-8) has no real value.",
            ),
            ex(
                "solve for base from definition",
                "If log_b(27) = 3 and b > 0, find b.",
                "3",
                "Convert to b^3 = 27. The positive number whose cube is 27 is 3.",
                equation_battle=True,
            ),
            ex(
                "inverse relationship",
                "Simplify 6^(log_6(20)).",
                "20",
                "The logarithm log_6(20) is the exponent that makes base 6 produce 20, so 6 raised to that exponent is 20.",
            ),
            ex(
                "mixed definition challenge",
                "Find x if log_2(x - 1) = 5.",
                "33",
                "Convert to exponential form: x - 1 = 2^5 = 32, so x = 33. The argument is positive at x = 33.",
                boss=True,
            ),
        ],
        "next_topic": "Logarithm properties",
    },
    {
        "id": 40,
        "topic": "Logarithm properties",
        "subtopic": "Product, quotient, power, and change-of-base properties",
        "prerequisites": "Logarithm definitions, exponent rules, factoring, and domain restrictions",
        "metadata_prereq": "logarithm_definitions, exponent_rules, factoring, domain_restrictions",
        "metadata_misconceptions": "log_sum_false_rule, coefficient_power_confusion, domain_after_expansion, change_base_reversal",
        "review": [
            "Logarithms convert multiplication into addition.",
            "Logarithms convert division into subtraction.",
            "Exponents inside a logarithm can move to the front as coefficients.",
            "Arguments of all logarithms must be positive.",
            "Change of base rewrites a logarithm as a quotient of logs with a shared base.",
        ],
        "concepts": [
            "Product property: log_b(MN) = log_b(M) + log_b(N).",
            "Quotient property: log_b(M/N) = log_b(M) - log_b(N).",
            "Power property: log_b(M^p) = p log_b(M).",
            "Condensing reverses expansion and requires matching bases.",
            "Change of base: log_b(a) = log(a)/log(b) = ln(a)/ln(b).",
            "Expanded forms can introduce hidden domain conditions from each log argument.",
        ],
        "misconceptions": [
            "Writing log(a + b) as log(a) + log(b).",
            "Moving a coefficient into the log as multiplication instead of as a power.",
            "Condensing logs with different bases.",
            "Forgetting parentheses when applying quotient properties.",
            "Ignoring positive-argument restrictions after expanding.",
        ],
        "exercises": [
            ex(
                "expand product",
                "Expand log_3(5x).",
                "log_3(5) + log_3(x)",
                "The product property changes multiplication inside one log into addition of two logs.",
            ),
            ex(
                "expand quotient",
                "Expand log_2(x/7).",
                "log_2(x) - log_2(7)",
                "The quotient property changes division inside the log into subtraction.",
            ),
            ex(
                "expand power",
                "Expand log_5(y^4).",
                "4log_5(y)",
                "The power property moves the exponent 4 to the front as a coefficient.",
            ),
            ex(
                "expand combined expression",
                "Expand ln(3x^2/y).",
                "ln(3) + 2ln(x) - ln(y)",
                "Use product, power, and quotient properties: ln(3x^2/y) = ln(3) + ln(x^2) - ln(y) = ln(3) + 2ln(x) - ln(y).",
                equation_battle=True,
            ),
            ex(
                "condense product",
                "Condense log_4(2) + log_4(x).",
                "log_4(2x)",
                "Same-base logs added together condense into the log of a product.",
            ),
            ex(
                "condense quotient",
                "Condense log_6(a) - log_6(b).",
                "log_6(a/b)",
                "Same-base logs subtracted condense into the log of a quotient.",
            ),
            ex(
                "condense coefficient",
                "Condense 3log_2(x).",
                "log_2(x^3)",
                "A coefficient in front of a logarithm becomes an exponent inside the logarithm.",
            ),
            ex(
                "condense mixed expression",
                "Condense 2ln(x) + ln(5) - ln(y).",
                "ln(5x^2/y)",
                "Move 2 inside as an exponent to get ln(x^2), add logs to multiply by 5, then subtract to divide by y.",
                equation_battle=True,
            ),
            ex(
                "change of base",
                "Rewrite log_7(20) using common logs.",
                "log(20)/log(7)",
                "Change of base says log_7(20) = log(20)/log(7).",
            ),
            ex(
                "evaluate with change of base",
                "Use change of base to evaluate log_2(32).",
                "5",
                "log_2(32) = log(32)/log(2). Since 2^5 = 32, the quotient equals 5.",
            ),
            ex(
                "domain after expansion",
                "What restrictions are needed for ln(x - 1) + ln(x + 3)?",
                "x > 1",
                "Both arguments must be positive: x - 1 > 0 gives x > 1, and x + 3 > 0 gives x > -3. Together, x > 1.",
            ),
            ex(
                "false sum rule",
                "Is log_2(x + 5) equal to log_2(x) + log_2(5)?",
                "No",
                "The product property works for multiplication, not addition. log_2(x) + log_2(5) equals log_2(5x).",
            ),
            ex(
                "expand square root",
                "Expand log_3(sqrt(x)).",
                "(1/2)log_3(x)",
                "A square root is a power of 1/2, so log_3(sqrt(x)) = log_3(x^(1/2)) = (1/2)log_3(x).",
            ),
            ex(
                "condense with fractional coefficient",
                "Condense (1/2)ln(x) + ln(4).",
                "ln(4sqrt(x))",
                "The coefficient 1/2 becomes an exponent: (1/2)ln(x) = ln(sqrt(x)). Adding ln(4) multiplies the arguments.",
            ),
            ex(
                "expand factored argument",
                "Expand log_5((x - 1)(x + 2)).",
                "log_5(x - 1) + log_5(x + 2)",
                "The argument is a product, so use the product property. The expanded form requires x - 1 > 0 and x + 2 > 0.",
            ),
            ex(
                "condense three logs",
                "Condense log(x) + log(x - 1) - log(2).",
                "log(x(x - 1)/2)",
                "Add the first two logs to multiply their arguments, then subtract log(2) to divide by 2.",
                boss=True,
            ),
            ex(
                "error analysis coefficient",
                "A player condenses 4log_3(x) as log_3(4x). What is the correct condensed form?",
                "log_3(x^4)",
                "A coefficient becomes an exponent, not a multiplier. So 4log_3(x) = log_3(x^4).",
                boss=True,
            ),
            ex(
                "change of base direction",
                "Which is correct: log_5(12) = log(5)/log(12) or log(12)/log(5)?",
                "log(12)/log(5)",
                "The argument goes in the numerator and the base goes in the denominator.",
            ),
            ex(
                "property with exact values",
                "Use properties to evaluate log_2(8) + log_2(4).",
                "5",
                "Condense to log_2(32), or evaluate separately as 3 + 2. Either way the value is 5.",
            ),
            ex(
                "mixed expansion with restrictions",
                "Expand ln((x^2 - 9)/(x + 1)) and state restrictions for the expanded logs.",
                "ln(x - 3) + ln(x + 3) - ln(x + 1); restrictions x > 3",
                "Factor x^2 - 9 as (x - 3)(x + 3). Expanded logs require x - 3, x + 3, and x + 1 all positive, so x > 3.",
                boss=True,
            ),
        ],
        "next_topic": "Logarithmic equations",
    },
    {
        "id": 41,
        "topic": "Logarithmic equations",
        "subtopic": "Solving logarithmic equations with definitions, properties, and domain checks",
        "prerequisites": "Logarithm definitions, logarithm properties, exponential equations, and algebraic solving",
        "metadata_prereq": "logarithm_definitions, logarithm_properties, exponential_equations, algebraic_solving",
        "metadata_misconceptions": "extraneous_solution, uncombined_logs, domain_check_missing, base_mismatch",
        "review": [
            "Convert log_b(A) = c into A = b^c.",
            "Combine same-base logarithms before using one-to-one reasoning.",
            "Every logarithm argument must be positive.",
            "Solutions from algebra must be checked in the original equation.",
            "Natural logarithms and common logarithms follow the same structural rules.",
        ],
        "concepts": [
            "A single logarithm equal to a number can be solved by rewriting in exponential form.",
            "Same-base log equations can use the one-to-one property after domain checks.",
            "Product and quotient properties can combine logs before solving.",
            "Some algebraic candidates are extraneous because they make a log argument nonpositive.",
            "Equations with logs on both sides often become equations between the arguments.",
            "Approximate answers are reasonable when exact powers are not available.",
        ],
        "misconceptions": [
            "Keeping an answer that makes a logarithm argument zero or negative.",
            "Applying one-to-one reasoning before combining logs with the same base.",
            "Dropping parentheses after converting from logarithmic form.",
            "Solving log(x) + log(3) = log(12) as x + 3 = 12.",
            "Using base 10 rules for natural logs without noticing that the base still matches on both sides.",
        ],
        "exercises": [
            ex(
                "solve by exponential form",
                "Solve log_3(x) = 4.",
                "x = 81",
                "Rewrite as x = 3^4. Since 3^4 = 81, x = 81.",
                equation_battle=True,
            ),
            ex(
                "solve shifted argument",
                "Solve log_2(x - 1) = 5.",
                "x = 33",
                "Rewrite as x - 1 = 2^5 = 32, so x = 33. The argument x - 1 is positive.",
            ),
            ex(
                "solve log equals zero",
                "Solve ln(2x + 4) = 0.",
                "x = -3/2",
                "Since ln(1) = 0, set 2x + 4 = 1. Then 2x = -3, so x = -3/2, which makes the argument positive.",
            ),
            ex(
                "one-to-one property",
                "Solve log_5(x + 7) = log_5(3x - 1).",
                "x = 4",
                "With matching bases, set arguments equal: x + 7 = 3x - 1. Then 8 = 2x, so x = 4. Both arguments are positive.",
                equation_battle=True,
            ),
            ex(
                "combine product logs",
                "Solve log_2(x) + log_2(3) = log_2(24).",
                "x = 8",
                "Combine the left side as log_2(3x). Then 3x = 24, so x = 8.",
            ),
            ex(
                "combine quotient logs",
                "Solve log_4(x) - log_4(2) = 3.",
                "x = 128",
                "Condense to log_4(x/2) = 3. Then x/2 = 4^3 = 64, so x = 128.",
            ),
            ex(
                "solve common log equation",
                "Solve log(x) = 2.",
                "x = 100",
                "Common log has base 10, so x = 10^2 = 100.",
            ),
            ex(
                "solve natural log equation",
                "Solve ln(x) = 3.",
                "x = e^3",
                "Natural log has base e, so ln(x) = 3 means x = e^3.",
            ),
            ex(
                "log equation with coefficient",
                "Solve 2log_3(x) = 4.",
                "x = 9",
                "Divide by 2 to get log_3(x) = 2. Then x = 3^2 = 9.",
                equation_battle=True,
            ),
            ex(
                "power property equation",
                "Solve log_2(x^2) = 6 for positive x.",
                "x = 8",
                "The equation means x^2 = 2^6 = 64. With positive x, x = 8.",
            ),
            ex(
                "extraneous solution check",
                "Solve log_3(x - 2) + log_3(x) = log_3(3).",
                "x = 3",
                "Condense to log_3(x(x - 2)) = log_3(3), so x^2 - 2x = 3. This gives x = 3 or x = -1. The value -1 is rejected because log_3(x) requires x > 0.",
                boss=True,
            ),
            ex(
                "equation with log on both sides",
                "Solve ln(5x - 4) = ln(x + 8).",
                "x = 3",
                "Matching natural logs allow 5x - 4 = x + 8. Then 4x = 12, so x = 3, and both arguments are positive.",
            ),
            ex(
                "solve after condensing quotient",
                "Solve log_5(x + 4) - log_5(x) = 1.",
                "x = 1",
                "Condense to log_5((x + 4)/x) = 1. Then (x + 4)/x = 5, so x + 4 = 5x and x = 1.",
                equation_battle=True,
            ),
            ex(
                "solve with base ten power",
                "Solve log(2x - 6) = 1.",
                "x = 8",
                "Rewrite as 2x - 6 = 10^1 = 10. Then 2x = 16 and x = 8.",
            ),
            ex(
                "solve with e and shift",
                "Solve ln(x + 2) = ln(7).",
                "x = 5",
                "The same log function appears on both sides, so x + 2 = 7. Thus x = 5.",
            ),
            ex(
                "error analysis domain check",
                "A player solves log_2(x - 3) = log_2(1 - x) and gets x = 2. What happens?",
                "There is no real solution",
                "Setting arguments equal gives x - 3 = 1 - x, so x = 2. But x = 2 makes x - 3 negative, so it is rejected.",
                boss=True,
            ),
            ex(
                "log equation producing quadratic",
                "Solve log_2(x) + log_2(x - 2) = 3.",
                "x = 4",
                "Condense to log_2(x(x - 2)) = 3, so x^2 - 2x = 8. Then x = 4 or x = -2; reject -2 because log arguments must be positive.",
                boss=True,
            ),
            ex(
                "approximate logarithmic solution",
                "Solve log_2(x) = 5.5 exactly in exponential form.",
                "x = 2^5.5",
                "Convert to exponential form: x = 2^5.5. This can also be written as 32sqrt(2).",
            ),
            ex(
                "solve with product property and coefficient",
                "Solve log_3(x) + log_3(x) = 4 for positive x.",
                "x = 9",
                "The left side is 2log_3(x), so log_3(x) = 2. Therefore x = 3^2 = 9.",
            ),
            ex(
                "mixed logarithmic equation",
                "Solve log_4(x - 1) + log_4(2) = log_4(10).",
                "x = 6",
                "Condense the left side as log_4(2(x - 1)). Then 2(x - 1) = 10, so x - 1 = 5 and x = 6.",
                boss=True,
            ),
        ],
        "next_topic": "Degree and radian measure",
    },
    {
        "id": 42,
        "topic": "Degree and radian measure",
        "subtopic": "Angle conversion, coterminal angles, arc length, and angular speed",
        "prerequisites": "Fractions, proportions, circle geometry, and basic function notation",
        "metadata_prereq": "fractions, proportions, circle_geometry, function_notation",
        "metadata_misconceptions": "pi_conversion_reversal, degree_radian_unit_loss, coterminal_sign_error, arc_length_uses_degrees",
        "review": [
            "A full circle is 360 degrees or 2pi radians.",
            "A half circle is 180 degrees or pi radians.",
            "To convert degrees to radians, multiply by pi/180.",
            "To convert radians to degrees, multiply by 180/pi.",
            "Arc length uses s = r theta when theta is measured in radians.",
        ],
        "concepts": [
            "Degrees and radians are two units for measuring the same angle rotation.",
            "Radians connect angle measure to arc length on a circle.",
            "Coterminal angles differ by full rotations of 360 degrees or 2pi radians.",
            "Positive angles rotate counterclockwise; negative angles rotate clockwise.",
            "Special angles often convert to simple multiples of pi.",
            "Angular speed can be measured in radians per unit time.",
        ],
        "misconceptions": [
            "Multiplying by 180/pi when converting degrees to radians.",
            "Leaving degree symbols on radian answers or pi on degree answers.",
            "Using s = r theta while theta is still in degrees.",
            "Adding 180 degrees instead of 360 degrees for coterminal angles.",
            "Treating pi radians as 90 degrees instead of 180 degrees.",
        ],
        "exercises": [
            ex(
                "convert degrees to radians",
                "Convert 60 degrees to radians.",
                "pi/3 radians",
                "Multiply by pi/180: 60(pi/180) = pi/3.",
            ),
            ex(
                "convert radians to degrees",
                "Convert 3pi/4 radians to degrees.",
                "135 degrees",
                "Multiply by 180/pi: (3pi/4)(180/pi) = 135 degrees.",
            ),
            ex(
                "negative degree conversion",
                "Convert -45 degrees to radians.",
                "-pi/4 radians",
                "Multiply by pi/180: -45(pi/180) = -pi/4.",
            ),
            ex(
                "negative radian conversion",
                "Convert -5pi/6 radians to degrees.",
                "-150 degrees",
                "Multiply by 180/pi: (-5pi/6)(180/pi) = -150 degrees.",
            ),
            ex(
                "full rotation equivalence",
                "How many radians are in 360 degrees?",
                "2pi radians",
                "A full circle is 360 degrees, which is the same rotation as 2pi radians.",
            ),
            ex(
                "coterminal degree angle",
                "Find a positive coterminal angle for -70 degrees.",
                "290 degrees",
                "Add 360 degrees to -70 degrees: -70 + 360 = 290 degrees.",
            ),
            ex(
                "coterminal radian angle",
                "Find a positive coterminal angle for -pi/3.",
                "5pi/3",
                "Add one full rotation of 2pi: -pi/3 + 2pi = -pi/3 + 6pi/3 = 5pi/3.",
            ),
            ex(
                "reduce angle to standard range",
                "Find the angle between 0 degrees and 360 degrees that is coterminal with 765 degrees.",
                "45 degrees",
                "Subtract 360 degrees twice: 765 - 360 - 360 = 45 degrees.",
            ),
            ex(
                "radian standard range",
                "Find the angle between 0 and 2pi that is coterminal with 17pi/6.",
                "5pi/6",
                "Subtract 2pi = 12pi/6 from 17pi/6 to get 5pi/6.",
            ),
            ex(
                "arc length with radians",
                "Find the arc length when r = 6 and theta = pi/3 radians.",
                "2pi",
                "Use s = r theta = 6(pi/3) = 2pi.",
            ),
            ex(
                "arc length after degree conversion",
                "Find the arc length for radius 10 and central angle 90 degrees.",
                "5pi",
                "Convert 90 degrees to pi/2 radians, then s = 10(pi/2) = 5pi.",
            ),
            ex(
                "central angle from arc length",
                "A circle has radius 8 and arc length 6. What is the central angle in radians?",
                "3/4 radians",
                "Use s = r theta. Then 6 = 8theta, so theta = 6/8 = 3/4 radians.",
                equation_battle=True,
            ),
            ex(
                "sector rotation direction",
                "Does -120 degrees rotate clockwise or counterclockwise from standard position?",
                "Clockwise",
                "Negative angles rotate clockwise from the positive x-axis.",
                visual=True,
            ),
            ex(
                "convert common special angle",
                "Convert 210 degrees to radians.",
                "7pi/6 radians",
                "Multiply by pi/180: 210pi/180 = 7pi/6.",
            ),
            ex(
                "convert unusual radian angle",
                "Convert 11pi/12 radians to degrees.",
                "165 degrees",
                "Multiply by 180/pi: (11pi/12)(180/pi) = 165 degrees.",
            ),
            ex(
                "angular speed",
                "A wheel turns through 10pi radians in 5 seconds. What is its angular speed?",
                "2pi radians per second",
                "Angular speed is angle divided by time: 10pi/5 = 2pi radians per second.",
            ),
            ex(
                "linear speed from angular speed",
                "A point 4 cm from the center rotates at pi/2 radians per second. What is its linear speed?",
                "2pi cm per second",
                "Linear speed is v = r omega = 4(pi/2) = 2pi cm per second.",
                boss=True,
            ),
            ex(
                "error analysis conversion",
                "A player converts 30 degrees to 30pi radians. What is the correct conversion?",
                "pi/6 radians",
                "Degrees to radians requires multiplying by pi/180: 30pi/180 = pi/6.",
                boss=True,
            ),
            ex(
                "coterminal angle in radians above range",
                "Find the angle between 0 and 2pi coterminal with 25pi/4.",
                "pi/4",
                "Subtract 2pi = 8pi/4 three times: 25pi/4 - 24pi/4 = pi/4.",
            ),
            ex(
                "mixed conversion and arc length",
                "A 135 degree central angle cuts an arc on a circle of radius 12. Find the arc length.",
                "9pi",
                "Convert 135 degrees to 3pi/4 radians. Then s = 12(3pi/4) = 9pi.",
                boss=True,
            ),
        ],
        "next_topic": "Reference angles",
    },
    {
        "id": 43,
        "topic": "Reference angles",
        "subtopic": "Reference angles in degrees and radians across all quadrants",
        "prerequisites": "Degree and radian measure, coordinate planes, quadrants, and coterminal angles",
        "metadata_prereq": "degree_radian_measure, coordinate_planes, quadrants, coterminal_angles",
        "metadata_misconceptions": "quadrant_reference_rule_mixup, negative_angle_range, reference_angle_not_positive, coterminal_before_reference",
        "review": [
            "A reference angle is always positive and acute, except for quadrantal angles where it is 0.",
            "Quadrant I angles have reference angle equal to the angle.",
            "Quadrant II reference angle is 180 degrees minus the angle.",
            "Quadrant III reference angle is the angle minus 180 degrees.",
            "Quadrant IV reference angle is 360 degrees minus the angle.",
        ],
        "concepts": [
            "Reference angles measure the acute angle from the terminal side to the x-axis.",
            "For radian angles, use pi, 2pi, and their fractions the same way as 180 degrees and 360 degrees.",
            "Negative or large angles should be made coterminal in the standard range before finding the reference angle.",
            "Reference angles help transfer exact trig values across quadrants.",
            "The reference angle is positive even when the original angle is negative.",
            "Quadrantal angles land on an axis and have reference angle 0.",
        ],
        "misconceptions": [
            "Returning the original obtuse angle as the reference angle.",
            "Keeping a negative reference angle for a negative rotation.",
            "Using 90 degrees as the reference line instead of the x-axis.",
            "Forgetting to reduce angles larger than 360 degrees.",
            "Confusing the reference angle with the coterminal angle.",
        ],
        "exercises": [
            ex(
                "reference angle in quadrant I",
                "Find the reference angle for 35 degrees.",
                "35 degrees",
                "The angle is already in Quadrant I, so its reference angle is 35 degrees.",
            ),
            ex(
                "reference angle in quadrant II",
                "Find the reference angle for 140 degrees.",
                "40 degrees",
                "Quadrant II reference angle is 180 degrees minus the angle: 180 - 140 = 40 degrees.",
            ),
            ex(
                "reference angle in quadrant III",
                "Find the reference angle for 225 degrees.",
                "45 degrees",
                "Quadrant III reference angle is angle minus 180 degrees: 225 - 180 = 45 degrees.",
            ),
            ex(
                "reference angle in quadrant IV",
                "Find the reference angle for 315 degrees.",
                "45 degrees",
                "Quadrant IV reference angle is 360 degrees minus the angle: 360 - 315 = 45 degrees.",
            ),
            ex(
                "negative angle reference",
                "Find the reference angle for -30 degrees.",
                "30 degrees",
                "-30 degrees is coterminal with 330 degrees. The Quadrant IV reference angle is 360 - 330 = 30 degrees.",
            ),
            ex(
                "angle above 360 degrees",
                "Find the reference angle for 405 degrees.",
                "45 degrees",
                "Subtract 360 degrees to get the coterminal angle 45 degrees, which is in Quadrant I.",
            ),
            ex(
                "quadrantal angle",
                "Find the reference angle for 180 degrees.",
                "0 degrees",
                "The terminal side lies on the x-axis, so the angle to the x-axis is 0 degrees.",
            ),
            ex(
                "radian quadrant I",
                "Find the reference angle for pi/6.",
                "pi/6",
                "The angle pi/6 is in Quadrant I, so its reference angle is pi/6.",
            ),
            ex(
                "radian quadrant II",
                "Find the reference angle for 5pi/6.",
                "pi/6",
                "In Quadrant II, subtract from pi: pi - 5pi/6 = pi/6.",
            ),
            ex(
                "radian quadrant III",
                "Find the reference angle for 4pi/3.",
                "pi/3",
                "In Quadrant III, subtract pi: 4pi/3 - pi = pi/3.",
            ),
            ex(
                "radian quadrant IV",
                "Find the reference angle for 7pi/4.",
                "pi/4",
                "In Quadrant IV, subtract from 2pi: 2pi - 7pi/4 = pi/4.",
            ),
            ex(
                "negative radian reference",
                "Find the reference angle for -2pi/3.",
                "pi/3",
                "Add 2pi to get 4pi/3. Its Quadrant III reference angle is 4pi/3 - pi = pi/3.",
            ),
            ex(
                "large radian reference",
                "Find the reference angle for 13pi/6.",
                "pi/6",
                "Subtract 2pi = 12pi/6 to get pi/6, so the reference angle is pi/6.",
            ),
            ex(
                "determine quadrant and reference angle",
                "For 250 degrees, give the quadrant and reference angle.",
                "Quadrant III; reference angle 70 degrees",
                "Since 250 degrees is between 180 and 270, it is in Quadrant III. The reference angle is 250 - 180 = 70 degrees.",
                visual=True,
            ),
            ex(
                "determine radian quadrant and reference",
                "For 11pi/6, give the quadrant and reference angle.",
                "Quadrant IV; reference angle pi/6",
                "11pi/6 is between 3pi/2 and 2pi, so it is in Quadrant IV. The reference angle is 2pi - 11pi/6 = pi/6.",
                visual=True,
            ),
            ex(
                "build angles from reference angle",
                "List the angles between 0 degrees and 360 degrees with reference angle 30 degrees.",
                "30 degrees, 150 degrees, 210 degrees, 330 degrees",
                "Place a 30 degree acute angle in each quadrant relative to the x-axis.",
                reverse_variant="Give a reference angle and ask for all standard-position angles in one full rotation.",
            ),
            ex(
                "build radian angles from reference angle",
                "List the angles between 0 and 2pi with reference angle pi/4.",
                "pi/4, 3pi/4, 5pi/4, 7pi/4",
                "Use pi/4 from the x-axis in each quadrant.",
                reverse_variant="Give a radian reference angle and ask for all matching angles in one rotation.",
            ),
            ex(
                "error analysis negative reference",
                "A player says the reference angle for -150 degrees is -30 degrees. What is the correct reference angle?",
                "30 degrees",
                "-150 degrees is coterminal with 210 degrees. In Quadrant III, the reference angle is 210 - 180 = 30 degrees, and reference angles are positive.",
                boss=True,
            ),
            ex(
                "axis angle in radians",
                "Find the reference angle for 3pi/2.",
                "0",
                "The angle 3pi/2 lies on the negative y-axis. A quadrantal angle has reference angle 0.",
            ),
            ex(
                "mixed coterminal reference challenge",
                "Find the reference angle for -17pi/6.",
                "pi/6",
                "Add 2pi twice: -17pi/6 + 24pi/6 = 7pi/6. In Quadrant III, the reference angle is 7pi/6 - pi = pi/6.",
                boss=True,
            ),
        ],
        "next_topic": "Unit circle",
    },
    {
        "id": 44,
        "topic": "Unit circle",
        "subtopic": "Coordinates, exact trigonometric values, and angle locations on the unit circle",
        "prerequisites": "Reference angles, degree and radian measure, coordinate planes, and special right triangles",
        "metadata_prereq": "reference_angles, degree_radian_measure, coordinate_planes, special_right_triangles",
        "metadata_misconceptions": "coordinate_order_swap, sign_quadrant_error, tangent_denominator_zero, radians_degrees_mismatch",
        "review": [
            "On the unit circle, a point has coordinates (cos theta, sin theta).",
            "Quadrants determine the signs of sine and cosine.",
            "The special reference angles are 30 degrees, 45 degrees, and 60 degrees, or pi/6, pi/4, and pi/3.",
            "Tangent equals sin theta divided by cos theta when cos theta is not zero.",
            "Coterminal angles share the same unit-circle point.",
        ],
        "concepts": [
            "The unit circle has radius 1 and center at the origin.",
            "Cosine is the x-coordinate and sine is the y-coordinate.",
            "Reference angles give the absolute values of special trig coordinates.",
            "Quadrant signs turn reference values into exact unit-circle values.",
            "Quadrantal angles have coordinates on the axes.",
            "Solving simple trig equations on 0 to 2pi means finding all matching unit-circle angles.",
        ],
        "misconceptions": [
            "Swapping sine and cosine coordinates.",
            "Using the right reference values but the wrong quadrant signs.",
            "Giving only one angle when two unit-circle angles have the same sine or cosine.",
            "Treating tangent as defined when cosine is zero.",
            "Mixing degree and radian labels in the same answer.",
        ],
        "exercises": [
            ex(
                "coordinate at zero",
                "What point on the unit circle corresponds to theta = 0?",
                "(1, 0)",
                "At angle 0, the terminal side points along the positive x-axis, so the point is (1, 0).",
                visual=True,
            ),
            ex(
                "coordinate at pi over six",
                "Give the unit-circle coordinates for theta = pi/6.",
                "(sqrt(3)/2, 1/2)",
                "The reference angle is 30 degrees in Quadrant I, so cosine is sqrt(3)/2 and sine is 1/2.",
            ),
            ex(
                "coordinate at pi over four",
                "Give the unit-circle coordinates for theta = pi/4.",
                "(sqrt(2)/2, sqrt(2)/2)",
                "A 45 degree reference angle has equal positive coordinates on the unit circle.",
            ),
            ex(
                "coordinate at pi over three",
                "Give the unit-circle coordinates for theta = pi/3.",
                "(1/2, sqrt(3)/2)",
                "The reference angle is 60 degrees in Quadrant I, so cosine is 1/2 and sine is sqrt(3)/2.",
            ),
            ex(
                "quadrant II coordinate",
                "Give the unit-circle coordinates for theta = 2pi/3.",
                "(-1/2, sqrt(3)/2)",
                "The reference angle is pi/3. In Quadrant II, cosine is negative and sine is positive.",
            ),
            ex(
                "quadrant III coordinate",
                "Give the unit-circle coordinates for theta = 5pi/4.",
                "(-sqrt(2)/2, -sqrt(2)/2)",
                "The reference angle is pi/4. In Quadrant III, both cosine and sine are negative.",
            ),
            ex(
                "quadrant IV coordinate",
                "Give the unit-circle coordinates for theta = 11pi/6.",
                "(sqrt(3)/2, -1/2)",
                "The reference angle is pi/6. In Quadrant IV, cosine is positive and sine is negative.",
            ),
            ex(
                "find sine from coordinate",
                "If the unit-circle point is (1/2, sqrt(3)/2), what is sin theta?",
                "sqrt(3)/2",
                "On the unit circle, sine is the y-coordinate.",
            ),
            ex(
                "find cosine from coordinate",
                "If the unit-circle point is (-sqrt(3)/2, 1/2), what is cos theta?",
                "-sqrt(3)/2",
                "On the unit circle, cosine is the x-coordinate.",
            ),
            ex(
                "tangent value",
                "Find tan(pi/4).",
                "1",
                "At pi/4, sine and cosine are both sqrt(2)/2, so tan(pi/4) = (sqrt(2)/2)/(sqrt(2)/2) = 1.",
            ),
            ex(
                "tangent undefined",
                "Find tan(pi/2).",
                "Undefined",
                "At pi/2, the unit-circle point is (0, 1). Tangent is sin/cos, and division by 0 is undefined.",
            ),
            ex(
                "quadrantal sine and cosine",
                "Find cos(pi) and sin(pi).",
                "cos(pi) = -1; sin(pi) = 0",
                "At pi radians, the terminal side points to (-1, 0) on the unit circle.",
            ),
            ex(
                "angle from point",
                "Which angle between 0 and 2pi has unit-circle point (0, -1)?",
                "3pi/2",
                "The point (0, -1) lies on the negative y-axis, which corresponds to 3pi/2.",
                visual=True,
            ),
            ex(
                "all angles with given sine",
                "Find all theta in [0, 2pi) with sin theta = 1/2.",
                "theta = pi/6 and 5pi/6",
                "Sine is positive in Quadrants I and II, and the reference angle for 1/2 is pi/6.",
                equation_battle=True,
            ),
            ex(
                "all angles with given cosine",
                "Find all theta in [0, 2pi) with cos theta = -sqrt(2)/2.",
                "theta = 3pi/4 and 5pi/4",
                "Cosine is negative in Quadrants II and III, and the reference angle is pi/4.",
                equation_battle=True,
            ),
            ex(
                "coterminal unit-circle value",
                "Find sin(13pi/6).",
                "1/2",
                "Subtract 2pi to get pi/6. Coterminal angles have the same sine, and sin(pi/6) = 1/2.",
            ),
            ex(
                "degree angle unit-circle coordinate",
                "Give the unit-circle coordinates for 300 degrees.",
                "(1/2, -sqrt(3)/2)",
                "The reference angle is 60 degrees. In Quadrant IV, cosine is positive and sine is negative.",
                visual=True,
            ),
            ex(
                "error analysis coordinate order",
                "A player says the point for pi/6 is (1/2, sqrt(3)/2). What is the correct point?",
                "(sqrt(3)/2, 1/2)",
                "The point is (cos theta, sin theta). For pi/6, cosine is sqrt(3)/2 and sine is 1/2.",
                boss=True,
            ),
            ex(
                "use identity to find missing coordinate",
                "A Quadrant II unit-circle point has y-coordinate 3/5. What is its x-coordinate?",
                "-4/5",
                "On the unit circle, x^2 + y^2 = 1. With y = 3/5, x^2 = 1 - 9/25 = 16/25, so x = -4/5 in Quadrant II.",
                boss=True,
            ),
            ex(
                "mixed unit-circle challenge",
                "Find cos(7pi/6), sin(7pi/6), and tan(7pi/6).",
                "cos(7pi/6) = -sqrt(3)/2; sin(7pi/6) = -1/2; tan(7pi/6) = sqrt(3)/3",
                "The reference angle is pi/6 and the angle is in Quadrant III, so sine and cosine are both negative. Tangent is (-1/2)/(-sqrt(3)/2) = 1/sqrt(3) = sqrt(3)/3.",
                boss=True,
            ),
        ],
        "next_topic": "Exact trigonometric values",
    },
]


if __name__ == "__main__":
    generate_batch(PHASES)
