def ex(focus, question, answer, explanation, **extra):
    item = {
        "focus": focus,
        "question": question,
        "answer": answer,
        "explanation": explanation,
    }
    item.update(extra)
    return item


PHASES = [
    {
        "id": 21,
        "topic": "Piecewise functions",
        "subtopic": "Evaluating, graphing, interpreting, and building piecewise-defined functions",
        "prerequisites": "function notation, inequalities, graph reading, domain intervals, linear equations",
        "metadata_prereq": "function notation, inequalities, domain intervals, graph reading",
        "metadata_misconceptions": "wrong interval branch, endpoint inclusion error, substituting into every branch, graph discontinuity confusion",
        "review": [
            "A piecewise function uses different formulas on different parts of the domain.",
            "The input value decides which branch applies.",
            "Closed endpoints are included; open endpoints are not included.",
            "Function notation still means replace the input after choosing the correct branch.",
            "A graph can jump, connect, or have holes at piecewise boundaries.",
        ],
        "concepts": [
            "Choose the branch by checking the input against the condition first.",
            "Only evaluate the formula from the branch that contains the input.",
            "At a boundary, endpoint symbols decide which formula gives the function value.",
            "Piecewise graphs are built one interval at a time.",
            "Continuity at a join requires matching output values from both sides.",
            "Context piecewise models often represent tiered prices, rates, or rules.",
        ],
        "misconceptions": [
            "Evaluating every branch and choosing the nicest answer.",
            "Ignoring whether an endpoint uses < or <=.",
            "Using the y-value to choose a branch instead of the x-value.",
            "Assuming a jump graph cannot still be a function.",
            "Forgetting to restrict each graph segment to its interval.",
        ],
        "next_topic": "Quadratic factoring",
        "exercises": [
            ex("Basic branch selection", "For f(x) = {2x+1 if x < 3; x^2 if x >= 3}, find f(2).", "5", "Because 2 < 3, use 2x+1. Then f(2)=2(2)+1=5.", type="Evaluation"),
            ex("Endpoint inclusion", "For f(x) = {x+4 if x < 1; 3x if x >= 1}, find f(1).", "3", "The condition x >= 1 includes 1, so use 3x. Thus f(1)=3.", type="Evaluation"),
            ex("Negative input branch", "For g(x) = {-x if x < 0; x+5 if x >= 0}, find g(-6).", "6", "Since -6 < 0, use -x. Then g(-6)=-(-6)=6."),
            ex("Evaluate at zero", "For h(x) = {4 if x = 0; x^2+1 if x != 0}, find h(0).", "4", "The special branch x=0 applies, so h(0)=4."),
            ex("Multiple intervals", "For p(x) = {x+2 if x < -1; 5 if -1 <= x < 4; 2x-3 if x >= 4}, find p(3).", "5", "The input 3 is in -1 <= x < 4, so the constant branch gives p(3)=5."),
            ex("Right boundary", "For p(x) = {x+2 if x < -1; 5 if -1 <= x < 4; 2x-3 if x >= 4}, find p(4).", "5", "The input 4 belongs to x >= 4, so p(4)=2(4)-3=5."),
            ex("Table from piecewise rule", "For f(x) = {x^2 if x < 2; x+3 if x >= 2}, make the outputs for x=1,2,3.", "1, 5, 6", "Use x^2 for 1 to get 1. Use x+3 for 2 and 3 to get 5 and 6."),
            ex("Graph endpoint choice", "A graph has y=x+1 for x<2 with an open circle at (2,3), and y=5 for x>=2 with a closed circle at (2,5). What is f(2)?", "5", "The closed point gives the actual function value at x=2.", visual=True),
            ex("Domain of piecewise rule", "What is the domain of f(x) = {x+1 if x<0; x^2 if 0<=x<=3; 7 if x>3}?", "all real numbers", "The three conditions cover x<0, 0<=x<=3, and x>3 with no gap."),
            ex("Range from simple pieces", "Find the range of f(x) = {2 if x<0; x+1 if 0<=x<=2}.", "{2} union [1,3]", "The first branch gives y=2. The second branch runs from 1 to 3, so the combined range is {2} union [1,3], which simplifies to [1,3]."),
            ex("Continuity check", "Is f(x) = {x+2 if x<1; 3x if x>=1} continuous at x=1?", "yes", "The left rule approaches 1+2=3, and the included right value is 3(1)=3, so the pieces meet."),
            ex("Jump discontinuity", "Is f(x) = {2x if x<1; x+4 if x>=1} continuous at x=1?", "no", "The left side approaches 2, while the function value from the right branch is 5."),
            ex("Solve within a branch", "For f(x) = {x+4 if x<2; 2x-1 if x>=2}, solve f(x)=7.", "x=4", "The first branch would give x=3, but x=3 is not less than 2. The second branch gives 2x-1=7, so x=4, which is valid."),
            ex("Absolute value as piecewise", "Write |x-3| as a piecewise function.", "{3-x if x<3; x-3 if x>=3}", "When x<3, x-3 is negative so the absolute value is 3-x. When x>=3, it is x-3."),
            ex("Context tiered pricing", "A parking garage charges $5 for the first hour and $3 per additional hour. Write the cost for h hours when 0<h<=3.", "C(h) = {5 if 0<h<=1; 5+3(h-1) if 1<h<=3}", "The first hour has a flat cost of 5. After 1 hour, add 3 dollars for each extra hour."),
            ex("Build from graph description", "A function is -2 for x<0, equals x for 0<=x<4, and equals 6 for x>=4. Write f(x).", "f(x) = {-2 if x<0; x if 0<=x<4; 6 if x>=4}", "Translate each described segment into a formula and condition."),
            ex("Parameter for continuity", "Find a so f(x) = {2x+a if x<3; x^2 if x>=3} is continuous at x=3.", "a=3", "Continuity needs 2(3)+a=3^2. Thus 6+a=9, so a=3."),
            ex("Parameter from function value", "For f(x) = {ax+1 if x<2; 9 if x>=2}, find a if f(1)=6.", "a=5", "Since 1<2, use ax+1. Then a(1)+1=6, so a=5."),
            ex("Piecewise composition", "Let f(x) = {x+1 if x<0; 2x if x>=0}. Find f(f(-2)).", "-1", "First f(-2)=-1 because -2<0. Then f(-1)=0 because -1<0.", boss=True),
            ex("Boss mixed evaluation", "For f(x) = {x^2-1 if x<-1; 4 if -1<=x<2; 3x-2 if x>=2}, find f(-2)+f(-1)+f(2).", "11", "f(-2)=3, f(-1)=4, and f(2)=4. The sum is 3+4+4=11.", boss=True),
        ],
    },
    {
        "id": 22,
        "topic": "Quadratic factoring",
        "subtopic": "Factoring quadratic expressions and solving quadratic equations by factoring",
        "prerequisites": "distributive property, integer factors, zero product property, simplifying expressions",
        "metadata_prereq": "integer arithmetic, distributive property, linear solving, polynomial terms",
        "metadata_misconceptions": "wrong factor pair, missing greatest common factor, sign pair error, forgetting zero product property",
        "review": [
            "A quadratic in standard form has terms ax^2+bx+c.",
            "Factoring rewrites a sum as a product.",
            "The zero product property says if AB=0, then A=0 or B=0.",
            "A greatest common factor should be removed before trinomial factoring.",
            "Factoring can reveal x-intercepts of a quadratic graph.",
        ],
        "concepts": [
            "For x^2+bx+c, find two numbers that multiply to c and add to b.",
            "For x^2-bx+c, both factor signs may be negative.",
            "If c is negative, the factor signs are opposite.",
            "For ax^2+bx+c, use grouping or another reliable factoring method.",
            "After factoring an equation equal to zero, set each factor equal to zero.",
            "Not every quadratic factors over integers.",
        ],
        "misconceptions": [
            "Factoring only the first and last terms.",
            "Using numbers that add to c instead of multiply to c.",
            "Solving factors before the equation equals zero.",
            "Dropping a negative sign during grouping.",
            "Assuming every quadratic has integer factors.",
        ],
        "next_topic": "Completing the square",
        "equation_battle": True,
        "exercises": [
            ex("Factor x^2+bx+c positive", "Factor x^2+7x+12.", "(x+3)(x+4)", "The numbers 3 and 4 multiply to 12 and add to 7."),
            ex("Factor with negative middle", "Factor x^2-9x+20.", "(x-4)(x-5)", "The numbers -4 and -5 multiply to 20 and add to -9."),
            ex("Factor with negative constant", "Factor x^2+x-12.", "(x+4)(x-3)", "The numbers 4 and -3 multiply to -12 and add to 1."),
            ex("Perfect square trinomial", "Factor x^2+10x+25.", "(x+5)^2", "Both factors are x+5 because 5 and 5 multiply to 25 and add to 10."),
            ex("Difference of squares", "Factor x^2-49.", "(x-7)(x+7)", "This is a^2-b^2 with a=x and b=7."),
            ex("Greatest common factor first", "Factor 3x^2+12x.", "3x(x+4)", "Both terms share 3x, leaving x+4."),
            ex("GCF then trinomial", "Factor 2x^2+10x+12 completely.", "2(x+2)(x+3)", "First factor 2 to get 2(x^2+5x+6), then x^2+5x+6=(x+2)(x+3)."),
            ex("Leading coefficient greater than 1", "Factor 2x^2+7x+3.", "(2x+1)(x+3)", "The product gives 2x^2+6x+x+3=2x^2+7x+3."),
            ex("Leading coefficient and negative constant", "Factor 3x^2+5x-2.", "(3x-1)(x+2)", "The product gives 3x^2+6x-x-2=3x^2+5x-2."),
            ex("Grouping method", "Factor 6x^2+11x+3.", "(3x+1)(2x+3)", "Split 11x as 9x+2x, group, and factor to get (3x+1)(2x+3)."),
            ex("Solve by factoring simple", "Solve x^2+5x+6=0.", "x=-2 or x=-3", "Factor as (x+2)(x+3)=0, so x=-2 or x=-3."),
            ex("Solve with negative constant", "Solve x^2-4x-21=0.", "x=7 or x=-3", "Factor as (x-7)(x+3)=0."),
            ex("Solve with leading coefficient", "Solve 2x^2-5x-3=0.", "x=3 or x=-1/2", "Factor as (2x+1)(x-3)=0."),
            ex("Equation not yet zero", "Solve x^2+3x=10 by factoring.", "x=2 or x=-5", "Move 10 left to get x^2+3x-10=0, then factor as (x+5)(x-2)=0."),
            ex("Find zeros from factored form", "What are the zeros of y=(x-4)(x+6)?", "x=4 and x=-6", "Set each factor equal to zero."),
            ex("Build quadratic from roots", "Write a monic quadratic with roots -2 and 5.", "x^2-3x-10", "The factors are (x+2)(x-5). Multiplying gives x^2-3x-10."),
            ex("Identify nonfactorable over integers", "Does x^2+x+1 factor over the integers?", "no", "No integer pair multiplies to 1 and adds to 1."),
            ex("Area model factoring", "A rectangle has area x^2+8x+15. What binomial side lengths fit?", "x+3 and x+5", "The factors of the area expression are (x+3)(x+5).", visual=True),
            ex("Error analysis signs", "A student factors x^2-2x-15 as (x-3)(x-5). What is wrong?", "The signs do not multiply to -15; the correct factorization is (x-5)(x+3).", "The factors must multiply to -15 and add to -2."),
            ex("Boss mixed factoring", "Solve 4x^2-25=0 and state the factors used.", "x=5/2 or x=-5/2; factors (2x-5)(2x+5)", "Use difference of squares: 4x^2-25=(2x)^2-5^2.", boss=True),
        ],
    },
    {
        "id": 23,
        "topic": "Completing the square",
        "subtopic": "Rewriting quadratics in vertex form and solving by completing the square",
        "prerequisites": "quadratic expressions, factoring perfect squares, square roots, equation balancing",
        "metadata_prereq": "perfect square trinomials, square roots, linear solving, quadratic standard form",
        "metadata_misconceptions": "forgetting half of b squared, adding to one side only, sign error in vertex form, mishandling leading coefficient",
        "review": [
            "A perfect square trinomial has the form x^2+2kx+k^2.",
            "Half of the x-coefficient, squared, completes x^2+bx.",
            "Equations stay balanced only when the same value is added to both sides.",
            "Vertex form is a(x-h)^2+k.",
            "Square roots produce positive and negative solutions when solving equations.",
        ],
        "concepts": [
            "Complete the square by adding (b/2)^2 to x^2+bx.",
            "A completed square reveals the vertex of a parabola.",
            "For equations, move constants first, complete the square, then take square roots.",
            "When a is not 1, factor a from the quadratic and linear terms first.",
            "Completing the square works even when a quadratic is not factorable.",
            "The process connects algebraic form to graph features.",
        ],
        "misconceptions": [
            "Squaring b instead of half of b.",
            "Adding a value inside an equation without balancing the other side.",
            "Taking only the positive square root.",
            "Forgetting to factor the leading coefficient before completing the square.",
            "Reading the vertex sign backward in (x-h)^2+k.",
        ],
        "next_topic": "Quadratic formula",
        "equation_battle": True,
        "exercises": [
            ex("Find completing value positive b", "What number completes the square for x^2+8x?", "16", "Half of 8 is 4, and 4^2=16."),
            ex("Find completing value negative b", "What number completes the square for x^2-6x?", "9", "Half of -6 is -3, and (-3)^2=9."),
            ex("Rewrite as square", "Rewrite x^2+10x+25 as a squared binomial.", "(x+5)^2", "Half of 10 is 5, so the trinomial is (x+5)^2."),
            ex("Complete expression", "Complete the square: x^2+4x+7.", "(x+2)^2+3", "Add and subtract 4: x^2+4x+4+3=(x+2)^2+3."),
            ex("Vertex form a=1", "Write y=x^2-12x+40 in vertex form.", "y=(x-6)^2+4", "Half of -12 is -6; add and subtract 36 to get (x-6)^2+4."),
            ex("Read vertex", "What is the vertex of y=(x+3)^2-8?", "(-3,-8)", "Vertex form y=(x-h)^2+k has vertex (h,k), so h=-3 and k=-8."),
            ex("Solve simple complete square", "Solve x^2+6x+5=0 by completing the square.", "x=-1 or x=-5", "Move 5: x^2+6x=-5. Add 9: (x+3)^2=4, so x+3=+-2."),
            ex("Solve nonfactorable", "Solve x^2+4x-1=0 by completing the square.", "x=-2+-sqrt(5)", "Move -1 to the right: x^2+4x=1. Add 4: (x+2)^2=5."),
            ex("Fractional completing value", "What number completes the square for x^2+5x?", "25/4", "Half of 5 is 5/2, and (5/2)^2=25/4."),
            ex("Fraction solution", "Solve x^2+5x+1=0 by completing the square.", "x=(-5+-sqrt(21))/2", "x^2+5x=-1. Add 25/4 to get (x+5/2)^2=21/4."),
            ex("Leading coefficient factor", "Write y=2x^2+8x+3 in vertex form.", "y=2(x+2)^2-5", "Factor 2 from the first two terms: 2(x^2+4x)+3. Complete inside with 4 to get 2(x+2)^2-8+3."),
            ex("Leading coefficient negative", "Write y=-x^2+6x-2 in vertex form.", "y=-(x-3)^2+7", "Factor -1 from the quadratic terms: -(x^2-6x)-2. Complete to get -(x-3)^2+9-2."),
            ex("Max or min from vertex", "Does y=3(x-1)^2+5 have a minimum or maximum, and what is its value?", "minimum value 5", "The coefficient 3 is positive, so the parabola opens up and the vertex y-value is the minimum."),
            ex("Vertex from standard form", "Find the vertex of y=x^2+2x-8 by completing the square.", "(-1,-9)", "x^2+2x-8=(x+1)^2-9."),
            ex("Solve with leading coefficient", "Solve 2x^2+8x+1=0 by completing the square.", "x=-2+-sqrt(14)/2", "Divide by 2: x^2+4x+1/2=0. Then (x+2)^2=7/2, so x=-2+-sqrt(14)/2."),
            ex("Derive quadratic formula step", "After completing the square on ax^2+bx+c=0, what squared expression appears?", "(x+b/(2a))^2", "Divide by a, move c/a, and add (b/(2a))^2 to form the square."),
            ex("Error analysis balance", "A student changes x^2+8x=3 into (x+4)^2=3. What is missing?", "They added 16 to the left but not the right; it should be (x+4)^2=19.", "Completing the square must keep the equation balanced."),
            ex("Convert vertex to standard", "Expand y=(x-4)^2+6 into standard form.", "y=x^2-8x+22", "Expand x^2-8x+16 and add 6."),
            ex("Context vertex", "A ball has height h(t)=-16(t-2)^2+80. What is its maximum height?", "80", "The coefficient is negative, so the vertex gives the maximum height of 80."),
            ex("Boss complete square", "Write y=-2x^2+12x-11 in vertex form and give the vertex.", "y=-2(x-3)^2+7; vertex (3,7)", "Factor -2, complete x^2-6x to (x-3)^2, and simplify.", boss=True),
        ],
    },
    {
        "id": 24,
        "topic": "Quadratic formula",
        "subtopic": "Solving quadratic equations with the quadratic formula and interpreting exact solutions",
        "prerequisites": "standard form quadratics, square roots, simplifying radicals, discriminant basics",
        "metadata_prereq": "standard form, coefficients, radicals, arithmetic with negatives",
        "metadata_misconceptions": "wrong coefficient substitution, sign error with negative b, forgetting denominator 2a, radical simplification error",
        "review": [
            "A quadratic equation in standard form is ax^2+bx+c=0.",
            "The quadratic formula is x=(-b+-sqrt(b^2-4ac))/(2a).",
            "The values a, b, and c come from standard form.",
            "The expression b^2-4ac is the discriminant.",
            "Exact radical answers are often preferred over decimals.",
        ],
        "concepts": [
            "Use the quadratic formula when factoring is hard or impossible.",
            "Move all terms to one side before identifying a, b, and c.",
            "Substitute coefficients carefully, especially when b or c is negative.",
            "Simplify the discriminant before simplifying the final radical.",
            "The denominator is the whole quantity 2a.",
            "Check solutions by substitution when possible.",
        ],
        "misconceptions": [
            "Using b instead of -b in the numerator.",
            "Forgetting that b^2 is positive even when b is negative.",
            "Leaving the equation outside standard form before reading coefficients.",
            "Dividing only the radical by 2a instead of the entire numerator.",
            "Rounding too early when exact form is requested.",
        ],
        "next_topic": "Discriminant",
        "equation_battle": True,
        "exercises": [
            ex("Identify coefficients", "For 3x^2-5x+2=0, identify a, b, and c.", "a=3, b=-5, c=2", "Read directly from ax^2+bx+c=0."),
            ex("Simple formula factoring match", "Solve x^2-5x+6=0 using the quadratic formula.", "x=2 or x=3", "Here a=1,b=-5,c=6. The formula gives (5+-sqrt(25-24))/2=(5+-1)/2."),
            ex("Negative b substitution", "Solve x^2+4x-5=0 using the quadratic formula.", "x=1 or x=-5", "a=1,b=4,c=-5. The formula gives (-4+-sqrt(16+20))/2=(-4+-6)/2."),
            ex("Leading coefficient", "Solve 2x^2+3x-2=0.", "x=1/2 or x=-2", "a=2,b=3,c=-2. The discriminant is 25, so x=(-3+-5)/4."),
            ex("No integer roots exact", "Solve x^2+2x-2=0.", "x=-1+-sqrt(3)", "The formula gives (-2+-sqrt(4+8))/2=(-2+-2sqrt(3))/2."),
            ex("Simplify radical", "Solve x^2-6x+1=0.", "x=3+-2sqrt(2)", "The discriminant is 36-4=32, so x=(6+-4sqrt(2))/2=3+-2sqrt(2)."),
            ex("Equation not standard", "Solve x^2=3x+10 using the quadratic formula.", "x=5 or x=-2", "Rewrite as x^2-3x-10=0. Then x=(3+-sqrt(49))/2."),
            ex("Missing b term", "Solve 4x^2-9=0 using the quadratic formula.", "x=3/2 or x=-3/2", "Here a=4,b=0,c=-9. The formula gives x=+-sqrt(144)/8=+-3/2."),
            ex("Missing c term", "Solve 5x^2-20x=0 using the quadratic formula.", "x=0 or x=4", "a=5,b=-20,c=0. The formula gives (20+-20)/10."),
            ex("One repeated root", "Solve x^2-8x+16=0 using the quadratic formula.", "x=4", "The discriminant is 64-64=0, so there is one repeated solution x=8/2=4."),
            ex("Two irrational roots", "Solve 3x^2-2x-1=0.", "x=1 or x=-1/3", "The discriminant is 4+12=16, so x=(2+-4)/6."),
            ex("Exact radical with a>1", "Solve 2x^2+4x-3=0.", "x=(-2+-sqrt(10))/2", "The formula gives (-4+-sqrt(16+24))/4=(-4+-2sqrt(10))/4."),
            ex("Decimal approximation", "Solve x^2+x-1=0 to the nearest hundredth.", "x=0.62 or x=-1.62", "Exact solutions are (-1+-sqrt(5))/2, approximately 0.62 and -1.62."),
            ex("Check a candidate", "Is x=2 a solution of 3x^2-7x+2=0?", "yes", "Substitute: 3(4)-14+2=0."),
            ex("Formula setup only", "Set up the quadratic formula for 5x^2+x-4=0 without simplifying.", "x=(-1+-sqrt(1-4(5)(-4)))/(10)", "Use a=5,b=1,c=-4 in x=(-b+-sqrt(b^2-4ac))/(2a)."),
            ex("Error analysis denominator", "A student solves 2x^2+3x-2=0 and writes x=(-3+-5)/2. What is wrong?", "The denominator should be 2a=4, not 2.", "Since a=2, the full denominator is 2a=4."),
            ex("Error analysis negative b", "For x^2-6x+8=0, a student uses -6+-sqrt(36-32) over 2. What is wrong?", "They used b instead of -b; the numerator should start with 6.", "When b=-6, -b=6."),
            ex("Context quadratic roots", "A height model is h(t)=-16t^2+32t+48. When is h(t)=0?", "t=3 seconds or t=-1 second; physical time is 3 seconds", "Use the formula on -16t^2+32t+48=0; the negative time is rejected in context."),
            ex("Choose method", "Why might the quadratic formula be better than factoring for x^2+4x+1=0?", "It does not factor over integers and the formula gives x=-2+-sqrt(3).", "Factoring over integers fails, but the formula always works for quadratics."),
            ex("Boss exact roots", "Solve 6x^2-7x-3=0 exactly.", "x=3/2 or x=-1/3", "The discriminant is 49+72=121. Then x=(7+-11)/12.", boss=True),
        ],
    },
]
