from tools.phase_batch_021_024 import ex


COMMON = {
    "quadratic": {
        "review": [
            "A quadratic graph is a parabola.",
            "Vertex form y=a(x-h)^2+k shows vertex (h,k).",
            "Factored form y=a(x-r1)(x-r2) shows x-intercepts.",
            "Standard form y=ax^2+bx+c shows the y-intercept c.",
            "The sign of a decides whether the graph opens up or down.",
        ],
        "misconceptions": [
            "Reading the vertex sign backward from vertex form.",
            "Confusing x-intercepts with the y-intercept.",
            "Forgetting that a negative leading coefficient opens down.",
            "Using all real numbers as a context domain when time or length is restricted.",
            "Assuming the graph scale does not affect interpretation.",
        ],
    },
    "polynomial": {
        "review": [
            "A polynomial is a sum of powers of x with real coefficients.",
            "The degree is the highest exponent with a nonzero coefficient.",
            "Zeros are x-values where the polynomial equals zero.",
            "Factored form shows zeros and multiplicities.",
            "Polynomial division rewrites one polynomial as quotient plus remainder over divisor.",
        ],
        "misconceptions": [
            "Using the constant term to decide end behavior.",
            "Counting a repeated factor only once when multiplicity matters.",
            "Dropping zero coefficient entries during polynomial division.",
            "Confusing a remainder value with an x-intercept.",
            "Forgetting to test the original polynomial after factoring.",
        ],
    },
    "rational": {
        "review": [
            "A rational expression is a ratio of polynomials.",
            "Values that make the original denominator zero are excluded.",
            "A common factor can create a hole after cancellation.",
            "A non-cancelled denominator factor creates a vertical asymptote.",
            "Horizontal asymptotes are predicted from degrees and leading coefficients.",
        ],
        "misconceptions": [
            "Cancelling terms that are not common factors.",
            "Forgetting restrictions from the original denominator.",
            "Calling every excluded value an asymptote.",
            "Ignoring holes after simplifying.",
            "Using y-values instead of x-values for denominator restrictions.",
        ],
    },
}


PHASES = [
    {
        "id": 26,
        "topic": "Quadratic graphs",
        "subtopic": "Reading, sketching, and interpreting parabolas from multiple forms",
        "prerequisites": "quadratic factoring, completing the square, quadratic formula, coordinate graphing",
        "metadata_prereq": "vertex form, factored form, standard form, intercepts",
        "metadata_misconceptions": "vertex sign reversal, intercept confusion, axis of symmetry error, opening direction error",
        "review": COMMON["quadratic"]["review"],
        "concepts": [
            "The vertex is the turning point of a parabola.",
            "The axis of symmetry is the vertical line through the vertex.",
            "The sign and size of a control opening direction and width.",
            "x-intercepts are real zeros of the quadratic.",
            "The y-intercept occurs when x=0.",
            "A quadratic graph can be described using vertex, intercepts, and opening direction.",
        ],
        "misconceptions": COMMON["quadratic"]["misconceptions"],
        "next_topic": "Quadratic modeling",
        "exercises": [
            ex("Read vertex form", "For y=2(x-3)^2-5, identify the vertex.", "(3,-5)", "Vertex form y=a(x-h)^2+k gives vertex (h,k), so h=3 and k=-5.", visual=True),
            ex("Axis of symmetry", "Find the axis of symmetry of y=(x+4)^2+1.", "x=-4", "The vertex is (-4,1), so the axis is x=-4."),
            ex("Opening direction", "Does y=-3(x-1)^2+7 open up or down?", "down", "The coefficient a=-3 is negative, so the parabola opens down."),
            ex("Width comparison", "Which is narrower: y=x^2 or y=4x^2?", "y=4x^2", "A larger absolute value of a makes the parabola vertically steeper and narrower."),
            ex("y-intercept from standard form", "Find the y-intercept of y=2x^2-5x+8.", "(0,8)", "Set x=0; the output is the constant term 8."),
            ex("x-intercepts from factored form", "Find the x-intercepts of y=(x-2)(x+5).", "(2,0) and (-5,0)", "Set each factor equal to zero."),
            ex("Vertex from factored form", "Find the axis of symmetry of y=(x-1)(x-7).", "x=4", "The axis is halfway between the roots 1 and 7, so x=(1+7)/2=4."),
            ex("Vertex by completing square", "Find the vertex of y=x^2-6x+11.", "(3,2)", "Complete the square: y=(x-3)^2+2."),
            ex("Maximum or minimum", "Does y=-2(x+1)^2+9 have a maximum or minimum value, and what is it?", "maximum value 9", "The graph opens down, so the vertex y-value is the maximum."),
            ex("Range from vertex", "Find the range of y=3(x-2)^2-4.", "y>=-4", "The graph opens up and has minimum y-value -4."),
            ex("Graph from three features", "Sketch description: vertex (1,-3), opens up, passes through (0,-1). What is a in y=a(x-1)^2-3?", "a=2", "Use (0,-1): -1=a(1)-3, so a=2."),
            ex("Number of x-intercepts", "How many x-intercepts does y=x^2+2x+5 have?", "0", "The discriminant is 4-20=-16, so there are no real x-intercepts."),
            ex("Convert vertex to standard", "Expand y=(x+2)^2-6.", "y=x^2+4x-2", "Expand x^2+4x+4 and subtract 6."),
            ex("Convert standard to vertex", "Write y=x^2+8x+10 in vertex form.", "y=(x+4)^2-6", "Complete the square: x^2+8x+16-6."),
            ex("Match graph description", "Which formula has vertex (-2,5) and opens down: y=-(x+2)^2+5 or y=(x-2)^2+5?", "y=-(x+2)^2+5", "The (x+2) gives h=-2 and the negative coefficient opens down."),
            ex("Intercept and vertex consistency", "A parabola has roots -1 and 5. What is its axis of symmetry?", "x=2", "The axis is the average of the roots: (-1+5)/2=2."),
            ex("Context maximum height", "A height is h(t)=-16(t-2)^2+64. What is the maximum height?", "64", "The vertex gives maximum height because the parabola opens down."),
            ex("Context time at vertex", "For h(t)=-5(t-3)^2+45, when does the object reach maximum height?", "t=3", "The vertex occurs at t=3."),
            ex("Error analysis vertex", "A student says y=(x-6)^2+4 has vertex (-6,4). What is wrong?", "The x-coordinate is 6, not -6.", "Vertex form y=(x-h)^2+k uses the opposite sign inside the parentheses."),
            ex("Boss graph summary", "Summarize y=-x^2+4x+5 by giving vertex, axis, y-intercept, and x-intercepts.", "vertex (2,9), axis x=2, y-intercept (0,5), x-intercepts (-1,0) and (5,0)", "Complete the square or use symmetry; factor -x^2+4x+5=-(x-5)(x+1).", boss=True),
        ],
    },
    {
        "id": 27,
        "topic": "Quadratic modeling",
        "subtopic": "Using quadratic functions to model area, projectile, revenue, and optimization situations",
        "prerequisites": "quadratic graphs, vertex form, factoring, units, interpreting domains",
        "metadata_prereq": "quadratic graphs, vertex interpretation, equation solving, context units",
        "metadata_misconceptions": "ignoring units, accepting negative context values, using wrong vertex coordinate, confusing zeros with maximum",
        "review": COMMON["quadratic"]["review"],
        "concepts": [
            "Quadratic models often describe area, height, revenue, and symmetrical optimization.",
            "The vertex often represents a maximum or minimum in context.",
            "Zeros can represent times, break-even values, or dimensions where output is zero.",
            "The domain must fit the situation, not just the algebra.",
            "Units should be included in interpreted answers.",
            "Model parameters can be found from points or constraints.",
        ],
        "misconceptions": COMMON["quadratic"]["misconceptions"],
        "next_topic": "Polynomial end behavior",
        "exercises": [
            ex("Projectile maximum height", "A ball's height is h(t)=-16(t-2)^2+80. What is the maximum height?", "80 feet", "The vertex gives the maximum because the coefficient is negative.", visual=True),
            ex("Projectile time at maximum", "For h(t)=-16(t-3)^2+144, when is the ball highest?", "3 seconds", "The vertex occurs at t=3."),
            ex("Projectile ground time", "For h(t)=-16t^2+64t, when does the ball hit the ground after launch?", "4 seconds", "Set h=0: -16t(t-4)=0, so t=0 or t=4; after launch is 4."),
            ex("Area model", "A rectangle has width x and length 20-x. Write the area function.", "A(x)=x(20-x)=-x^2+20x", "Area is width times length."),
            ex("Area maximum", "For A(x)=-x^2+20x, what width gives maximum area?", "x=10", "The vertex x-value is -b/(2a)=-20/(2(-1))=10."),
            ex("Revenue model", "Revenue is R(p)=p(100-5p). What price maximizes revenue?", "p=10", "R(p)=-5p^2+100p has vertex p=-100/(2(-5))=10."),
            ex("Break-even values", "Profit is P(x)=-(x-2)(x-8). What production levels break even?", "x=2 and x=8", "Break-even means P(x)=0, so use the roots."),
            ex("Interpret y-intercept", "For C(x)=2x^2+5x+40, what does C(0)=40 represent?", "fixed cost of 40 units of money", "The output when x=0 is the starting cost before production."),
            ex("Find model from roots", "A profit model has zeros at 3 and 11 and opens down with a= -2. Write P(x).", "P(x)=-2(x-3)(x-11)", "Factored form uses the roots and leading coefficient."),
            ex("Find vertex from roots", "A downward parabola has zeros at 4 and 12. At what x is its maximum?", "x=8", "The vertex lies halfway between the roots."),
            ex("Fence model", "A farmer uses 60 m of fence for three sides against a wall. If width is x, write area.", "A(x)=x(60-2x)", "Two widths use 2x fence, leaving 60-2x for the length."),
            ex("Fence maximum", "For A(x)=x(60-2x), what width maximizes area?", "15 m", "A(x)=-2x^2+60x has vertex x=15."),
            ex("Context domain", "For A(x)=x(60-2x), what is the practical domain?", "0<x<30", "Width must be positive and length 60-2x must be positive."),
            ex("Dropped object", "A dropped object's height is h(t)=-16t^2+100. When is it at height 36?", "2 seconds", "Solve -16t^2+100=36, so t^2=4 and practical time is t=2."),
            ex("Bridge arch", "An arch is y=-0.25(x-8)^2+16. What is the maximum height?", "16", "The vertex y-value gives the maximum height."),
            ex("Symmetric points", "If a projectile is at the same height at t=1 and t=5, when is the maximum?", "t=3", "The axis of symmetry is halfway between 1 and 5."),
            ex("Parameter from point", "A model h(t)=a(t-2)^2+50 passes through (0,18). Find a.", "a=-8", "Substitute 18=a(4)+50, so 4a=-32 and a=-8."),
            ex("Error analysis context", "A student keeps t=-1 as a time solution for h(t)=0. What should they do?", "Reject t=-1 if time after launch is required.", "Negative time may solve the equation but not the context."),
            ex("Compare models", "Which has greater maximum: A(x)=-(x-4)^2+30 or B(x)=-2(x-5)^2+28?", "A", "A's maximum is 30 and B's maximum is 28."),
            ex("Boss revenue", "Demand is q=80-4p and revenue is R=pq. Find the price and maximum revenue.", "price 10; maximum revenue 400", "R(p)=p(80-4p)=-4p^2+80p, whose vertex is p=10 and R=400.", boss=True),
        ],
    },
    {
        "id": 28,
        "topic": "Polynomial end behavior",
        "subtopic": "Predicting polynomial graph ends from degree and leading coefficient",
        "prerequisites": "polynomial degree, leading coefficient, graph direction, function notation",
        "metadata_prereq": "degree, leading coefficient, coordinate graphing, powers of negatives",
        "metadata_misconceptions": "using constant term, ignoring leading coefficient, confusing odd and even degree, reversing left-end direction",
        "review": COMMON["polynomial"]["review"],
        "concepts": [
            "End behavior is controlled by the leading term.",
            "Even degree ends go the same direction.",
            "Odd degree ends go opposite directions.",
            "Positive leading coefficients rise to the right.",
            "Negative leading coefficients fall to the right.",
            "Lower-degree terms do not control far-left or far-right behavior.",
        ],
        "misconceptions": COMMON["polynomial"]["misconceptions"],
        "next_topic": "Polynomial multiplicity",
        "exercises": [
            ex("Even positive", "Describe the end behavior of f(x)=2x^4-3x+1.", "left up, right up", "Even degree with positive leading coefficient means both ends rise.", visual=True),
            ex("Even negative", "Describe the end behavior of f(x)=-5x^6+x^2.", "left down, right down", "Even degree with negative leading coefficient means both ends fall."),
            ex("Odd positive", "Describe the end behavior of f(x)=x^3-4x.", "left down, right up", "Odd degree with positive leading coefficient falls left and rises right."),
            ex("Odd negative", "Describe the end behavior of f(x)=-2x^5+7x.", "left up, right down", "Odd degree with negative leading coefficient rises left and falls right."),
            ex("Identify leading term", "What is the leading term of 4x-7x^3+2x^5-1?", "2x^5", "The leading term has the highest degree."),
            ex("Degree from expression", "What is the degree of -3x^7+2x^4-9?", "7", "The highest exponent is 7."),
            ex("Right-end only", "As x->infinity, what happens to f(x)=-x^4+3x?", "f(x)->-infinity", "The leading term -x^4 dominates and goes down to the right."),
            ex("Left-end only", "As x->-infinity, what happens to f(x)=3x^5-x^2?", "f(x)->-infinity", "Odd positive degree falls to the left."),
            ex("Choose graph shape", "Which polynomial could have both ends up: x^3+1, -x^4+2, or x^4-x?", "x^4-x", "Both ends up requires even degree and positive leading coefficient."),
            ex("Match degree parity", "A graph falls left and rises right. Is the degree even or odd?", "odd", "Opposite end directions indicate odd degree."),
            ex("Match leading sign", "A graph falls left and rises right. Is the leading coefficient positive or negative?", "positive", "Odd positive polynomials fall left and rise right."),
            ex("Lower terms ignored", "Does +1000 in f(x)=x^5+1000 change the end behavior?", "no", "The leading term x^5 controls far-end behavior."),
            ex("Table evidence", "A polynomial's values become very negative for large negative x and very positive for large positive x. What end behavior is shown?", "left down, right up", "The outputs decrease on the left and increase on the right."),
            ex("Minimum possible degree", "What is the least possible degree for a polynomial with left up and right down?", "1", "Opposite ends require odd degree with negative leading coefficient; degree 1 is the least."),
            ex("Degree and turns", "Can a degree 4 polynomial have 5 turning points?", "no", "A degree n polynomial has at most n-1 turning points, so degree 4 has at most 3."),
            ex("End behavior notation", "Write end behavior for f(x)=-x^3+2 using limits.", "as x->-infinity, f(x)->infinity; as x->infinity, f(x)->-infinity", "Odd negative means left up and right down."),
            ex("Compare two polynomials", "Which has the same end behavior as -3x^4+2x: 5x^4-1 or -x^6+x?", "-x^6+x", "Both are even degree with negative leading coefficient."),
            ex("Error analysis", "A student says f(x)=x^6-x has odd end behavior because of -x. What is wrong?", "The leading term x^6 controls end behavior.", "The lower-degree term does not control the graph ends."),
            ex("Build polynomial", "Give a polynomial with left down and right down.", "-x^2", "Even degree with negative leading coefficient gives both ends down."),
            ex("Boss classify", "Classify degree parity and leading sign for a graph that rises left and falls right.", "odd degree, negative leading coefficient", "Opposite ends mean odd degree; right end down means negative leading coefficient.", boss=True),
        ],
    },
    {
        "id": 29,
        "topic": "Polynomial multiplicity",
        "subtopic": "Interpreting repeated zeros and graph behavior at intercepts",
        "prerequisites": "factored polynomials, zeros, graph intercepts, polynomial end behavior",
        "metadata_prereq": "factoring, zeros, end behavior, graph intercepts",
        "metadata_misconceptions": "counting repeated factors once, crossing at even multiplicity, bouncing at odd multiplicity, missing total degree",
        "review": COMMON["polynomial"]["review"],
        "concepts": [
            "Multiplicity is the exponent on a repeated factor.",
            "Odd multiplicity usually crosses the x-axis.",
            "Even multiplicity usually touches and turns around.",
            "Higher multiplicity makes the graph flatter near the zero.",
            "The sum of multiplicities equals the degree when all factors are shown.",
            "Multiplicity helps sketch a polynomial graph from factored form.",
        ],
        "misconceptions": COMMON["polynomial"]["misconceptions"],
        "next_topic": "Polynomial division",
        "exercises": [
            ex("Identify multiplicity", "In f(x)=(x-2)^3(x+1), what is the multiplicity of x=2?", "3", "The factor x-2 has exponent 3."),
            ex("Find zeros and multiplicities", "List zeros and multiplicities for f(x)=(x+4)^2(x-1)^5.", "x=-4 mult 2; x=1 mult 5", "Each zero comes from setting a factor to zero; the exponent is multiplicity."),
            ex("Cross or bounce odd", "Does f(x)=(x-3)^3 cross or bounce at x=3?", "cross", "Odd multiplicity zeros cross the x-axis."),
            ex("Cross or bounce even", "Does f(x)=(x+2)^4 cross or bounce at x=-2?", "bounce", "Even multiplicity zeros touch and turn around."),
            ex("Total degree", "What is the degree of f(x)=2(x-1)^2(x+3)^3?", "5", "Add the multiplicities 2+3."),
            ex("End behavior with multiplicity", "Describe end behavior of f(x)=-(x-1)^2(x+2).", "left up, right down", "The total degree is 3 and the leading coefficient is negative."),
            ex("Graph behavior list", "For f(x)=(x+1)^2(x-4), identify where the graph bounces and crosses.", "bounces at -1; crosses at 4", "Multiplicity 2 is even and multiplicity 1 is odd."),
            ex("Flattening", "Which zero is flatter: multiplicity 1 or multiplicity 5?", "multiplicity 5", "Higher multiplicity creates flatter behavior near the intercept."),
            ex("Build from behavior", "Write a polynomial with a bounce at x=2 and a cross at x=-3.", "(x-2)^2(x+3)", "Even multiplicity at 2 gives bounce; odd multiplicity at -3 gives cross."),
            ex("Least degree", "What is the least degree for zeros -1 with bounce and 4 with cross?", "3", "Use multiplicity 2 at -1 and multiplicity 1 at 4."),
            ex("Sign through simple root", "If f(x) has factor (x-5), does the sign usually change at x=5?", "yes", "A multiplicity 1 root is odd, so the graph crosses and changes sign."),
            ex("Sign through double root", "If f(x) has factor (x+6)^2, does the sign usually change at x=-6?", "no", "An even multiplicity root touches and turns, so sign does not change."),
            ex("Repeated root equation", "Solve (x-2)^2(x+1)=0 and include multiplicities.", "x=2 mult 2; x=-1 mult 1", "Set each factor equal to zero and read the exponents."),
            ex("Match graph", "A graph touches at x=-2 and crosses at x=3. Which factored form fits: (x+2)^2(x-3) or (x+2)(x-3)^2?", "(x+2)^2(x-3)", "Touch at -2 needs even multiplicity there; cross at 3 needs odd multiplicity."),
            ex("Multiplicity from expanded clue", "If f(x)=(x-1)(x-1)(x+4), what is the multiplicity of x=1?", "2", "The factor x-1 appears twice."),
            ex("Error analysis", "A student says (x+2)^2 crosses at -2. What is wrong?", "Even multiplicity means the graph bounces at -2.", "Crossing is associated with odd multiplicity."),
            ex("Y-intercept from factored form", "Find the y-intercept of f(x)=(x-2)^2(x+1).", "(0,4)", "Evaluate f(0)=(-2)^2(1)=4."),
            ex("Negative leading coefficient behavior", "For f(x)=-2(x+1)^2(x-3)^2, describe end behavior.", "left down, right down", "Degree 4 is even and leading coefficient is negative."),
            ex("Construct degree 5", "Write a degree 5 polynomial with zeros 0 mult 3 and 2 mult 2.", "x^3(x-2)^2", "The multiplicities add to 5."),
            ex("Boss sketch summary", "Summarize f(x)=(x+2)^2(x-1)^3: zeros, behavior, degree, end behavior.", "zero -2 bounce; zero 1 cross; degree 5; left down right up", "Multiplicities are 2 and 3, total degree 5 with positive leading coefficient.", boss=True),
        ],
    },
    {
        "id": 30,
        "topic": "Polynomial division",
        "subtopic": "Dividing polynomials using long division and synthetic division",
        "prerequisites": "polynomial operations, factoring, exponents, linear divisors",
        "metadata_prereq": "polynomial terms, subtraction, synthetic division setup, linear factors",
        "metadata_misconceptions": "missing zero coefficient entry, sign error during subtraction, using wrong synthetic value, forgetting remainder",
        "review": COMMON["polynomial"]["review"],
        "concepts": [
            "Polynomial division rewrites dividend divided by divisor as quotient plus remainder over divisor.",
            "Long division works for any polynomial divisor.",
            "Synthetic division is a shortcut for divisors of the form x-c.",
            "Missing powers need zero coefficient entries.",
            "The remainder has degree lower than the divisor.",
            "A zero remainder means the divisor is a factor.",
        ],
        "misconceptions": COMMON["polynomial"]["misconceptions"],
        "next_topic": "Remainder theorem",
        "equation_battle": True,
        "exercises": [
            ex("Simple synthetic division", "Divide x^2+5x+6 by x+2.", "x+3 remainder 0", "Use c=-2. Synthetic division gives quotient x+3 and remainder 0."),
            ex("Synthetic with remainder", "Divide x^2+3x+5 by x+1.", "x+2 remainder 3", "Use c=-1. The quotient is x+2 and the remainder is 3."),
            ex("C value for divisor", "For division by x-4, what number is used in synthetic division?", "4", "The divisor x-c uses c=4."),
            ex("Divisor x+7", "For division by x+7, what number is used in synthetic division?", "-7", "x+7=x-(-7), so c=-7."),
            ex("Cubic by linear", "Divide x^3-2x^2-5x+6 by x-3.", "x^2+x-2 remainder 0", "Synthetic division with c=3 gives coefficients 1,1,-2,0."),
            ex("Missing term coefficient", "Divide x^3+2x+1 by x+1.", "x^2-x+3 remainder -2", "Use coefficients 1,0,2,1 with c=-1."),
            ex("Long division first step", "When dividing 2x^3+3x^2 by x, what is the first quotient term?", "2x^2", "Divide leading terms: 2x^3/x=2x^2."),
            ex("Long division binomial", "Divide x^2+5x+4 by x+1.", "x+4 remainder 0", "The dividend factors as (x+1)(x+4)."),
            ex("Remainder form", "Write (x^2+1)/(x-1) as quotient plus remainder over divisor.", "x+1+2/(x-1)", "Division gives quotient x+1 and remainder 2."),
            ex("Check division", "Check that x^2+3x+2 divided by x+1 equals x+2.", "(x+1)(x+2)=x^2+3x+2", "Multiply divisor and quotient to recover the dividend."),
            ex("Quartic synthetic", "Divide x^4-1 by x-1.", "x^3+x^2+x+1 remainder 0", "Synthetic division with c=1 produces all ones in the quotient."),
            ex("Negative synthetic value", "Divide 2x^3+x^2-8x-4 by x+2.", "2x^2-3x-2 remainder 0", "Use c=-2; the quotient coefficients are 2,-3,-2."),
            ex("Nonzero remainder meaning", "If division by x-5 has remainder 7, is x-5 a factor?", "no", "A factor must divide with remainder 0."),
            ex("Degree of quotient", "If a degree 5 polynomial is divided by a degree 1 polynomial, what is the quotient degree?", "4", "The quotient degree is 5-1=4 when leading terms divide normally."),
            ex("Divide by quadratic", "Divide x^3+2x^2-x-2 by x+2.", "x^2-1 remainder 0", "The polynomial factors by grouping as (x+2)(x^2-1)."),
            ex("Long division by quadratic", "Divide x^3+3x^2+2x+4 by x^2+1.", "x+3 remainder x+1", "Long division gives x, then 3, leaving x+1."),
            ex("Error analysis zero coefficient", "A student divides x^3+4x+1 by x-2 using coefficients 1,4,1. What is wrong?", "They omitted the 0x^2 coefficient entry.", "Synthetic division needs coefficients 1,0,4,1."),
            ex("Recover dividend", "If quotient is x^2+2, divisor is x-3, and remainder is 5, what is the dividend?", "x^3-3x^2+2x-1", "Compute (x-3)(x^2+2)+5=x^3-3x^2+2x-6+5."),
            ex("Factor from division", "If x^3-4x^2+x+6 divided by x-2 has remainder 0, what factor is confirmed?", "x-2", "Zero remainder means the divisor is a factor."),
            ex("Boss divide", "Divide 2x^4-3x^3+0x^2+5x-1 by x-1.", "2x^3-x^2-x+4 remainder 3", "Synthetic division with c=1 gives quotient coefficients 2,-1,-1,4 and remainder 3.", boss=True),
        ],
    },
    {
        "id": 31,
        "topic": "Remainder theorem",
        "subtopic": "Using polynomial evaluation to find division remainders",
        "prerequisites": "polynomial division, function notation, synthetic division, evaluating polynomials",
        "metadata_prereq": "polynomial evaluation, synthetic division, function notation, linear divisors",
        "metadata_misconceptions": "using the wrong sign for c, treating remainder as quotient, evaluating at divisor coefficient, ignoring parentheses",
        "review": COMMON["polynomial"]["review"],
        "concepts": [
            "When f(x) is divided by x-c, the remainder is f(c).",
            "The theorem finds remainders without full division.",
            "The sign of c comes from rewriting the divisor as x-c.",
            "If f(c)=0, then x-c is a factor.",
            "Remainders can be positive, negative, zero, or fractional.",
            "Evaluation and synthetic division must agree.",
        ],
        "misconceptions": COMMON["polynomial"]["misconceptions"],
        "next_topic": "Factor theorem",
        "exercises": [
            ex("Basic remainder", "Find the remainder when f(x)=x^2+3x+5 is divided by x-2.", "15", "By the remainder theorem, the remainder is f(2)=4+6+5=15."),
            ex("Divisor x+1", "Find the remainder when x^3+2x+4 is divided by x+1.", "1", "Use c=-1. f(-1)=-1-2+4=1."),
            ex("Zero remainder", "Find the remainder when x^2-5x+6 is divided by x-2.", "0", "f(2)=4-10+6=0."),
            ex("Negative remainder", "Find the remainder when f(x)=2x^2-3x+1 is divided by x-3.", "10", "f(3)=18-9+1=10."),
            ex("Remainder with negative c", "Find the remainder when f(x)=x^3-4x is divided by x+2.", "0", "Use c=-2. f(-2)=-8+8=0."),
            ex("Identify c", "For divisor x-7, what input is used in the remainder theorem?", "7", "x-7 means c=7."),
            ex("Identify c for x+5", "For divisor x+5, what input is used in the remainder theorem?", "-5", "x+5=x-(-5)."),
            ex("Compare with division", "If synthetic division of f by x-4 ends with 9, what is f(4)?", "9", "The final synthetic value is the remainder, equal to f(4)."),
            ex("Find missing constant", "Find k so f(x)=x^2+kx+3 has remainder 0 when divided by x-1.", "k=-4", "f(1)=1+k+3=k+4. Set equal to 0."),
            ex("Find missing coefficient", "Find a so f(x)=ax^2+2x-5 has remainder 7 when divided by x-2.", "a=2", "f(2)=4a+4-5=4a-1. Set 4a-1=7."),
            ex("Remainder from table", "If f(3)=-8, what is the remainder when f(x) is divided by x-3?", "-8", "The remainder is f(3)."),
            ex("Nonlinear divisor caution", "Can the remainder theorem in the form f(c) be used directly for division by x^2+1?", "no", "The simple f(c) form applies to divisors x-c."),
            ex("Remainder value interpretation", "If f(5)=0, what is the remainder when dividing by x-5?", "0", "The remainder equals f(5)."),
            ex("Evaluate carefully", "Find the remainder when f(x)=-x^3+x^2+2 is divided by x+1.", "4", "Use c=-1: -(-1)^3+(-1)^2+2=1+1+2=4."),
            ex("Standard notation", "For P(x)=3x^3-x+6, find the remainder when divided by x-1.", "8", "P(1)=3-1+6=8."),
            ex("Error analysis sign", "A student divides by x+2 and evaluates f(2). What is wrong?", "They should evaluate f(-2).", "x+2 corresponds to c=-2."),
            ex("Remainder theorem and factor", "If f(-4)=0, name a factor of f(x).", "x+4", "If f(c)=0, then x-c is a factor; here c=-4."),
            ex("Find remainder with quartic", "Find the remainder when x^4-3x^2+x is divided by x-2.", "6", "f(2)=16-12+2=6."),
            ex("Parameter boss", "Find m so x^3+mx+10 has remainder 4 when divided by x+2.", "m= -1", "Use c=-2: -8-2m+10=4, so 2-2m=4 and m=-1."),
            ex("Boss theorem link", "For f(x)=2x^3-5x+1, find remainders for division by x-1 and x+1.", "-2 and 4", "f(1)=2-5+1=-2; f(-1)=-2+5+1=4.", boss=True),
        ],
    },
    {
        "id": 32,
        "topic": "Factor theorem",
        "subtopic": "Determining polynomial factors and zeros through evaluation",
        "prerequisites": "remainder theorem, factoring, polynomial division, zeros",
        "metadata_prereq": "remainder theorem, polynomial zeros, synthetic division, factored form",
        "metadata_misconceptions": "wrong factor sign, confusing zero with y-intercept, assuming near-zero remainder counts, skipping verification",
        "review": COMMON["polynomial"]["review"],
        "concepts": [
            "x-c is a factor of f(x) exactly when f(c)=0.",
            "A zero of a polynomial corresponds to a linear factor.",
            "Synthetic division can confirm and reduce a polynomial after a factor is found.",
            "Known factors help factor higher-degree polynomials.",
            "The sign in the factor x-c is opposite the zero c.",
            "Factor theorem connects equations, graphs, and division.",
        ],
        "misconceptions": COMMON["polynomial"]["misconceptions"],
        "next_topic": "Rational expression simplification",
        "exercises": [
            ex("Check factor", "Is x-2 a factor of f(x)=x^2-5x+6?", "yes", "Evaluate f(2)=4-10+6=0."),
            ex("Check nonfactor", "Is x+1 a factor of f(x)=x^2+3x+5?", "no", "Evaluate f(-1)=1-3+5=3, not 0."),
            ex("Name factor from zero", "If f(4)=0, name a factor of f(x).", "x-4", "A zero c gives factor x-c."),
            ex("Name zero from factor", "If x+7 is a factor, what zero does the polynomial have?", "-7", "Set x+7=0 to get x=-7."),
            ex("Use synthetic division", "Given f(x)=x^3-6x^2+11x-6 and factor x-1, find the remaining quadratic factor.", "x^2-5x+6", "Synthetic division by c=1 gives quotient x^2-5x+6."),
            ex("Fully factor with known root", "Factor x^3-6x^2+11x-6 completely.", "(x-1)(x-2)(x-3)", "Use known root 1, then factor x^2-5x+6."),
            ex("Parameter for factor", "Find k so x-3 is a factor of f(x)=x^2+kx+6.", "k=-5", "Set f(3)=9+3k+6=0, so 3k=-15."),
            ex("Parameter for factor x+2", "Find a so x+2 is a factor of f(x)=ax^2+3x-2.", "a=2", "Use f(-2)=4a-6-2=0, so 4a=8."),
            ex("Graph connection", "If x-5 is a factor, what x-intercept is on the graph?", "(5,0)", "The factor gives zero x=5."),
            ex("Factor from table", "A table shows f(-3)=0. Name a factor.", "x+3", "Zero -3 corresponds to x-(-3)=x+3."),
            ex("Check multiple candidates", "Which is a factor of x^3+x^2-4x-4: x-2 or x+2?", "x-2 and x+2", "f(2)=8+4-8-4=0 and f(-2)=-8+4+8-4=0."),
            ex("Divide after factor", "If x+1 is a factor of x^3+4x^2+x-6, find the quotient.", "x^2+3x-2", "Synthetic division with c=-1 gives quotient coefficients 1,3,-2."),
            ex("Error analysis sign", "A student says f(3)=0 means x+3 is a factor. What is wrong?", "The factor should be x-3.", "A zero c gives factor x-c."),
            ex("Repeated factor", "If f(x)=(x-2)^2(x+1), is x-2 a factor?", "yes", "The factor appears with multiplicity 2."),
            ex("Least polynomial", "Write a monic quadratic with factors x-4 and x+1.", "x^2-3x-4", "Multiply (x-4)(x+1)."),
            ex("Find missing constant", "Find c so x-5 is a factor of x^2-2x+c.", "c=-15", "Set f(5)=25-10+c=0."),
            ex("Use factor theorem before solving", "Why does f(2)=0 help factor a cubic?", "It confirms x-2 is a factor, so division reduces the cubic to a quadratic.", "The factor theorem turns a zero into a known divisor."),
            ex("Check factor with negative leading", "Is x+3 a factor of -x^2-5x-6?", "yes", "Evaluate at -3: -9+15-6=0."),
            ex("Find all roots after known factor", "Given x-2 is a factor of x^3-4x^2+x+6, find all roots.", "x=2, 3, -1", "Divide by x-2 to get x^2-2x-3=(x-3)(x+1)."),
            ex("Boss factor theorem", "Find a so x+4 is a factor of f(x)=2x^3+ax+8.", "a=-15", "Use f(-4)=-128-4a+8=0, so -120-4a=0.", boss=True),
        ],
    },
    {
        "id": 33,
        "topic": "Rational expression simplification",
        "subtopic": "Simplifying rational expressions by factoring and cancelling common factors",
        "prerequisites": "factoring, polynomial expressions, domain restrictions, fraction simplification",
        "metadata_prereq": "factoring, common factors, denominator restrictions, polynomial multiplication",
        "metadata_misconceptions": "cancelling terms instead of factors, losing restrictions, sign cancellation error, treating addition like multiplication",
        "review": COMMON["rational"]["review"],
        "concepts": [
            "Factor numerator and denominator before cancelling.",
            "Only common factors may be cancelled.",
            "Restrictions come from the original denominator.",
            "A simplified expression may hide excluded values.",
            "Signs can be factored out to reveal common binomials.",
            "Simplification should be checked by multiplication.",
        ],
        "misconceptions": COMMON["rational"]["misconceptions"],
        "next_topic": "Rational restrictions and holes",
        "equation_battle": True,
        "exercises": [
            ex("Cancel monomial factor", "Simplify 6x^2/(3x).", "2x, x != 0", "Cancel common factor 3x; x=0 is excluded from the original denominator."),
            ex("Cancel binomial factor", "Simplify (x^2-9)/(x-3).", "x+3, x != 3", "Factor numerator as (x-3)(x+3), then cancel x-3."),
            ex("Factor trinomial", "Simplify (x^2+5x+6)/(x+2).", "x+3, x != -2", "Factor numerator as (x+2)(x+3)."),
            ex("Cancel denominator factor", "Simplify (x^2-4)/(x^2+x-6).", "(x+2)/(x+3), x != 2,-3", "Factor to (x-2)(x+2)/((x+3)(x-2)) and cancel x-2."),
            ex("GCF numerator", "Simplify (4x^2+8x)/(2x).", "2x+4, x != 0", "Factor numerator 4x(x+2), divide by 2x to get 2(x+2)."),
            ex("GCF both", "Simplify (3x^2-12x)/(6x).", "(x-4)/2, x != 0", "Factor 3x(x-4) over 6x, then cancel 3x."),
            ex("Difference of squares both", "Simplify (x^2-16)/(x^2-8x+16).", "(x+4)/(x-4), x != 4", "Factor numerator (x-4)(x+4) and denominator (x-4)^2."),
            ex("Opposite binomials", "Simplify (x-5)/(5-x).", "-1, x != 5", "Since 5-x=-(x-5), the ratio is -1."),
            ex("No cancellation", "Can (x+3)/(x+5) be simplified by cancelling x?", "no", "x is not a common factor; it is part of sums."),
            ex("Cancel common factor with signs", "Simplify (2-x)/(x-2).", "-1, x != 2", "2-x=-(x-2)."),
            ex("Factor by grouping", "Simplify (x^2+3x)/(x^2+5x+6).", "x/(x+2), x != -2,-3", "Factor numerator x(x+3) and denominator (x+2)(x+3)."),
            ex("Complex trinomial", "Simplify (2x^2+7x+3)/(2x+1).", "x+3, x != -1/2", "Factor numerator as (2x+1)(x+3)."),
            ex("Restrictions after cancellation", "Simplify (x^2-1)/(x-1) and state restrictions.", "x+1, x != 1", "The original denominator excludes x=1 even after cancellation."),
            ex("Multiple restrictions", "Simplify (x^2+x-6)/(x^2-4).", "(x+3)/(x+2), x != -2,2", "Factor numerator (x+3)(x-2) and denominator (x-2)(x+2)."),
            ex("Rational expression multiplication", "Simplify [(x^2-4)/(x+3)] * [(x+3)/(x-2)].", "x+2, x != -3,2", "Factor x^2-4 and cancel x+3 and x-2."),
            ex("Rational expression division", "Simplify [(x^2-9)/(x+1)] divided by [(x+3)/(x+1)].", "x-3, x != -1,-3", "Multiply by the reciprocal and cancel x+1 and x+3."),
            ex("Error analysis term cancellation", "A student simplifies (x+4)/(x+7) to 4/7. What is wrong?", "They cancelled terms, not common factors.", "Only factors common to numerator and denominator can cancel."),
            ex("Check simplified form", "Is (x^2-25)/(x+5) equivalent to x-5 for all x?", "no; x=-5 is excluded", "The simplified rule matches except at the original denominator zero."),
            ex("Build expression", "Create a rational expression that simplifies to x+2 but excludes x=3.", "((x+2)(x-3))/(x-3)", "The common factor cancels but x=3 remains excluded."),
            ex("Boss simplify", "Simplify (x^2-6x+9)/(9-x^2) with restrictions.", "(x-3)/(3+x) times -1 or -(x-3)/(x+3), x != 3,-3", "Factor numerator (x-3)^2 and denominator (3-x)(3+x)=-(x-3)(x+3).", boss=True),
        ],
    },
    {
        "id": 34,
        "topic": "Rational restrictions and holes",
        "subtopic": "Identifying excluded values, holes, and vertical asymptotes from rational functions",
        "prerequisites": "rational expression simplification, factoring, domain restrictions, graph features",
        "metadata_prereq": "factoring, denominator zeros, cancellation, rational graphs",
        "metadata_misconceptions": "all restrictions are asymptotes, cancelled factors disappear from domain, holes have no y-coordinate, using simplified denominator only",
        "review": COMMON["rational"]["review"],
        "concepts": [
            "Restrictions come from zeros of the original denominator.",
            "A cancelled denominator factor creates a hole.",
            "A non-cancelled denominator factor creates a vertical asymptote.",
            "The x-coordinate of a hole is the cancelled restriction.",
            "The y-coordinate of a hole is found from the simplified function.",
            "Domain excludes both holes and vertical asymptotes.",
        ],
        "misconceptions": COMMON["rational"]["misconceptions"],
        "next_topic": "Rational asymptotes",
        "exercises": [
            ex("Find restrictions", "Find restrictions for f(x)=1/(x-4).", "x != 4", "The denominator is zero at x=4."),
            ex("Two restrictions", "Find restrictions for f(x)=1/((x-2)(x+3)).", "x != 2,-3", "Both denominator factors can be zero."),
            ex("Hole from cancellation", "For f(x)=(x^2-9)/(x-3), identify the hole x-value.", "x=3", "The factor x-3 cancels, so the excluded value becomes a hole."),
            ex("Hole coordinate", "Find the hole of f(x)=(x^2-9)/(x-3).", "(3,6)", "Simplify to x+3, then evaluate at x=3 to get y=6."),
            ex("Vertical asymptote", "Find the vertical asymptote of f(x)=1/(x+5).", "x=-5", "The denominator factor does not cancel."),
            ex("Hole and asymptote", "For f(x)=((x-1)(x+2))/((x-1)(x-3)), identify the hole and vertical asymptote.", "hole at x=1; vertical asymptote x=3", "The x-1 factor cancels; x-3 remains in the denominator."),
            ex("Hole y-coordinate", "Find the hole coordinate for f(x)=((x-1)(x+2))/((x-1)(x-3)).", "(1,-3/2)", "Simplify to (x+2)/(x-3), then plug in x=1 to get 3/-2."),
            ex("Domain with hole and asymptote", "Find the domain of f(x)=((x+4)(x-2))/((x-2)(x+1)).", "all real x except x=2 and x=-1", "Both original denominator zeros are excluded."),
            ex("No hole", "Does f(x)=(x+1)/(x-2) have a hole?", "no", "No common factor cancels."),
            ex("Cancelled factor only", "For f(x)=(x+5)/(x+5), what is the domain and graph feature?", "x != -5; hole at (-5,1)", "The expression simplifies to 1, but x=-5 is excluded."),
            ex("Factor first", "Find holes of f(x)=(x^2+x-6)/(x-2).", "hole at x=2", "Factor numerator as (x+3)(x-2), so x-2 cancels."),
            ex("Hole coordinate after factoring", "Find the hole coordinate of f(x)=(x^2+x-6)/(x-2).", "(2,5)", "After cancellation, the simplified function is x+3; at x=2, y=5."),
            ex("Asymptote after factoring", "Find the vertical asymptote of f(x)=(x^2-4)/(x^2-5x+6).", "x=3", "Factor to (x-2)(x+2)/((x-2)(x-3)); x-2 cancels and x-3 remains."),
            ex("Hole after factoring", "Find the hole of f(x)=(x^2-4)/(x^2-5x+6).", "(2,-4)", "Factor to (x-2)(x+2)/((x-2)(x-3)), cancel x-2, then evaluate (x+2)/(x-3) at x=2 to get -4."),
            ex("Domain after simplification", "Simplify f(x)=(x^2-4)/(x^2-5x+6) and state the domain restrictions.", "(x+2)/(x-3), x != 2,3", "The original denominator factors as (x-2)(x-3), so both x=2 and x=3 are excluded even though x-2 cancels."),
            ex("Error analysis all asymptotes", "A student says f(x)=((x-2)(x+1))/((x-2)(x-5)) has asymptotes x=2 and x=5. What is wrong?", "x=2 is a hole, not an asymptote.", "The factor x-2 cancels."),
            ex("Restriction from original", "For f(x)=(x^2-1)/(x-1), can x=1 be used after simplifying?", "no", "The original denominator is zero at x=1, so it remains excluded."),
            ex("Build with hole", "Build a rational function with a hole at x=4 and vertical asymptote x=-2.", "(x-4)/((x-4)(x+2))", "The x-4 factor cancels to make a hole, while x+2 remains."),
            ex("Graph interpretation", "A graph follows y=x+1 except for an open circle at (2,3). What rational feature is shown?", "a hole at (2,3)", "An open missing point on an otherwise defined curve is a hole.", visual=True),
            ex("Boss classify", "For f(x)=((x+3)(x-1))/((x+3)(x-4)), give domain restrictions, hole, and vertical asymptote.", "x != -3,4; hole (-3,4/7); vertical asymptote x=4", "Cancel x+3, simplify to (x-1)/(x-4), and evaluate at x=-3 to get -4/-7=4/7.", boss=True),
        ],
    },
]
