# =============================================================================
# rebuild-curriculum.ps1
# Rebuilds game/config/curriculum.config.js as a 65-arena Bible-driven map:
#   arenas 1-6   = 6 condensed pre-algebra warm-ups (reuse existing generators)
#   arenas 7-65  = the 59 Bible phases (P001..P059), served from QUESTION_TEMPLATES
# Each arena KEEPS the body (name/kind/system/fact) that lived in that slot in the
# original curriculum, so every planet's photo + astronomy stays correct.
#   Run:  powershell -ExecutionPolicy Bypass -File tools/rebuild-curriculum.ps1
# =============================================================================
$ErrorActionPreference = 'Stop'
$root = if ($PSScriptRoot) { Split-Path $PSScriptRoot -Parent } else { (Get-Location).Path }
$src  = Join-Path $root 'tools\curriculum-bodies-source.js'      # stable body source (original config)
$out  = Join-Path $root 'game\config\curriculum.config.js'
$status = Join-Path $root 'Precalculus_Odyssey_Bible_v5_Codex_Package\STATUS.json'

# ---- 1. extract bodies for slots 1..65 from the original config rows ----
$lines = Get-Content -LiteralPath $src -Encoding UTF8
$rowRe = "^\s*\['([^']*)',\s*'([^']*)',\s*'([^']*)',\s*'([^']*)',\s*'([^']*)',\s*(true|false),\s*'([^']*)'\]"
$bodies = New-Object System.Collections.ArrayList
foreach ($l in $lines) {
  if ($l -match $rowRe) {
    [void]$bodies.Add([ordered]@{ systemId=$Matches[3]; name=$Matches[4]; kind=$Matches[5]; real=($Matches[6] -eq 'true'); fact=$Matches[7] })
    if ($bodies.Count -ge 65) { break }
  }
}
if ($bodies.Count -lt 65) { throw "Only extracted $($bodies.Count) bodies (need 65)" }
Write-Host ("Extracted {0} bodies from the original curriculum." -f $bodies.Count)

# ---- 2. the 6 condensed pre-algebra warm-ups (topic, mechanic, reuse old generator #) ----
$prealg = @(
  @{ topic='Integers: adding, subtracting, multiplying & dividing'; mech='mcOnly';      gen=4 }
  @{ topic='Order of operations (BODMAS)';                          mech='mcThenMorph'; gen=6 }
  @{ topic='Factors, multiples & prime numbers';                    mech='mcOnly';      gen=9 }
  @{ topic='Powers & the index laws';                               mech='directInput'; gen=16 }
  @{ topic='Square & cube roots';                                   mech='directInput'; gen=20 }
  @{ topic='Standard form (large & small numbers)';                 mech='mcOnly';      gen=22 }
)

# ---- 3. the 59 Bible topics (from STATUS.json) ----
$st = Get-Content -LiteralPath $status -Raw -Encoding UTF8 | ConvertFrom-Json
$bibleTopics = @{}
foreach ($p in $st.phases) { $bibleTopics[[int]$p.phase] = $p.topic }

# Which Bible phases keep the native Equation Battle balance solver / formula mode.
$mechOverride = @{ 1='numeric'; 2='numeric'; 3='numeric'; 4='formula'; 6='numeric' }  # P001-P003 solve, P004 change-of-subject, P006 battle

# ---- 4. build the 65 rows: [topic, mechanic, systemId, bodyName, bodyKind, real, fact, phaseId, gen] ----
$rows = New-Object System.Collections.ArrayList
for ($i = 0; $i -lt 65; $i++) {
  $b = $bodies[$i]
  if ($i -lt 6) {
    $p = $prealg[$i]
    [void]$rows.Add(@($p.topic, $p.mech, $b.systemId, $b.name, $b.kind, $b.real, $b.fact, '', $p.gen))
  } else {
    $phaseNum = $i - 5                       # arena 7 -> phase 1
    $phaseId  = 'P{0:D3}' -f $phaseNum
    $topic    = $bibleTopics[$phaseNum]
    $mech     = if ($mechOverride.ContainsKey($phaseNum)) { $mechOverride[$phaseNum] } else { 'mcOnly' }
    [void]$rows.Add(@($topic, $mech, $b.systemId, $b.name, $b.kind, $b.real, $b.fact, $phaseId, 0))
  }
}

# ---- 5. emit curriculum.config.js (build the jagged JSON array by hand; ConvertTo-Json
#         mishandles arrays-of-arrays) ----
function Js-Str($s){ return '"' + ((([string]$s) -replace '\\','\\') -replace '"','\"') + '"' }
$rowStrs = @()
foreach ($r in $rows) {
  $fields = @( (Js-Str $r[0]), (Js-Str $r[1]), (Js-Str $r[2]), (Js-Str $r[3]), (Js-Str $r[4]),
               $(if ($r[5]) { 'true' } else { 'false' }), (Js-Str $r[6]), (Js-Str $r[7]), ([string]([int]$r[8])) )
  $rowStrs += '[' + ($fields -join ',') + ']'
}
$rowsJson = '[' + ($rowStrs -join ',') + ']'

$header = @'
  // ============================================================================
  // CONFIG - Curriculum: the 65-arena Bible-driven precalculus map.
  // GENERATED by tools/rebuild-curriculum.ps1 - do not hand-edit; edit the script.
  // Arenas 1-6 = condensed pre-algebra warm-ups (reuse existing generators via `gen`).
  // Arenas 7-65 = the 59 Bible phases (P001..P059); each carries a `phaseId` and is
  // served from QUESTION_TEMPLATES (04-logic.js). Every arena keeps the astronomical
  // body that lived in its slot in the original 187-arena map, so photos + astronomy
  // stay correct. Row = [topic, mechanic, systemId, bodyName, bodyKind, real, fact, phaseId, gen].
  // ============================================================================

'@

$body = @'
  var CURRICULUM = [];
  function _genCode(n){ var v=n+1000,s=''; for(var i=0;i<4;i++){ s=String.fromCharCode(65+(v%26))+s; v=Math.floor(v/26); } return s; }
  (function(){
    for (var i=0;i<CURRICULUM_ROWS.length;i++){
      var r=CURRICULUM_ROWS[i], n=i+1;
      CURRICULUM.push({
        n:n, worldId:r[2], systemId:r[2], origSystem:r[2],
        topic:r[0], mechanic:r[1], code:_genCode(n),
        phaseId: r[7] || null, gen: r[8] || null,
        body:{ name:r[3], kind:r[4], real:r[5]!==false, fact:r[6]||'' }
      });
    }
    ['SEED','GROW','ROOT','WIND','LAKE','FIRE','SAND','VOID','HERO','STAR'].forEach(function(c,i){ if(CURRICULUM[i]) CURRICULUM[i].code=c; });
    if (typeof STAR_SYSTEMS !== 'undefined'){
      STAR_SYSTEMS.forEach(function(sys){
        var rows=CURRICULUM.filter(function(a){ return a.systemId===sys.id; });
        sys.planets=rows.length;
        sys.arenaStart=rows.length?rows[0].n:null;
        sys.arenaEnd=rows.length?rows[rows.length-1].n:null;
      });
    }
    if (typeof chapters !== 'undefined'){
      chapters.forEach(function(ch){
        var rows=CURRICULUM.filter(function(a){ return a.systemId===ch.id; });
        ch.roomCount=rows.length;
        ch.startArena=rows.length?rows[0].n:0;
        ch.endArena=rows.length?rows[rows.length-1].n:0;
      });
    }
  })();

  function getArena(n){ return CURRICULUM[n-1] || null; }
  function arenasForSystem(id){ return CURRICULUM.filter(function(a){ return a.systemId===id; }); }
  function arenasForWorld(id){ return CURRICULUM.filter(function(a){ return a.worldId===id; }); }
  function arenaByCode(code){ var up=(code||'').toUpperCase(); for(var i=0;i<CURRICULUM.length;i++) if(CURRICULUM[i].code===up) return CURRICULUM[i]; return null; }
  var CURRICULUM_MAX = CURRICULUM.length;
'@

$js = $header + "  var CURRICULUM_ROWS = " + $rowsJson + ";`n`n" + $body + "`n"
[System.IO.File]::WriteAllText($out, $js, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0}  ({1} arenas, {2:N0} KB)" -f (Split-Path $out -Leaf), $rows.Count, ((Get-Item $out).Length/1KB))
Write-Host ("Pre-algebra 1-6, Bible 7-65 (P001-P059). Systems used: " + (($rows | ForEach-Object { $_[2] } | Select-Object -Unique) -join ', '))
